### ISSUE TITLE
How to handle items contained in consultations which relate to supported clinical areas but are out of scope of that area?

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#1009]
How does a provider handle the following items contained in a consultation when responding to a consultation request?

- Test Requests not in the scope of Investigations
- Inbound Referrals not in scope of Referrals (scope is outbound only)
- Completed Diary Entries not in the scope of Diary Entries (scope is incomplete only)

Specification update required to explicitly state how these are handled

**Comment by martinhillyard** [comment]
Change applied and ready for review

**Comment by martinhillyard** [comment]
Amended to remove Inbound referrals from this change as per #1013

**Comment by mstephens-xsl** [comment]
Can this be closed? @martinhillyard
