### ISSUE TITLE
How to handle items linked to problems which relate to supported clinical areas but are out of scope of that area?

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#1010]
How does a provider handle the following items linked to a problem when responding to a problems request?

- Test Requests not in the scope of Investigations
- Inbound Referrals not in scope of Referrals (scope is outbound only)
- Completed Diary Entries not in the scope of Diary Entries (scope is incomplete only)

Specification update required to explicitly state how these are handled

**Comment by martinhillyard** [comment]
Update applied but excluding inbound referrals as these are now covered by #1013

**Comment by mstephens-xsl** [comment]
Can this be closed? @martinhillyard
