### ISSUE TITLE
Update Problem guidance to include all 1.5 clinical areas

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#1012]
extension[relatedClinicalContent] includes a list of resources which it can reference. This needs to be updated to version 1.5 content (currently at v1.3)

**Comment by martinhillyard** [comment]
Change applied ready for review / release

**Comment by martinhillyard** [comment]
This also applies to the actualProblem extension

**Comment by martinhillyard** [comment]
Additional change applied and ready for review / release

**Comment by mstephens-xsl** [comment]
Can this be closed? @martinhillyard
