### ISSUE TITLE
Multi area searches - Pre defined search

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#1023]
The following question was raised by EMIS:
"https://gpc-structured-1-5-0.netlify.app/accessrecord_structured_development_searchmultiareasearches#pre-defined-search-1---last-3-consultations-last-1-years-medications-allergies-and-problems

"name": "includeMedication",
	        "part": [
			{
			  "name": "medicationSearchFromDate",
			  "valueDate": "today()-one year"
			}
	      ]

(today()-one year)  What is "one year"

The answer is 365 days - this requires update to the specification

**Comment by PeteSalis** [comment]
Updated to be -365 days in the example
