### ISSUE TITLE
Investigations - Filing Comments Value

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#1024]
EMIS query:
"The spec states that this field should be populated with the code of the Test Group Header, what if the report has no header and just a single result?
Would this be populated with the code of the test result in this scenario? or not populated?
The manual tests ask for the value from the test result and/or the test group header to be also found in the value of the filing comment, this doesnt match the spec

https://gpc-structured-1-5-0.netlify.app/accessrecord_structured_development_observation_filingcomments"

PS: Use the code from the test result for the value.

This requires update to the 1.5.0 Spec

**Comment by martinhillyard** [comment]
Change made to profile guidance. Release note required

**Comment by martinhillyard** [comment]
Added release note
