### ISSUE TITLE
Add issued element to test group header observation guidance

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#1035]
Update the guidance for the observation profile when used for the test group header in investigation to move it from do not use to being mandatory to match the GPC observation profile.
Guidance to advice to use the same date as the diagnostic report will use for issued as a default / in the absence of any more specific date.

Also move interpretation out of not in use to be made available to populate.

**Comment by PeteSalis** [comment]
Added these two fields to the test group header page.
