### ISSUE TITLE
#4709 SEV4: Consultations - reference to the actual problem observation

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#1042]
Patient:  946 569 9918 (Magre)
This looks like it is general behaviour that the first instance of a problem does not include the problem observation within the consultation structure, only the reference to the problem header (subsequent reference to a problem in consultations are the reverse, there is a problem category with the observation but the problem header is not linked). The observation is included in the list of uncategorised in consultations but is not part of the consultation. The obvservation includes a reference to the encounter.
Example, Probelm: Suspected COVID-19; Consultation: Telephone call to a patient (14-Dec-2010 10:18)
Encounter: 472F4B2D-83A3-4E4D-B9D0-079B16CA9009
Observation: 1DBFC8C2-3321-414F-861D-D094799EF9DC

MH  may be a duplicate with #4642 - 12/1

12-01-2011 MH - EMIS have implemented based on diagram at https://gpc-structured-1-5-0.netlify.app/accessrecord_structured_development_consultation_guidance.html#consultation-notes (see example diagram showing SOAP headers), which will need updating / additional narrative inline with change

20-01-11 tested and accepted under #4642, keeping open as per note regarding spec review / update

**Comment by martinhillyard** [comment]
Release note added
