### ISSUE TITLE
Filing comments not linked down from parent

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#1044]
Investigations -> filing comments are semi orphaned as they cannot be navigated to directly from their parent. This makes travesing the FHIR much more difficult than it need be. Their parents are 'Test Group Header' or 'Test Result' both of which have a 'Related' property. This property (related.type = has-member) could be used to point to the filing comments.

Resolution: add to spec

**Comment by martinhillyard** [comment]
Images to update

Linkages
- FHIR Model
- Consultations
- Problems
- Investigations
- Multiple Clinical Areas (Summary)

Problems
- Relationships diagram

**Comment by martinhillyard** [comment]
Release note added
