### ISSUE TITLE
Demonstrator - current version

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#105]
The Patient Summary section for TPP patient has the following problems:

Patient Summary Section has Key Indicators, Warnings, Investigations and Recalls which are out of scope for Stage 1
Patient Summary Section Active Probs has table layout for Current Repeat Medications and vice versa
Patient Summary Section Current Med Issues missing columns
Investigations still on Menu

**Comment by michaelmeasures** [comment]
@jackiebarnes I'm closing this issue and will create a new one over on the Demonstrator repository (https://github.com/nhs-digital/gpconnect) as this issue doesn't relate to the specification.
