### ISSUE TITLE
Problem filter

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#1064]
Where problems are linked in an hierarchy, but only some of the linked problems match the search filter, should all problems be returned anyway so that the association between the problems cannot be lost

**Comment by PeteSalis** [comment]
Added a section for 'Related problem headers not returned due to search criteria' to the retrieve a patient record page.

**Comment by PeteSalis** [comment]
Added a link in the problems guidance page to the paragraph already written.
