### ISSUE TITLE
Ensure Consumer Audit Data Item reqs elaborated explicitly

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#107]
Particularly to cover consumer portal architectures to ensure that the end-user's originating organisation is recorded in the consumer appl audit trail, not the org which may be operating the portal

**Comment by adamjlees** [comment]
@jackiebarnes see issue #71 
I've made some changes to the topologies and cross-org audit pages to cover this area.  Can you give the changes a look please to see if this covers your requirements   9da7e6b

**Comment by michaelmeasures** [comment]
Closing as a duplicate.
