### ISSUE TITLE
Uplift the non functional requirements to include details of technical switch-on for the GP Connect APIs

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#108]
Provider systems SHALL be deployed with the provider APIs enabled by default.

Provider systems MAY provide a mechanism for a data controller at an organisation (i.e. an individual GP practice) to choose to disable/enable the provider APIs.

Provider systems MAY allow each capability to be disabled/enabled independently of each other (i.e. Access Record vs. Appointments vs. Tasks).

**Comment by jackiebarnes** [comment]
Michael – does your 2nd sentence below provide a mixed message given that we have said local org data-sharing settings should not be applied given DS org validation by SSP?



Regards

Jackie Barnes
Senior Business Analyst
GPSoC  GP Connect Team
NHS Digital

DDI:                 0113 3973076
Mobile:             07825 118589
email:               jackie.barnes8@nhs.net
                        www.digital.nhs.uk<http://www.digital.nhs.uk/>
                        @NHSDigital

Trevelyan Square, Boar Lane, Leeds LS11 6AE

General enquiries:  0300 303 5678
enquiries@nhsdigital.nhs.uk

**Comment by michaelmeasures** [comment]
@jackiebarnes  I've changed the wording slightly in the pack to reflect it's a global technical on/off mechanism and thus by implication not organisation by organisation in nature.
