### ISSUE TITLE
Review prescription type definition for med request

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#1129]
Check use and description of acute delayed / delayed prescribing.
Change Mandatory to Required in Optionality.

**Comment by PeteSalis** [comment]
Do we actually need to make this change. I think that the use of text in the codable concept is fine. Also the current examples contain delayed prescribing so guessing this is still out in the wild.

Need to take those out of the examples if they are not in live.

**Comment by martinhillyard** [comment]
not changed optionality but added codes against the prescription type to make explicit that delayed acute and delayed prescribing are equivalent. Haven't changed the name so as to indicate that delayed prescribing is acute only.
