### ISSUE TITLE
Default date range if only a start or end date parameter passed in getCareRecord

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#114]
In reviewing a providers test evidence it was noticed that for our automated test which checks that the correct variation of date parameters is accepted in the Period element of the "gpc.getcarerecord" operation request, if you only pass the end date they default to 01/01/1900. If you only pass the end date the provider system should really return all records since the start of time.

This raises the question what is our expectation, especially since we have mandated a specific wording for the applied date range which requires both a start and an end date.

The scenario where only a start or an end date need to be considered and the GP Connect program needs to update the specification to cater for the possibility of someone only sending a start date or an end date. The options are probably:

1. Have different wording for the date range banner.
2. Restrict the request to only be allowed if both start and end dates are included with the Period parameter, theis might be bad as it restricts the capabilities of the api.

**Comment by michaelmeasures** [comment]
@james-answer the mandated wording around the start and end date wasn't meant to move GP Connect away from handling the Period data type inline with the FHIR standard. Hence, I would suggest in the next release of the specification we provide some additional wording to cater for when a start or end are not specified.

**Comment by jackiebarnes** [comment]
DL Ticket HDL-146 - Proposed Decision, awaiting team confirmation  = 
No end date = all data from start date onwards (including future where applicable) 
No start date = all data until the end date 

Proposal on Section Banner Date Line: 

No Consumer End date supplied = “All Data Items from [Start Date]” 

No Consumer Start date = "All Data Items until [End Date]"

**Comment by tim1ford** [comment]
Update in 0.7.0 to:

### Date banner ###

The provider **SHALL** supply all matching dates/times, e.g. the period 2011-05-23 to 2011-05-27 includes all items with times from the start of the 23rd May through to the end of the 27th of May.

If no end date is supplied, the provider **SHALL** supply all data from start date onwards (including future where applicable).

If no start date is supplied, the provider **SHALL** supply all data until the end date.

#### Applied date ranges ####

Consumer systems **SHALL** display the date range applied to a section's data, as supplied by the provider where applicable, beneath the section header.

```html
<div>
	<p>For the period 'dd-mmm-yyyy' to 'dd-mmm-yyyy'</p>
</div>
```

If no consumer end date: 

```html
<div>
	<p>All data items from [Start Date]</p>
</div>
``` 

If no consumer start date:

```html
<div>
	<p>All data items until [End Date]</p> 
</div>
``` 

#### Default date ranges ####

Where the consumer system has not supplied a date range, then where applicable and while the default is for ALL items to be provided, the following message **SHALL** be supplied by the provider and displayed by the consumer system beneath the section header.

```html
<div>
	<p>All relevant items</p>
</div>
```
