### ISSUE TITLE
Add documentReference resource as a valid inclusion in some clinical areas

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#1147]
A documentReference may be referenced by some profiles but is not referenced in the Linkages and API definition pages. The currently specification is unclear as to whether to return the reference only or the associated resource as well.

**Comment by martinhillyard** [comment]
Detail added to Linkages page and referrals diagram updated. Release note required

**Comment by martinhillyard** [comment]
Release note added

**Comment by mstephens-xsl** [comment]
API page has been updated and release note added.
