### ISSUE TITLE
Encounters limit on summary screen

### ISSUE THREAD

**Issue by chrisbloe** [nhsconnect/gpconnect#115]
The HTML Views "Summary" page specification contains a ["Last 3 Encounters"](https://nhsconnect.github.io/gpconnect/accessrecord_view_summary.html#last-3-encounters) link to the Encounters HTML section of the specification for guidance however this does not cover what should be included on the Summary page.

The spec suggests the summary screen display only the most recent 3 encounters, so should the title on the summary page be "Last 3 Encounters", or "Recent Encounters" rather than "Encounters" as stated on the Encounters HTML specification page? Also, are we sure we want the quantity to be 3?

We may also wish to add a banner for further clarification such as: "Only the most recent encounters are displayed, visit the Encounters section to see all Encounters."

Additionally, the number of table columns listed for Encounters doesn't match the [HTML view example](https://nhsconnect.github.io/gpconnect/accessrecord_view_encounters.html).

**Comment by michaelmeasures** [comment]
@chrisbloe the intention (which isn't clear) was that the header text "Last 3 Encounters" should be used in the summary and the format / details making up this sub-section is the same as full Encounters view. If it specifies "Last 3 Encounters" then I think adding a banner isn't really required.
