### ISSUE TITLE
update error for uncategorised data dates

### ISSUE THREAD

**Issue by mstephens-xsl** [nhsconnect/gpconnect#1153]
The entry in the error handling table that checks dates for the uncategorisedDataSearchPeriod needs to be updated so that the dates are stated correctly.

**Comment by tmay2** [comment]
@mstephens-xsl I have made the changes and committed to the feature/1.5.0 branch: https://github.com/nhsconnect/gpconnect/commit/ae0951f11da636e899ce8e06af47da76bf8905f7
