### ISSUE TITLE
Broken link in documents spec

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#1159]
On the page,

https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents.html

Search for a patients documents link is broken and giving a 404 error

**Comment by rajiv-bhatia** [comment]
This has been fixed in [7255ec0](https://github.com/nhsconnect/gpconnect/commit/7255ec01d1759ecde9b3ed8bf26c233c214b6a6e)
