### ISSUE TITLE
Search for free slots snippit - non compliant URL

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#116]
The C# snippits provided in the API Use Cases contain a call to "http://gpconnect.fhir.nhs.net/fhir/". This does not conform to the URL format guidelines which we have specified in spine integration details at https://nhsconnect.github.io/gpconnect/integration_spine_directory_service.html

Rationale: We need a uniform message on Base URL formats - the present pack contains mixed messages.

When resolving this issue, we should look also at the other capability packs to ensure that they also do not contain any non-conformant URLs

**Comment by michaelmeasures** [comment]
Sounds good.

**Comment by james-answer** [comment]
Fixed as part of #121
