### ISSUE TITLE
Retrieve patients appointments - clarify function of [Id] parameter

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#117]
appointments_use_case_retrieve_a_patients_appointments.html

The guidance should be uplifted that Clarify that [id] is the logical patient identifier at the organisation, and that the client must first resolve the NHS number to this using the Find Patient Foundation Capability API call.

**Comment by michaelmeasures** [comment]
@briandiggle would be good to provide a link to the [Find A Patient](https://nhsconnect.github.io/gpconnect/foundations_use_case_find_a_patient.html) page. It's also important to note that in many real-world usages you will already have these details (i.e. if you've accessed the patient's record using the $gpc.getcarerecord) call.

**Comment by briandiggle** [comment]
Uplifted content as stated above
