### ISSUE TITLE
DocumentReference.author search parameter

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect#1184]
Analysis around the DocumentReference.author search parameter. Currently the user has the ability to search by who and/r what authored the document, i.e. Practitioner or Organisation

**Options**
Should the search parameter be refined, i.e remove the ability to search using a Practitioner as the use case for this seems limited. 

If it remains should the abiity to search via a Practitioner be limited to only specific User IDs (SDS only?)

Should the ability to search by author be removed completely?

If the search parameter remains and Provider does not support for example the Practitioner how would this be represented from an Operation Outcome perspective

Should the capability statement be used to indicate what a Provider supports in terms of parameters?

Also changes to the 1.5.0 spec potentially are needed - https://gpc-structured-1-5-0.netlify.app/access_documents_development_search_patient_documents.html#search-parameters states author filter applies to DocumentReference.author.
https://gpc-structured-1-5-0.netlify.app/access_documents_development_search_patient_documents.html#_include-parameters states that author may be a practitioner or organisation. 
However, error messages (https://gpc-structured-1-5-0.netlify.app/access_documents_development_search_patient_documents.html#error-handling) suggests only organisation should be supported.

**Comment by martinhillyard** [comment]
Change made via commits such as https://github.com/nhsconnect/gpconnect/commit/c4e3009e705605e83b229c18aff3f3cda3c094b1
Awaiting release
