### ISSUE TITLE
Retrieve a patients appointments - date range clarification

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#119]
appointments_use_case_retrieve_a_patients_appointments.html

Clarify what date range of appointments will be returned should the client not specify a date range. Will this be all past, present and future appointments?

Uplift with clarification

**Comment by michaelmeasures** [comment]
@briandiggle this relates to #114.

**Comment by briandiggle** [comment]
I have added the following  to provide clarity:

- Where only start date is specified, provider SHALL return all data items from this date
- Where only end date is specified, provider SHALL return all data items until this date
- Where no date period is specified in input parameters, provider systems SHOULD return all past, present and future appointments

NOTE that I have softened the requirement to SHOULD where no date range is supplier in view of our concerns over the potential volume of data in play in certain circumstances to give room to provider systems to take measures to protect their API infrastructure if they deem this necessary.
