### ISSUE TITLE
API Use case - Request and Response body examples

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#120]
Uplift API use case to include examples of request and response body for all use cases, where this is appropriate (i.e. no request body on GET)

appointments_use_case_search_for_free_slots.html
etc

**Comment by michaelmeasures** [comment]
@briandiggle the code examples to date have been generated from my c# implementation [here](https://github.com/michaelmeasures/gpconnect-reference) which you might want to take a look at.

**Comment by michaelmeasures** [comment]
The intention was to build on top of Furore Spark server but to be honest that's been a pain and I've still got a memory leak I can't track down under certain error conditions. Please consider it alpha quality!

**Comment by james-answer** [comment]
All the pages currently have valid request and response examples for the Appointment Management API Use Cases. No work needs doing for this.

**Comment by james-answer** [comment]
Sorry didn't notice the urls
