### ISSUE TITLE
API use cases - code snippits in java, .net, curl

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#121]
Uplift all API use cases with code snippits in java (hapi), .net (fhir-net-api) and optionally curl

https://nhsconnect.github.io/gpconnect/appointments_use_case_search_for_free_slots.html
etc

**Comment by michaelmeasures** [comment]
@briandiggle can we also add here that code examples should also be committed back to the corresponding git repo (i.e. gpconnect-dotnet-examples or gpconnect-java-examples).
