### ISSUE TITLE
Book an appointment - consecutive slots

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#122]
appointments_use_case_book_an_appointment.html

Should the provider or the consumer have responsibility for ensuring that an appointment does not include non-consecutive time slots? Should this be made explicit on the page?

What does a consecutive time slot mean exactly? I.e. end time of slot 1 is exactly start time of slot 2? What about one slot at end of day, next slot at start of next day - this would seem to be two bookings.

Clarify and uplift spec including the addition of an error example

**Comment by michaelmeasures** [comment]
@briandiggle in the vendor workshops we discussed being able to only book adjacent slots with-in the same schedule (i.e. two 15 minutes to make a 30 minute) and I believe the people involved where comfortable with this being handled/enforced by the provider system. Having thought about defining consecutive slots maybe this is something we should avoid as it may be better to leave this in the hands of each provider system rather than being strict (i.e. end time of one slot must be equal to the start time of the next slot) as I can see schedule/slot definitions and rules will be different across organisations and even potentially within an organisation.

**Comment by james-answer** [comment]
@michaelmeasures @briandiggle - The problem with not defining a specific criteria for what is considered an adjacent slot is that it makes front end development for a consumer difficult. If one system returns slots which are one minute apart and expects them to be adjacent but another system send slots a minute apart but does not consider them adjacent how would the front end know that those slots are adjacent or not until it returned an error is it was not allowed.

It would be easier for consumers systems and users of those systems if there was a consistent approach to adjacent slots (ie there is less chance of them getting errors when they are using it). If we specify that slots are only considered adjacent if they have the same end date on the first slot as the start date on the second slot. Development wise it should be easy for a provider to change the end date of the slots to meet the requirement as their system should be consistent with how slots are allocated.

**Comment by michaelmeasures** [comment]
@james-answer I totally agree with your position on it not being easy for consumers if we don't define what is considered an 'adjacent slot'. However, I don't believe we have full autonomy on this decision as each provider already has the ability to book multiple slots (via the IM1 mechanism) and it's not defined in the IM1 requirements what constitutes an 'adjacent slot'. I'm just wary of being to restrictive as it seems quite reasonable to me that people may allow a bit of time between adjacent slots to perform the associated admin work (i.e. 15 minute consultation followed by 5 minute gap to write up) but if you need a longer slot it's perfectly fine to book two consecutive slots, even though there is a gap.

**Comment by briandiggle** [comment]
Summary:
Overall guidance is that providers are responsible for the implementation of business rules that forbid the booking of non-adjacent slots according to their own practices.

To simplify consumer implementations, we need to enable consumers to book appointments with multiple adjacent slots with certainty and thus to be able to identify adjacent slots in a deterministic fashion. We should stipulate therefore indicate that adjacent slots are identified only as follows:

Where slot B is adjacent to slot A, start time of slot B equals end time of slot A.

**Comment by james-answer** [comment]
It would probably be advisable to add this information to both the "Search for free slots" and "Book an appointment" sections of the specification where the information will affect the returned or posted resources.
