### ISSUE TITLE
Book an appointment - detail on patient ID resolution

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#123]
appointments_use_case_book_an_appointment.html

Provide clarity on requirement to resolve patient NHS number to logical ID in advance of booking request body:

"actor": {
			"reference": "Patient/1",
			"display": "Mr. Mike Smith"
		},

**Comment by michaelmeasures** [comment]
@briandiggle a link back to the [Common API Guidance - Resource ID](https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#resource-id) page would be good to have here.

**Comment by james-answer** [comment]
Going to add a line to specify that a patient search should have been done to get patient logical id for use in the appointment.
