### ISSUE TITLE
Book an appointment - profile to be used

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#124]
appointments_use_case_book_an_appointment.html

Is the appointment resource to be posted expected to conform to the gpconnect-appointment-1 profile? Should we therefore, as well as a link to the standard DSTU2 appointment resource, also provide a link to this profile? Should this be https://fhir-test.nhs.uk/StructureDefinition/gpconnect-appointment-1 or http://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.GetScheduleQueryResponse/gpconnect-appointment-1.html

**Comment by michaelmeasures** [comment]
@briandiggle now that the publication landscape has stabilized I think it's worth looking at doing a pass across the Appointments capability pack ensuring deep linking into the DMS where profiles or valuesets are referenced.
