### ISSUE TITLE
Book a slot - limitation of number of slots to be booked

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#125]
appointments_use_case_book_an_appointment.html

Do we need to put limits on the amount of slots which can be booked by a consumer? To protect against block bookings, or bookings which are for long time periods? Should we simply state that the provider system is responsible for implementing any business logic required here?

**Comment by michaelmeasures** [comment]
@briandiggle worth putting through the decision log but think the second option of stating that the provider system is responsible is sensible. Note, we will need a test case and suitable error handling guidance for this one as well.

**Comment by briandiggle** [comment]
It is worth noting that the slots to be booked must be [consecutive](https://github.com/nhsconnect/gpconnect/issues/122).  Therefore a "block booking" could not be made across multiple schedules.

I would image that  provider systems would have logic in place already to protect against such "block bookings" being made from other contexts, and that business logic to be applied for gpconnect interactions would follow that.

**Comment by briandiggle** [comment]
Each appointment booking is associated with a patient record. Healthcare organisations for appropriate use of patient record information. Therefore local standard best-practice at consumers (booking organisation) can be assumed to be followed - consumers would be acting illegally if using a particular patient to make a block booking.

In addition, it is worth stating that provider systems are responsible to implement business rules to protect the responsible use of the booking API along the lines of those business rules already in place to prevent misuse outside of the GPConnect API implementation.

**Comment by jackiebarnes** [comment]
Getting Providers system rules around this w/c 4/9
