### ISSUE TITLE
Clinical scenarios - Business analysis

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#128]
The clnical scenarios, appointments_clinical_scenarios.html, coming out of workshops with suppliers, do not give clearly defined business scenarios which will be delivered at FoT and roadmap stages.

It would  be useful to flesh out the detail of the business requirements, align this with the appointments capability as it now standing, and present this to NHS England (Mike Smith?) for acceptance

**Comment by michaelmeasures** [comment]
@briandiggle I suggest we look at working up some user stories and BDD scenarios what lock-in the scope and can also be used for testing purposes.

**Comment by briandiggle** [comment]
Engagement with NHS England and the healthcare community to clarity and validate business scenarios is taking place.
