### ISSUE TITLE
Book/Amend/Cancel appointment - profile metadata on client post

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#129]
Require that clients include profile metadata on POST requests.

Also uplift guidance at development_fhir_api_guidance.html to this effect

**Comment by michaelmeasures** [comment]
#130 please see comment on why this is important.

**Comment by james-answer** [comment]
The API Use Case pages had already been updated with additional wording to indicate use of profile element so added additional guidance to common api guidance.
