### ISSUE TITLE
Amend appointment - resource must exist.

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#131]
Explicity state that if the resource does not exist, it will result in a error – it will not be created. Reference https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#create-resource

**Comment by michaelmeasures** [comment]
@briandiggle not sure what you mean by this one... do you mean no resource is provided in the request payload? or that a referenced resource isn't available? both of these would result in an error.

**Comment by briandiggle** [comment]
I had in mind that where the resource does not exist at the provider, to clarify that PUT cannot be used to create the resource in this scenario as the provider is responsible for defining the logical name of the resource.  ( http://stackoverflow.com/questions/630453/put-vs-post-in-rest)

**Comment by briandiggle** [comment]
Review API guidance on the use of HTTP verbs. Aggreement that PUT should not be used to create a resource.
