### ISSUE TITLE
Cancel appointment - provider responsibility

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#132]
Do we need guidance on the responsibility of the provider to deal with a cancellation according to their internal processes?

**Comment by michaelmeasures** [comment]
@briandiggle yes I think it's sensible that existing business rules are consistently enforced. For example, I know that in PFS land that there can be a GP practice configurable cut-off for online cancellation of appointments by the patient. However, it's important that no new restrictions are added for GP Connect that don't already exist as this would limit the usefulness of the APIs. I believe the IM1 requirements cover this business requirement by saying API access MUST behave inline with physical user access. @jackiebarnes  has been looking at getting the IM1 business requirements that also apply to GP Connect (IM2) up on GitHub,

**Comment by jackiebarnes** [comment]
GPSoC requirements state that the a) appointment status should be updated to reflect cancellation,   b) slot becomes available;    c) Appts Subsidiary Module - cancellation notification should be sent to the patient according to patient contact method preferences; - checking that this is part of the Providers system processes

**Comment by briandiggle** [comment]
Re a) and b), the specification for "Cancel an appointment" already covers this:

_A status response 200 OK implies that the state of any resources affected by the appointment cancellation (i.e. the associated Slot) subsequently reflects the cancellation (for example, Appointment.status, Slot.freeBusyType are updated inline with any internal integrity constraints)._

Re: c) This should be considered in the context that this GPSoC requirement is specifically for a Patient Facing services use case.
