### ISSUE TITLE
Register a patient - Design Decisions

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#133]
"To do: Details of how to Register a Patient will be provided in the Foundations capability pack in a future release."

This can be found at foundations_use_case_register_a_patient.html

**Comment by michaelmeasures** [comment]
@briandiggle I've now written a first cut of the API spec for the register a patient. However, their is a decision on the decision register to re-cut/strip back the DMS and API. Note, we also really need a Foundation DMS to be made as the register patient operation is currently living in the Appointment DMS (which isn't ideal) as we didn't have enough time to get a new DMS made at the time.

**Comment by michaelmeasures** [comment]
@rpugmire  As discussed internally we need to make it clear that the expectation is that the organisation and practitioner included in the response Bundle are the details as returned from PDS (inline with the practitioner and organisation behavior returned in the $gpc.getcarerecord response Bundle). Note, this may be an area we simply in a future uplift.

**Comment by briandiggle** [comment]
Updated appointments design to point at the register a patient API

Put not on Register a patient API to emphasise that this API is only to be used to create a temporary local registration to support federated appointments.
