### ISSUE TITLE
Design Decisions - federations

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#134]
Much of the appointment management capability is predicated on the concept of a "federation" of organisation which have already agreed to share data and appointments. 

This concept is implicit, but some of the scenarios given in "clinical scenrios" could be viewed as non regional business scenarios.

It would also be useful to indicate that the concept of the "federation" is defined in the spine as a combination of SDS setup (interactions and endpoints) and SSP (data sharing aggrements). The correct set up a federation in the spine is a prerequisite to appointments capability usage

**Comment by michaelmeasures** [comment]
#137 is related to this issue.

**Comment by james-answer** [comment]
Fixed by fix for #137 so closing.
