### ISSUE TITLE
Clinical Scenarios - Emphasis federation concept for FoT

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#137]
"As a Clinician, providing care for a patient, I want to see all appointments that are already booked or scheduled for my patient with any other health, social or mental health care organization so that I have a full picture of the care that is planned for my patient."

This suggest a non-regional scenario. Do we need to introduce the concept of a federation and emphasise that this is discrete set of organisations who have agreed to share data and appointments, and have been set up accordingly in SDS and SSP?

**Comment by michaelmeasures** [comment]
@briandiggle yes we need to call out more explicitly how the federated scenarios are to be met. We should add a design decision which makes it clear that neither the SSP nor Provider system is expected to aggregate all appointments across other health, social or mental health care organisations. The responsibility for being aware of the organisational federation and aggregating on that is to be handled by the consumer systems (if at all).

**Comment by briandiggle** [comment]
Related to HDL-169 - the following decision has been made:

The GP Connect specification glossary describes a federation as follows:
"For the purposes of federation of appointment bookings through the Appointments API, the “federation” is simply considered to the list of the organisations which are members of the federation, for example as a list of ODS codes".
The Appointment Management Capability places responsibility for definition and discovery of this "federation" with the consuming system. I.e. the consuming system is responsible for defining and maintaining this list of organisations forming the federation in the context of which the consuming system runs.

Update https://nhsconnect.github.io/gpconnect/appointments_design.html
