### ISSUE TITLE
Clinical Scenarios - current appointment?

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#138]
"A Patient would like to view their current/future appointments so that they can manage their time appropriately, they can access Patient Facing Services online and view their booked appointments with any care organization"

What do we mean by "current" appointment? Is this an appointment which is scheduled for now? If not, how is this different from "future" appointments?

**Comment by michaelmeasures** [comment]
@briandiggle yes current means any appointment that is currently underway. It's marked as a roadmap item so not in scope anyway. Hence, I'd consider leaving it for the PFS team to determine what they want/need around this.

**Comment by briandiggle** [comment]
The "Read a patient's appointments" API enables the retrieval of a patients appointment by start and end datetime. Therefore a consumer is able to use the API capability to provide whatever time view is required.

No change is required to the specification therefore.
