### ISSUE TITLE
Cancel an appointment - slot references

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#140]
"To do: Decide if when cancelling an appointment we should remove all references to the original slot resources."

**Comment by james-answer** [comment]
When an appointment is cancelled its contents is changed to indicate that the appoinment is cancelled, the references to slots should not really be removed as they just indicate that there was a link to those slots for the appointment. If the slot references are removed then a lot of the information about the appointment is lost such as which schedule this appointment was booked against and posibly which practitioner this was booked against.

The reference is fine to be left as the slot resource contains a free/busy field which indicates if the slot can be used for another appointment so there is no benefit of removing the slots from the appointment resource.

**Comment by james-answer** [comment]
There is no reason to remove the slot references from a fhir perspective and data will be lost if the references are removed. The spec also says that the provider "SHALL return an Appointment resource that conform to the gpconnect-appointment-1 profile.", in the profile the cardinality of the slot reference is 1..* so there must be a slot reference.

Closing this ticket as will not change.
