### ISSUE TITLE
API use cases - consumer prerequisites

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#141]
Some, but not all API use cases have the following

"The Consumer system:

SHALL have previously resolved the organisation’s FHIR instance using an ODS Code, ODS Site Code or other organisational business identifier."

Should this be present in all API use cases (or at least the GET use cases), and should the text be change to "SHALL have previously resolved the organisations FHIR endpoint base URL according the the guidance provided in [link to spine integration guidance]"

Also should all API use cases which require patient information include:
"SHALL have previously traced the patient’s NHS Number using PDS or an equivalent service."

**Comment by michaelmeasures** [comment]
@briandiggle happy to standardize and provide consistent consumer guidance across all API use cases. Note, the reason I didn't mandate the mechanism is that other use cases (such as Urgent Care / 111) will likely not use ODS Codes and the SDS LDAP model. However, I'm happy to tighten up the wording as proposed and we'll deal with the Urgent Care use cases when we uplift specifically for that clinical scenario.
