### ISSUE TITLE
GPConnect-Appointment-1 still appears under Get Schedule Query Response

### ISSUE THREAD

**Issue by Chrisjobling** [nhsconnect/gpconnect#142]
GPConnect-Appointment-1 appears in the list of response objects for get schedule. I am under the impression get schedule no longer returns the list of objects documented, so this should be changed.

Get Schedule Query Response location : http://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Chapter.5.Constrained%20FHIR%20Models/index.html

**Comment by james-answer** [comment]
The get schedule operation should not return the following resources:
* Patient
* Appointment

The response bundle specific profile does not include these:

http://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.GetScheduleQueryResponse/gpconnect-getschedule-bundle-1.html

but the "Get Schedule Query Response" page does appear to be missleading by including them. There should probably just be links to foundation profiles.

http://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.GetScheduleQueryResponse/Profile.GetScheduleQueryResponse.html

**Comment by michaelmeasures** [comment]
@james-answer it's my recollection that in the vendor workshops we decided that creating a full administrator calendar view (as could be seen in Outlook) is out of scope. Hence, why this call has gone from including both free and busy slots (plus their associated Appointment and Patient details) to just returning free slots. Hence, the change in scope. Note, the DMS will also need updating to make it clear that the operation now only returns free slot details (and not all the detail of the schedule).

**Comment by james-answer** [comment]
@michaelmeasures Do you mean that the getSchedule operation response should not contain the Schedule, Practitioner, Location and Organization resource, just return the free slots?

I assume I have just miss understood you comment and it should contain the relavant reference details from within the returned slot resources, such as schedulle and the referenced practitioner and location from the schedule should also be included.

**Comment by michaelmeasures** [comment]
@james-answer apologies I've updated my comment... It was my intention to give the rational for why what you've proposed is correct (i.e. remove Patient and Appointment) everything else should stay as is.

**Comment by james-answer** [comment]
This will no longer be an issue once we move from using the DMS Capability packs to using the FHIR Reference server. The updates to the specification are underway along with the deployment of the new fhir profiles so this will not be an issue in the next release of the specification. The specification is clear around the expected response for a gpc.getschedule operation. For these reasons I am going to close this issue.
