### ISSUE TITLE
Find a practitioner - clarity on search parameter

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#145]
https://nhsconnect.github.io/gpconnect/foundations_use_case_find_a_practitioner.html#request-operation

When searching for a practitioner the spec implies but is not completely clear if the only allowed search parameter system is "http://fhir.nhs.net/Id/sds-user-id" the spec should be updated to make it clear and if others are allowed this should probably be stated more clearly?

Whatever the outcome of this decision we will need to update the test suite to include the appropriate identifier parameters and check for other parameters. If other parameters are allowed should the allowed parameter systems be reflected in the conformance profile so a consumer system knows which identifiers it can use to search?

**Comment by michaelmeasures** [comment]
@james-answer Given we don't have a hard requirement to allow other search parameter systems at this stage. I'd say lets tighten up the working to make it clear that consumers can only reliably search by sds-user-id.

Note, I don't think you can stipulate in a FHIR server's conformance profile that identifier search only takes certain systems (but I could be wrong).

**Comment by james-answer** [comment]
Looking at the specification for the different search capbilities ("Find a practitioner", "Find a patient", "Find an organisation", "Find a location"), the format is identical for all capabilities so it seems more logical to clarify that we can only guarentee the capability for specific identifier types (as per MM comment).
