### ISSUE TITLE
Move the gpconnect demonstrator across to the nhsconnect organisation account

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#146]
Currently the GP Connect demonstrator is living inside the nhs-digital organisation on GitHub separate from the other 4 gpconnect repositories. It should be moved across into the nhsconnect organisation so that everything is easy to find and lives in the same place. Note, doing this will mean that the configuration of the automated deployments will likely have to change as the repository location will change (breaking the current Jenkins builds and AWS deployment).

**Comment by james-answer** [comment]
We will need to update the github page to point to the new location.

**Comment by jonnyry** [comment]
Moved.
