### ISSUE TITLE
Establish if the Appointment Extensions can be meaningfully populated

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#147]
We need to determine if the appointment extensions (i.e. category, booking method, contact method) can be meaningfully populated by the providers. If they cannot then the impact on the deliverable use cases needs to be established. Any that can't be supported should be removed from the profile or extra guidance given as to what a consumer can actually expect to receive.

**Comment by briandiggle** [comment]
Are you referring mainly to "Retrieve a patients appointments" - the ability to populate these extension fields will depend on whether equivalent data fields are stored in provider systems.

What about create a booking? The booking method extension has only one valid value from the valueset (http://fhir.nhs.net/ValueSet/gpconnect-appointment-booking-method-1) for consumers to use- "Online". Should providers error if any other type is found on a create booking request?

**Comment by james-answer** [comment]
I think the booking method is an example of one which could be used but needs guidance from a consumer perspective. For example if someone rings a GP Practice to make a booking the mothod might be "telephone", if the person has come a GP Practice the receptionist might be booking an appointment at a federated practice which would mean that the booking method should be "In Person".

I agree that contact method and appoitment category extensions might not actually be needed.

We probably also need to specifically state if the cancellation reason extension can be included in the book appointment as currently there is nothing (appart from common sense) to say that you should not include a cancellation reason extension extension when you create a new appointment.

**Comment by james-answer** [comment]
I am looking at writing tests for the appointment resource extensions, it is not clear what is mandatory or not within the extension. Could an appointment have an extension with just a display element and no code element? This needs to come out of discussions about the use of the extensions within appointments.

**Comment by jackiebarnes** [comment]
Including question in Provider Profile review session 7/9

**Comment by jackiebarnes** [comment]
Value sets:
Appt Category,
CLI - Clinical/ ADM - Administrative/ VIR - Virtual/ REM - Reminder/ MSG - 
 Booking Method, Contact Method
ONL - Online/ PER - In Person/ TEL - Telephone/ EMA - Email LET - Letter
Value for Booking Method - what should consumer send:  "On-line"

**Comment by jonnyry** [comment]
Suppliers have indicated limited ability to populate these extensions meaningfully.  Some of these are recorded using locally configurable values in slot and session type.

Also the current valuesets bound to these extensions need rework.

Decision for Appointments RC1 is to remove all three extensions.

During subsequent phases of the GP Connect  implementation we will continue to monitor the requirements for these fields - and consider ways in which suppliers could be able to populate them consistently and meaningfully.

**Comment by james-answer** [comment]
Need to updated the spec so re-opening issue.

**Comment by briandiggle** [comment]
The following decision has been made today:

"Remove these extensions for RC1 given the lack of current use cases for the values and lack of meaningful mapping from Provider systems; will be monitored in FOT deployments and can be added back in without breaking change, if a standardised approach evolves or new use cases arise"

**Comment by james-answer** [comment]
No update required as these fields are not mentioned in the spec, data standards have updated the profiles to remove these extensions, therefore no additional changes needed so closing this issue.
