### ISSUE TITLE
Provider extra guidance around Identifier handling on Appointments, Schedule and Slots.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#149]
Currently we have business identifiers in the profiles but we've not specified how these can be utilised by consumer systems.

**Comment by briandiggle** [comment]
Could you give an example to flesh this out?

**Comment by briandiggle** [comment]
Currently we do not mandate business identifiers for these resources -  there is a 0..1 cardinality.

We also do not support searching for business identifiers on this resource.

Decision is to wait for a clear business need to emerge for more capability on business identifiers for these resources, and add API capability is this is a confirmed strategic need

**Comment by briandiggle** [comment]
Closed with above decision
