### ISSUE TITLE
Provider extra guidance around Status usage.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#150]
Need to make it clear that:

- 'pending' can't currently be used.
- 'arrived | fulfilled | cancelled | noshow' should be made available if technically possible.

**Comment by briandiggle** [comment]
Requires business elaboration

**Comment by jackiebarnes** [comment]
Seeking to elaborate in Supplier profile review sessions 7/9

**Comment by jackiebarnes** [comment]
Providers can map statuses to the value set;  github spec does not need updating
