### ISSUE TITLE
Appointment Amend - Which fields can be updated

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#152]
On the following page:

https://nhsconnect.github.io/gpconnect/appointments_use_case_amend_an_appointment.html

In sections "Use Case", point 3 says that you can update the "description" and/or "comment", but on the same page under section "Payload Request Body" it says that only the "reason" can be updated.

Which of the following fields should be allowed to be updated:
* description
* comment
* reason

From the uses of the fields it would make sense to allow all the three fields to be updated, only allowing the "reason" to be updated would probably not meet many real world use cases.

**Comment by briandiggle** [comment]
I would imagine it would be a good idea to keep the original description intact, and possibly also the comment - i.e. the original booked appointment entity has a state change only from booked to cancelled. The reason attribute can be used to specify a reason why the booking was cancelled. Therefore I would say that the use case 3 text is erroneous.

It would be good to get some BA input on this - perhaps @jackiebarnes has a view?

**Comment by james-answer** [comment]
This only applies to the Amend, I would only expect the cancellation reason extension to be changed for a cancellation. For an Amend, the "reason.text" field only contains "Plain text representation of the concept", if you are amending an appointment you probably want to change the description or comment as they might be wrong or you might want to add more details which is why it would make more sense to allow all the fields to be updated.

**Comment by briandiggle** [comment]
Sorry - I had "cancel" in my head.

It does seem appropriate to allow updating of description/comment.

**Comment by james-answer** [comment]
The other thing we should make a decision on is if an appointment has been cancelled should it still be allowed to be amended? If so should the same fields be amended or should the cancellation reason be the only field that can be amended?

In the demonstrator when we came across this scenario we only allowed amendment of the cancellation reason once an appointment had been cancelled. Before the appointment was cancelled we only allowed amendment of the comment and description.

**Comment by adamjlees** [comment]
Once cancelled the booking is gone, and the slot is freed for another booking, so there's no valid reason for amending other fields.  I'd say cancellation reason is the only field that should be amended post cancellation.

**Comment by adamjlees** [comment]
Sorry didn't mean to close; clicked on wrong button.

**Comment by rbutterf** [comment]
It also states in the Use Case

The typical flow to cancel an appointment is:

**Comment by briandiggle** [comment]
@rbutterf  The "The typical flow to cancel an appointment is:" appears to be a cut/paste from the Cancel Appointment API spec - I will raise this as a separate issue so we don't lose sight of it.

**Comment by briandiggle** [comment]
Needs BA elaboration

**Comment by devmikey** [comment]
The purpose is to amend the reason for the appointment. 

The comment and description relate to details about the slot and would be predetermined by who ever is setting up the scheduled.

Should only allow reason to be amended.

**Comment by james-answer** [comment]
The "reason" element is described as the "Reason this appointment is scheduled" but the element is a CodableConcept with a value from the value set "http://hl7.org/fhir/DSTU2/valueset-encounter-reason.html", so will not be used to describe or elaborate on the exact patient problem.

If you were amending an appointment you may want to change the "reason" code but you would probably also want to amend the "description" or the "comment" which will include additional information about the patients problem.

Reason - Reason this appointment is scheduled (CodableConcept Field)
Comment - Additional comments (Free Text Field)
Description - Shown on a subject line in a meeting request, or appointment list (Free Text Field)

We should really allow the "reason", "comment" and "description" elements to be amended.

**Comment by lasm1** [comment]
@james-answer @jackiebarnes Within EMIS GP systems they only have a reason field. From here they can pick from a drop down list but also add free text (and add options to the drop down). This is the only field that can be edited, if anything else is to change then the appointment would need to be cancelled and rebooked. 
Would it be a question as to whether the 'reason' field maps to 'reason' or 'comment'?

**Comment by jackiebarnes** [comment]
Agree with James that all three fields - reason, desc, comments should be amendable but presumably for future appointments, ie not amending appointments which have been attended or are 'current', ie have started but not completed/updated by Practitioner?  include in questions to Suppliers - how their systems deal with appointment info amendment

**Comment by jackiebarnes** [comment]
My view having read the above is agreement with James that Reason, Comment and Description elements should be amendable;  will pose question explicitly to providers as to what fields they will populate to store these 3 elements

**Comment by jackiebarnes** [comment]
Would seem that the text appointment fields are amended by practices even for historic appointments to add further bits of info not available at time of booking;  

for info - 
Mtest - only supports Reason text
Vision -  'Reason' text equivalent would be captured in their Appts Comments field
EMIS - populates all

**Comment by james-answer** [comment]
Decision made: On amend appointment if not cancelled comment, description and reason can be updated. If cancelled appointment the comment, description, reason and cancellation reason can be updated. Need to update spec, test suite and demonstrator.
