### ISSUE TITLE
Is the aud claim in JWT valid?

### ISSUE THREAD

**Issue by Dunmail** [nhsconnect/gpconnect#154]
https://github.com/nhsconnect/gpconnect/blob/develop/pages/integration/integration_cross_organisation_audit_and_provenance.md

The specification proposes using a fixed value for the aud claim of https://authorize.fhir.nhs.net/token (Authorization server’s token_URL) but the RFC requires that any principal processing the JWT must reject the claim if it isn't in the audience (see https://tools.ietf.org/html/rfc7519#page-9). The 'Authorization Server' doesn't appear on the 'Integrate With Spine/System Topologies' page, but (based on the name) doesn't seem like a likely name for a FHIR end-point.

**Comment by briandiggle** [comment]
1. Normally the aud claim would identify the _audience_ for the token. I.e. you would expect the URI of the protected resource here - the FHIR Server Root URL for the organisation as returned from an endpoint lookup.

2. Also, the fixed value indicates the presence of a central NHS OAuth authorization endpoint, which does not at present exist.

**Comment by adamjlees** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/fd53757ef154bad3f04342173cf1d9d2648bcde1
