### ISSUE TITLE
Find a Practitioner - Use cases for appointments and tasks

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#156]
The "find a practitioner" foundation end point has been included in the foundation endpoints which need to be implemented to enable Appointments or Tasks capability.

It is not clear to me what use case would require the use of this API call to facilitate one of the Appointments and Tasks use cases. 
E.g Appointments - $gpc.getschedule returns logical identifier of practitioner associated with free slots.
    Tasks - As this is now Organisation to Organisation there is no need for a practitioner SDS-ID to be resolved to a logical ID at an organisation.

**Comment by michaelmeasures** [comment]
@briandiggle agree that now that the Task is purely Org to Org that the direct need for this call has diminished. However, given it has already been factored into the suppliers delivery timelines and costings I have elected to leave it in scope as it rounds-out/completes the Foundations pack and will enable future (practitioner dependent) stages to be delivered more expediently.

**Comment by briandiggle** [comment]
As there is no current use case which requires a lookup of SDS User Id to resolve a logical practitioner resource ID at a logical practice FHIR server, this API use case will be removed from Foundations1.0.00.rc.1

**Comment by james-answer** [comment]
It was agreed that this should be left in as part of foundation issues so we are leaving find practitioner in as an API Use Case, therefore closing.
