### ISSUE TITLE
Find a practitioner - Search use cases

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#157]
This API call is very constrained to the point where it is effectively "Resolve a Practitioner SDS user ID to logical identifier"

It would be good to understand what use cases require this call? It would seem more evident to expose a use case to find practitioners by SDS role profile ID. Should this be included?

**Comment by briandiggle** [comment]
Business analysis required to understand potential need for consumer applications to search by a "SDS role profile ID" system,  or other parameters.

Moving to RC1 milestone  - can be closed if nothing arises out of engagement at this stage with consuming organisations to indicate need for this.

**Comment by james-answer** [comment]
Provisional decision made to remove "Find Practitioner" from the spec. As agreed by most people of decision log so seeking agreement from other TA's.

**Comment by james-answer** [comment]
Decision has been agreed to remove "Find Practitioner" from the specification and requirements for RC.1

**Comment by james-answer** [comment]
Decision has been changed and Find Practitioner is going to be left in. No Changes.
