### ISSUE TITLE
Search for free slots - no free slots available

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#158]
Where the $gpc.getschedule request does not result in any free slots returned, the following specification line at https://nhsconnect.github.io/gpconnect/appointments_use_case_search_for_free_slots.html needs clarifying:

"SHALL include the Schedule, Slot, Practitioner, Organization and Location details for the retrieved schedule(s) in a searchset Bundle."

Should we add clarity to state what the expected behaviour is in this instance so that consumers have clarity. It would seem sensible to include guidance that no other resources are returned when no slots are returned? Would these resources be considered spurious given the lack of slots? 
Would a consumer simple indicate "no free slots", or would the consumer wish to display a schedule with no slots available for booking?

**Comment by Dunmail** [comment]
Suggest behaviour is consistent with the FHIR search param `_include=*`, _i.e._ referenced resources are returned, with recursion as above.

**Comment by michaelmeasures** [comment]
Agree that when there are no free Slots then no other data can be/should be returned. 

I'm less convinced aligning with full recursion to be consistent with  `_include=*` is the way to go; as this could potentially spider through the system and pull in _lots_ of referenced data, as it is unbounded and will go to any depth.

As the FHIR standard itself says:

> It is at the server's discretion how deep to recursively evaluate the inclusions. Servers are expected to limit the number of iterations done to an appropriate level and are not obliged to honor requests to include additional resources in the search results.

I'd suggest we just make it explicit in our guidance which references are expected to automatically included (and which are not) to make it crystal clear what behavior we're expecting (and will be testing for in our automated test harness).

**Comment by Dunmail** [comment]
Agree that expected level of recursion can be defined within implementation guidance
