### ISSUE TITLE
Search for free slots - resource profile metadata

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#159]
The example response XML does not include profile metadata for any of the resources returned despite the fact that all contained resources have gp connect profiles. 

Add profile in <meta> section for each resource to ensure example complies with advice elsewhere on the spec at https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#resource-metadata

**Comment by michaelmeasures** [comment]
@briandiggle just been looking over the Appointment response example XML in the GitHub pack and they do have the resource metadata populated, including the profile details. However, I did notice that the request XML payload for "Book an Appointment" is missing the profile details. Just wondering if you've noticed the problem elsewhere?

**Comment by briandiggle** [comment]
I'm referring to https://nhsconnect.github.io/gpconnect/appointments_use_case_search_for_free_slots.html#payload-response-body

E.g. the contained resource Organisation/1 has the following meta (without profile):

"meta": {
				"versionId": "1469444400000",
				"lastUpdated": "2016-07-25T12:00:00.000+01:00"
}
