### ISSUE TITLE
Missing error codes

### ISSUE THREAD

**Issue by chrisbloe** [nhsconnect/gpconnect#160]
The [Identity Validation Errors](https://nhsconnect.github.io/gpconnect/development_fhir_error_handling_guidance.html#identity-validation-errors) section of the Error Handling page is missing two entries:

APPOINTMENT_NOT_FOUND
LOCATION_NOT_FOUND

**Comment by michaelmeasures** [comment]
@chrisbloe it wasn't my intention to add XYZ_NOT_FOUND error codes for every resource that we're going to be using as this is in my opinion unnecessary. I've only added them when we're using a business identifier inside a custom operation (so for Patient and Organisation) and then for Practitioner as that's part of our Foundation pack. It was my intention to stop there and to use the more generic REFERENCE_NOT_FOUND error code if you try and create an Appointment for a Slot reference that no longer exists. You can then use the 'location' fields on the OperationOutcome to say which field caused the error. Did you have specific automated test cases in mind for using these errors?

**Comment by michaelmeasures** [comment]
@chrisbloe would be good to understand you're thinking a little more but if we can handle sensibly without adding more error codes then I'd be pro closing this issue as invalid/wont fix.

**Comment by michaelmeasures** [comment]
Talked to @chrisbloe and he's happy that this can be closed as won't fix.
