### ISSUE TITLE
Schedule Profile Practitioner reference extension

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#161]
In the schedule DMS the practitioner extension has a cardinality of 0..*

https://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.GetScheduleQueryResponse/gpconnect-schedule-1.html

This needs to be 1..* as when you have performed a getScheduleOperation and you want to book an appointment you need a practitioner reference to use in the appointment as it is mandatory, as per the page linked blow:

https://nhsconnect.github.io/gpconnect/appointments_use_case_book_an_appointment.html

If the cardinality is 0..* it is possible there is no practitioner included in the response to the getSchedule and this would stop the consumer creating an appointment as they would not have all the mandatory fields required for creating an appointment.

**Comment by michaelmeasures** [comment]
@james-answer i've made this a decision as it's possible we could make the book appointment requirement softer (i.e. you only need a patient/subject and not a practitioner to book an appointment). I guess this could be useful if you know a clinic is running on a future date but you're not sure yet who will be the actual practitioner.

**Comment by james-answer** [comment]
Agreed, this might be a better solution.

**Comment by briandiggle** [comment]
I find the wording of responses above to be a little ambiguous - Is the decision to soften the book appointment requirements to allow the specification of a practitioner to be optional?

**Comment by briandiggle** [comment]
This relates to the profile  [gpconnect-appointment-1](https://www.simplifier.net/GPConnect/gpconnect-appointment-1/rendered).  Currently participant is cardinality 1..*, however the [book appointment API](https://nhsconnect.github.io/gpconnect/appointments_use_case_book_an_appointment.html#payload-request-body) spec indicates that both the patient and primary practitioner must be present.

These areas need to be brought into alignment.

**Comment by james-answer** [comment]
To clarify the comments above, I think the generally agreed position is to soften the requirement for a practitioner reference to be included as this would allow a greater number of possible use cases to be satisfied.

**Comment by james-answer** [comment]
Decision: The decision has been made to make the Practitioner optional in both the schedule and the appointment resource profiles.

Change required:
**Profiles** -  No change required as both the Schedule resource practitioner extension and the Appointment resource participant are optional so the profiles already allow for the solution.

**Spec Updates** - The following specification page needs updating to remove the Practitioner as a mandatory participant within the appointment resource: "https://nhsconnect.github.io/gpconnect/appointments_use_case_book_an_appointment.html#payload-request-body"
