### ISSUE TITLE
Default Date Range Banner Message Wording

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#162]
Change from:
"All relevant  items subject to ......

To:
"All relevant items"

as where there are items excluded, there will also be the  Excluded Items Section Banner message;  unnecessary duplication, and caused confusion

**Comment by tim1ford** [comment]
Updated in 0.7.0 to:

#### Default date ranges ####

Where the consumer system has not supplied a date range, then where applicable and while the default is for ALL items to be provided, the following message **SHALL** be supplied by the provider and displayed by the consumer system beneath the section header.

```html
<div>
	<p>All relevant items</p>
</div>
```
