### ISSUE TITLE
Investigations Section - Op Outcome Message

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#164]
Change Design Decision and HTML Impl Guidance pages to align spec for Investigations section to PAT etc - ie for providers to return an Op Outcome Error Message

**Comment by jackiebarnes** [comment]
Entry in table on Impl Guidance page needs to be removed - GPConnect 0.5.1 patch release

**Comment by tim1ford** [comment]
Entry removed in 0.5.1
