### ISSUE TITLE
Uplift Topologies page to clarify

### ISSUE THREAD

**Issue by adamjlees** [nhsconnect/gpconnect#167]
https://nhsconnect.github.io/gpconnect/integration_system_topologies.html

-	Add a description of Party Key. 
-	Make clear these are mixed physical/logical diagram i.e. the yellow boxes are logical components, all other boxes represent physical components/functions.

**Comment by michaelmeasures** [comment]
@adamjlees would be good to also describe how the registration of these topologies into SDS looks like (and what is and isn't supported in SDS).

**Comment by adamjlees** [comment]
Simplified the diagrams for the TOM, need to incorporate these and update the existing ones on this page.

**Comment by adamjlees** [comment]
Revised page and diagrams in feature branch [/feature/topologies](https://github.com/nhsconnect/gpconnect/tree/feature/topologies)

https://github.com/nhsconnect/gpconnect/commit/ae63f2af89aed71b8104f1033a413f8bf71dc27d

**Comment by jonnyry** [comment]
Merged into develop on https://github.com/nhsconnect/gpconnect/commit/708af0326a8eb89fd5e229e1299ac3487a018c94

**Comment by jonnyry** [comment]
Closing feature branch and issue.

**Comment by jonnyry** [comment]
Also merge into 1.1.1.

**Comment by jonnyry** [comment]
Also merge into 0.5.1.

Now complete.
