### ISSUE TITLE
Register a patient clarification

### ISSUE THREAD

**Issue by Chrisjobling** [nhsconnect/gpconnect#168]
The questions are relating to the documentation located : https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html#payload-response-body

1. When a patient is registered to an organisation, the documentation specifies the response body “SHALL include the Patient, Practitioner and Organisation details for the nwely registered patient record in a searchset Bundle”. What are the practitioner and organisation resources to be returned and where are they acquired from? It is unclear if this is the practitioner who registers the patient or a practitioner who has an appointment with the patient being registered within the organisation practice or a practitioner at another practice?

2. Are the returned details in the response for the patient, practitioner and organisation references to the resource or a set of details which conform to the GPConnect-Register-Patient-1, GPConnect-Practitioner-1 and GPConnect-Organization-1 specification? The example response body only includes the patient which is not a reference. Is this the case for practitioner and organisation?

**Comment by michaelmeasures** [comment]
@Chrisjobling please see #133 for the answer to point 1 (they're the details pulled in from PDS). On point 2 the Bundle will contain the GPConnect profiled resources to be consistent with the behaviour for the $gpc.getcarerecord behavior. This behavior is under review (there is a ticket on the decision log) to consider if we simplify this call further and only return the patient details (which I'm beginning to think is a more sensible approach). Basically, keeping the Register Patient custom operation as lean and focused as possible.

**Comment by michaelmeasures** [comment]
@Chrisjobling closing this as a duplicate as this is covered on other tickets.
