### ISSUE TITLE
What can change in an Appointment between create and the returned resource

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#169]
The question has been raised about what fields sent in an appointment create the consumer can expect to be the same in the returned resource.

For example the consumer has to create an Appointment with the status "booked" but the provider system could change this to "pending" for the returned resource. So when the consumer looks at the returned resource for the create the appointment then the fields would be different. The question is what fields should not change, what can we validate in the test suite agains and what fields should the consumer be aware of that could change from what they sumbitted on the create.

As a starting point I think the following fields should not change as they are core to the appointment:

* Description
* Start
* End
* Comment
* Participant - Patient reference
* Participant - Practitioner reference (Only on returned (created) resource, on later reads this may have changed)
* Participant - Location reference (Only on returned (created) resource, on later reads this may have changed)

**Comment by michaelmeasures** [comment]
@james-answer i would say there is an argument that any details inherited from the slot/schedule shouldn't need to be posted up again (i.e. participant and location). However, i would argue that allowing the start and end date/times to be submitted is useful as they can then be used to ensure/cross-check at the provider end that you're actually booking against the correct slot(s). Potentially one for the decision log.

**Comment by james-answer** [comment]
Within the book appointment part of the specification it says "SHALL maintain resource state in accordance with their own internal integrity constraints, including the state of any associated resources, such as Slots, Schedules, etc.". It makes logical sense that a provider may wish to update some of the appointment to align with their internal appointment booking system as long as it does not affect the meaning of the appointment which can be checked during testing. Some things like start and end date can not change as this would affect the meaning of the appointment, this can also be covered by testing.

Based on this we should leave the spec as it is, the spec contains enough information to highlight this design principal so no spec change needs to be made.
