### ISSUE TITLE
Appointment participant - Location Reference

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#170]
There is a problem with finding the location of an appointment if the Location reference is not included in the Appointment as a participant.

The problem is that, if no location reference is included in the appointment resource the only link to location would be through the slot resource,

`Slot (contains reference to Schedule) -> Schedule (Contains reference to Location) -> Location`

The problem is that there is no "Slot Read" endpoint so there is no way to get the schedule for the slot and there for no way to get the location for the appointment from just the slot reference within the appointment.

There is two possible solutions to the problem of finding the location of an appointment:

1. Create a "Slot Read" endpoint to allow the consumer to find the schedule and then the location fo the appointment.
2. Make the Location Reference a manadatory participant in the Appointment resource so that the location can be found from the appointment alone.

Option 2 would reduce additional development effort as no new endpoint would have to be create. The only other problem with not having a "Slot Read" endpoint is that you can not find the schedule that the Appointment is booked against as there is no reference within the appointment.

**Comment by michaelmeasures** [comment]
@briandiggle also worth getting @jackiebarnes to think about the use cases for returning the Location details so we know what the requirements actually are from the business perspective. Also, we could consider not introducing the Slot Read or Schedule Read at all but instead allowing a the "_include" mechanism to be used for the standard location, practitioner and patient search parameters.

**Comment by briandiggle** [comment]
Decision to go with:
Make the Location Reference a manadatory participant in the Appointment resource so that the location can be found from the appointment alone.

**Comment by briandiggle** [comment]
Change required to gpconnect-appointment-1 profile
https://simplifier.net/GPConnect/gpconnect-appointment-1

**Comment by james-answer** [comment]
I am not sure we can make specific participants mandatory within the appointment profile (ie Patient and Location participants), so we will have to just specify it within the "https://nhsconnect.github.io/gpconnect/appointments_use_case_book_an_appointment.html" as a mandatory element with in the request body so that we can test against it and get the providers to include both references.

We could update the cardinality of the participants element to be 2..* indicate that the Patient and Location are mandatory but that will potentially cause problems with edge cases or future development so I would suggest just adding the requiremnet to the specification and leaving the profile with a cardinality of 1..* so there is less chance we will need to update the profile again later on.

**Comment by briandiggle** [comment]
According to https://www.hl7.org/fhir/DSTU2/profiling.html#cardinality a cardinality of 2..* would not be a valid use of profiling.

Re-opened  - will close when spec updates arising from this have been done.

**Comment by james-answer** [comment]
Descision made to make location mandatory to bring inline with profiles and to satisfy interaction flow.
