### ISSUE TITLE
Appointment Profile - Participant constraints

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#171]
There is a constraint on the participants forming part of the [gpconnect-appointment-1](https://www.simplifier.net/GPConnect/gpconnect-appointment-1/rendered ) profiled resources that states that "Either the type or actor on the participant MUST be specified"

This is not shown in the DMS. Would be useful to add a statment to the Book Appointments API spec to indicate this.

Also, would it be good to augment this constraint to require where the participant is a patient,  that a patient resource reference be present, rather than potentially just a type element?

**Comment by michaelmeasures** [comment]
@briandiggle the constraint is from the base FHIR standard and I think we need a deeper review of the usage of values in the [encounter-participant-type](http://hl7.org/fhir/DSTU2/valueset-encounter-participant-type.html#expansion) value set. As this impacts potential use-cases such as when a translator or emergency contact is needed or referrer is available etc. Note, I expect 95% of these won't be actually used by the GP CIS systems (and maybe non at all).

**Comment by briandiggle** [comment]
Additionally, the following should be considered (previously) 
The gpconnect-appointment-1 profile has the following constraint on the participant element:
"Either the type or actor on the participant MUST be specified"

My assumption is that this constraint allows the following:
Type only present
Actor only present
Type AND Actor present

It would be helpful to state this more clearly

**Comment by briandiggle** [comment]
Decision is that where there is a participant element, actor MUST be present, type is optional
