### ISSUE TITLE
Book appointment -Business Identifier clarification

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#173]
[Book appointment API spec response body](https://nhsconnect.github.io/gpconnect/appointments_use_case_book_an_appointment.html#payload-response-body) includes the following statement:

"MAY generate a business identifier to allow an individual appointment (i.e. Appointment resource) to be uniquely identifiable."
This has some ambiguity around namespace the identifier is unique within. Better to refer to standard FHIR guidance around business identifiers at https://hl7.org/fhir/DSTU2/resource.html#identifiers

**Comment by michaelmeasures** [comment]
@briandiggle the identifier would only be unique (at best) with-in a single principal system (i.e. EMIS, TPP, Vision, MT) however it's also possible it could only be unique with-in the scope of the logical system (i.e. GP Practice A with ODS code 1234). The FHIR standard wouldn't really have anything to say on this and it's really a design decision for each vendor. Note, as it stands non of the vendors have actually indicated they will be supporting the assignment of business identifier.

**Comment by michaelmeasures** [comment]
@briandiggle also it's important to say that the neither the FHIR standard nor DMS have anything to say about if the business identifiers can be assigned by the consumer , or should be assigned by the provider. The current position is that consumer assignment is not supported  and provider assignment may be supported.

**Comment by james-answer** [comment]
By including this in the guidance without specifying any real use for the business identifier it will just cause confusion and is not nessersary. The resource profile indicates other identifiers can be included so it does not also need to be included in the specificaiton if it does not add any additional meaning.
