### ISSUE TITLE
Appointment Resource Profile - clarity on use of extenstions

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#174]
Addition of clarity on the use of the following extenstions on [gpconnect-appointment-1](https://www.simplifier.net/GPConnect/gpconnect-appointment-1/rendered)

appointmentCategory
appointmentBookingMethod
appointmentContactMethod
appointmentCancellationReason

**Comment by michaelmeasures** [comment]
@briandiggle suggest we drive this review by capturing more detailed use-cases / user stories as this will also help shape the assurance process.

**Comment by james-answer** [comment]
As part of appointments rc.1 release the following extensions were removed from the profile:

* appointmentCategory
* appointmentBookingMethod
* appointmentContactMethod

The use of the "appointmentCancellationReason" is well documented between the cancel and amend appointment pages, therefore closing the issue as it is no longer an issue.
