### ISSUE TITLE
Locum doctor use case  - expected behavior?

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#175]
Given a use case where a doctor is not able to run their clinic due to ill health, and a locum covers the clinic, what would be the expected behavior?

Current working assumption is that where there is a change to the practitioner referenced from a schedule, that all linked resources would be updated - practitioner referenced in appointment resources which are linked to the schedule via the slot resource.

**Comment by briandiggle** [comment]
I.e. any scenario where the practitioner changes after appointment is booked

**Comment by james-answer** [comment]
The assumption is correct, the relationship/links between the FHIR resources is a result of the model behind the scenes in the appointment booking system.

If a practitioner is changed for a schedule then all appointments which have slots linked to that schedule should also show the updated practitioner reference if a read or search is done for the appointments. The references within resources should not be fixed values, they should reflect the actual underlying data, so if the data underneath changes then the references should change.

@briandiggle do you think this needs to be outlined specifically in the specification or are you happy the appointment specification already implies this?

**Comment by briandiggle** [comment]
So the specification for "book an appointment" currently says:

_Provider SHALL maintain resource state in accordance with their own internal integrity constraints, including the state of any associated resources, such as Slots, Schedules, etc._

Personally I find this statement a little abstract, and an example of an application of this principle would be of use

**Comment by james-answer** [comment]
Decision: Move this from book appointment api use case into common api guidance and add examples of use cases like locum doctor.
