### ISSUE TITLE
Ensure that the original Appointment feedback on Openhealthhub has all been addressed.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#176]
Back in April 2016 Dunmail gave some good feedback on OpenHealthHub around the Appointment profiles and API specifications. We need to ensure all this feedback has since been addressed and comment back on OpenHealthHub with a link back to GitHub.

https://www.openhealthhub.org/t/gp-connect-appointments-practitioner/383/3
https://www.openhealthhub.org/t/gp-connect-appointments-patient/381/2
https://www.openhealthhub.org/t/gp-connect-appointments-schedule/385/1
https://www.openhealthhub.org/t/gp-connect-appointments-general-points/380/3
https://www.openhealthhub.org/t/gp-connect-appointments-appointment/384/1
https://www.openhealthhub.org/t/gp-connect-appointments-gp-practitioner/382/1

**Comment by briandiggle** [comment]
I have raised each of the listed feedback as seperate issues:

https://www.openhealthhub.org/t/gp-connect-appointments-practitioner/383/3 - #246 
https://www.openhealthhub.org/t/gp-connect-appointments-patient/381/2 - #247 and #251 
https://www.openhealthhub.org/t/gp-connect-appointments-schedule/385/1 - #248 and #249 
https://www.openhealthhub.org/t/gp-connect-appointments-general-points/380/3 - #252 
https://www.openhealthhub.org/t/gp-connect-appointments-appointment/384/1 - #252 (for para 1), #253 (for paras 2 and 3), #254 (for para 4 and 5)
https://www.openhealthhub.org/t/gp-connect-appointments-gp-practitioner/382/1  - Not required

**Comment by briandiggle** [comment]
Closing this now that necessary issues have been raised - these can be tracked individually
