### ISSUE TITLE
Clarify acceptable Consumer system handling of the HTML Task narrative

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#179]
Something like...

Consumer systems MAY downgrade the HTML Task narrative details into a plain-text representation for rendering in client systems that don't support HTML rendering.

Provider systems SHALL NOT encode any clinical meaning into the HTML Task narrative markup which would preclude a Consumer system from safely downgrading the narrative to a plain-text format for rendering.

**Comment by jonnyry** [comment]
Tasks now being handled as part of FHIR Generic Receiver project.
