### ISSUE TITLE
Add a Consumer track to GitHub with requirements for Access Record HTML

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#181]
Currently Consumer requirements are spread-out throughout the GitHub site and really need to be centralised into one place to help streamline development and assurance.

**Comment by michaelmeasures** [comment]
Also in some situations Consumer requirements are implied, these need to be enumerated out in full.

**Comment by jackiebarnes** [comment]
Being done as part of Github re-structure
