### ISSUE TITLE
Added details of the 4 Spine message/product sets which define to the GP Connect capabilities

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#182]
We have split the master list of GP Connect interactions into 4 separate product sets; the GitHub site needs to be updated to reflect this in each pack.

**Comment by michaelmeasures** [comment]
[GP Connect Provider Message Sets.xlsx](https://github.com/nhsconnect/gpconnect/files/1055283/GP.Connect.Provider.Message.Sets.xlsx)

**Comment by briandiggle** [comment]
I notice that a "GPC Patient Registration" message set is found in the spreadsheet "GP Connect Provider Message Sets"  - should the urn:nhs:names:services:gpconnect:fhir:operation:gpc.registerpatient interaction be found in the "GPC Foundations" message set? Do we need a separate message set for this one interaction?

Also, I believe that the interactions as currently defined are not "provider only" interactions, but can also describe consumer accredited capability in spine configuration.

**Comment by michaelmeasures** [comment]
@briandiggle sorry I didn't add the link in my original description but the following page [FHIR Operation Guidance](https://nhsconnect.github.io/gpconnect/development_fhir_operation_guidance.html) should also be updated.
