### ISSUE TITLE
GPConnect-Appointment-1 reason coding documentation links broken

### ISSUE THREAD

**Issue by Chrisjobling** [nhsconnect/gpconnect#183]
I am trying to access the documentation for coding (SNOMED CT), coding (READ V2) and coding (READ CTV3) on https://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.GetScheduleQueryResponse/gpconnect-appointment-1.html. I specifically want the codes and display for each of the coding systems but the links appear to be broken:
The codes SHALL be taken from http://snomed.info/sct
The codes SHALL be taken from http://read.info/readv2
The codes SHALL be taken from http://read.info/ctv3

Can someone point me in the right direction to get the codes and displays?

**Comment by michaelmeasures** [comment]
@Chrisjobling the NHS Digital site for this info looks like https://digital.nhs.uk/article/290/Terminology-and-Classifications which has https://digital.nhs.uk/snomed-ct and https://digital.nhs.uk/article/1104/Read-Codes. It looks like http://snomed.info/ works for browsing SNOMED for multiple jurisdictions including the UK.

**Comment by michaelmeasures** [comment]
@Chrisjobling it's important to note that the use of URIs to reference external code systems is part of the FHIR standard's [Known Terminologies](https://www.hl7.org/fhir/dstu2/terminologies-systems.html) guidance. You'll notice the URI for SNOMED CT is correct per the FHIR DSTU2 standard. However, the fictitious READ v2 and v3 URIs don't appear in the base specification and may (or more likely not) have been officially registered. Looking at the WHOIS record for the read.info domain it appears to be registered to someone in the US (Washington) so not anyone in the UK that is affiliated with the UK Terminology Centre (UKTC) who I believe are responsible for the READ code sets.

**Comment by james-answer** [comment]
Change to fhir reference server and changes which are going to be made to the appointment resource and the contained resource, this is no longer an issue so we are closing.
