### ISSUE TITLE
Clarify acceptable usage of sub-section banners and uplift the specification.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#184]

**Comment by adamjlees** [comment]
For sections without sub-sections, Encounters, Clinical Items, Admin Items, Obs
general principle agreed that Section Banner should contain:
- Section Title
- Section Date Range Applied, Where Applicable 
- Section Content Desc
- Section Excluded Items Indication Message

Sections with Sub-Sections - Probs, Allergies, Medications
- Section Title
- Sub-Section Title
- Sub-Section Date Range Applied - where applicable - ie Past Medications, and Inactive Problems only
- Sub-Section Content Desc
- Sub-Section Excluded Items

For Summary section - Section Banner = Not applicable

**Comment by tim1ford** [comment]
This section has been uplifted to the following:

HTML views with multiple tables
HTML views with multiple tables and hence multiple sections are:

Problems, Allergies, Medications.

These views SHALL have the following structure:

Section title
GP transfer banner
Content banner (if applicable)
Subsection (repeated for each subsection)
Subsection title (for example, Current Medications)
Subsection content banner (if applicable)
Date banner (if applicable: section date range applied)
Exclusion banner (if applicable, to indicate excluded items)
Table
{% include custominfocallout.html content="Note: This layout does not apply to the Summary HTML view. See Summary HTML view." type="info" %}

Single table example
<div>
  <h1>Encounters</h1>
	
  <div>
    <p></p>
  </div>
	
  <div>
    <p></p>
  </div>
  
  <div>
    <p></p>
  </div>
  
  <div>
    <p></p>
  </div>
  
  <table>
    
  </table>
</div>
Multiple table example
<div>
  <h1>Problems and Issues</h1>
   
  <div>
    <p></p>
  </div>
	
  <div>
    <p></p>
  </div>

  <div>
    <h2>Active Problems and Issues</h2>

	<div>
	  <p></p>
	</div>	  

	<div>
	  <p></p>
	</div>
    
	<div>
	  <p></p>
	</div>
    
	<table>
	  
	</table>
  </div>
  
  <div>
    <h2>Inactive Problems and Issues</h2>
	  
	<div>
	  <p></p>
	</div>	  
    
	<div>
	  <p></p>
	</div>
    
	<div>
	  <p></p>
	</div>
    
	<table>
	  
	</table>
  </div>
</div>

**Comment by tim1ford** [comment]
Delivered in 0.7.0
