### ISSUE TITLE
Generic Error Code for resource not found

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#185]
I am writing a test which tries to perform a read on a resource which does not exist on the provider system, the error code should be 404 as the URL is valid but the resource is not available as currently does not exist on the providers system.

The issue I have is working out what error code should be returned in the OperationOutcome, it should probably be something like "RESOURCE_NOT_FOUND", but on the error page of the specificaiton there is no appropriate error code. Should we add a generic error code like above to cater for when a read of any resource fails, eg. Appointment Read, Organization Read, Location Read.

**Comment by Dunmail** [comment]
Why not just use the standard HTTP description "Not Found"? From: https://tools.ietf.org/html/rfc7231

**Comment by michaelmeasures** [comment]
@james-answer it's totally my expectation and inline with the RESTful model that is a resource truly doesn't exist on the server then a standard HTTP 404 Not Found is used (as per @Dunmail's comment). I'd be happy to align with the FHIR reference server's behavior on this as it's not that useful to return an OperationOutcome in this instance (as the 'extra' detail of RESOURCE_NOT_FOUND doesn't add anything). Having said that I'm also happy to return an OperationOutcome for consistency purposes which would use the standard fields issue.severity='error' and issue.code='not-found'. However, for this to work we'd need to revert the profiled GPC OperationOutcome's 'details' field back to the base FHIR cardinality of [0..1] - which I think is a sensible thing to do anyway!

**Comment by james-answer** [comment]
Emis have asked about error code for Location not found. Talking to Brian there was a general preference to always return an OperationOutcome for consistency, do we want to stick with this and if so should we add a "RESOURCE_NOT_FOUND" error code rather than removing the need for an error code from the OperationOutcome.

**Comment by james-answer** [comment]
There is a strong preference to require the OperationOutcome to be produced so, rather than adding a new error code the "https://fhir.nhs.uk/ValueSet/spine-error-or-warning-code-1" now used by OperationOutcome there is the error code "NO_RECORD_FOUND" which would be descriptive enough to explain the error.
