### ISSUE TITLE
PDS trace sequence number on design decisions page

### ISSUE THREAD

**Issue by adamjlees** [nhsconnect/gpconnect#186]
PDS has a trace sequence number.  This would have been of use in determining whether providers need to perform a PDS trace themselves, for example if their local patient record's trace was not current.
However consumer requirements don't mandate full PDS compliance, and SMSP does not return this item.
Add to design decisions page

**Comment by briandiggle** [comment]
It would good to augment [https://nhsconnect.github.io/gpconnect/integration_personal_demographic_service.html](https://nhsconnect.github.io/gpconnect/integration_personal_demographic_service.html) with details of what is/ is not mandated for consumers.

**Comment by adamjlees** [comment]
Ticket #181 covers pulling consumer requirements together into a single track.
