### ISSUE TITLE
gpconnect-appointment-1 profile  - participant type and actor

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#190]
The [gpconnect-appointment-1](https://www.simplifier.net/GPConnect/gpconnect-appointment-1) profile has the following constraint on the participant element:
"Either the type or actor on the participant MUST be specified"

My assumption is that this constraint allows the following:
Type only present
Actor only present
Type AND Actor present

It would be helpful to state this more clearly

**Comment by michaelmeasures** [comment]
@briandiggle this looks to be a duplicate of #171 and as discussed on that ticket we need a lot more detail around exactly how these types can be used and what happens if you potentially get multiple participants of the same type etc.
