### ISSUE TITLE
Amend an Appointment - Use cases

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#191]
1. As mentioned in #152, the use case appears to be a cut/paste from the "Cancel Appointment" API 

2. Should we explicitly state that the "Re-schedule" use case, though it could be considered a type of amend, should be handled through two API interactions - firstly Cancel (existing time slot), then secondly Book (at new time slot)

**Comment by devmikey** [comment]
Yes. We should specify the guidance as you have  outlined

**Comment by james-answer** [comment]
Decision: Add this as a design decision to the appointment capability pack.
