### ISSUE TITLE
Amend an Appointment - Error Handling specifics

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#192]
[Error Handling section](https://nhsconnect.github.io/gpconnect/appointments_use_case_amend_an_appointment.html#error-handling)

Should any field be updated other than reason, are we expecting the error to be a [ resource validation error ](https://nhsconnect.github.io/gpconnect/development_fhir_error_handling_guidance.html#resource-validation-errors) of error code INVALID_RESOURCE, including further details in the diagnostics element of the OperationOutcome resource

**Comment by james-answer** [comment]
does this relate to:

https://github.com/nhsconnect/gpconnect/issues/152

**Comment by james-answer** [comment]
Update wording to be clearer that it should be 422 and invalid resource.
