### ISSUE TITLE
Amend an Appointment - Expected Behavior on Reason update

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#193]
What is the expected behavior for updates on the Reason element? Can all child elements of the Reason element be updated as the example given suggests that only the text sub-element be used to update.

I assume that the expected behavior is that the received Reason element will replace the existing element. For example where the existing element contained a READ CTV3 code only, and the received element contained a SNOMED CT code, that the resultant resource would contain only the SNOMED CT code.

**Comment by briandiggle** [comment]
Can previous state be lost with the assumption that auditing will retain history?

**Comment by jonnyry** [comment]
Yes - I think it's reasonable that the reason is overwritten with an update to the field.  Auditing would maintain the history.

Worth checking whether the principals support coded reason - my instinct is that they don't.

**Comment by james-answer** [comment]
Decision was made to update the spec to add clarification within the specification for the expectaion that updated elements such as reason will be overwritten and the provider should not look at the delta between the new element and old element, picking and choosing what they update.
