### ISSUE TITLE
Cancel an Appointment - interaction to be used

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#194]
What interaction ID should be used for Cancel an Appointment?
[FHIR Operation Guidance](https://nhsconnect.github.io/gpconnect/development_fhir_operation_guidance.html#stage-1--2-fhir-operations) has conflicting information:

> RESTful syle API = [ create, read, update, delete, search ] + any more specific actions (**i.e. cancel**).

BUT, the cancel an appointment is shown listed with the following interaction in the table below this:

> urn:nhs:names:services:gpconnect:fhir:rest:**update**:appointment

Additionally, I have information from the DIR  team which includes the following statement of Appointment Management capability interactions:

urn:nhs:names:services:gpconnect:fhir:operation:gpc.getschedule  
urn:nhs:names:services:gpconnect:fhir:rest:read:appointment 
urn:nhs:names:services:gpconnect:fhir:rest:create:appointment  
urn:nhs:names:services:gpconnect:fhir:rest:update:appointment  
urn:nhs:names:services:gpconnect:fhir:rest:**cancel**:appointment  
urn:nhs:names:services:gpconnect:fhir:rest:search:patient_appointments

Finally, I note also that existing SDS configuration in the development environment includes ASIDs which have the urn:nhs:names:services:gpconnect:fhir:rest:**cancel**:appointment interaction.

**Comment by michaelmeasures** [comment]
@briandiggle this is something I've struggled with to be honest. Basically, from an API interaction point of view both update and cancel are just a resource update (i.e. HTTP PUT). However, I can see from a business perspective that it may be useful to distinguish between them for things like technical accreditation, role based access and data sharing rules. However, we don't have any firm requirements in that space to push us down the path of registering more fine-grained interactions... and my concern is that it's somewhat of a slippery slope as you could potentially end up needing _lots_ of logical interactions for updating every single field on the appointment. So I'm somewhat torn between keeping it as simple as possible (i.e. they're both just an update) vs. adding in the logical interaction so if we do get some future requirements we can enforce it more easily in the SSP without having to inspect the payload.

**Comment by Dunmail** [comment]
Check out the CQRS pattern for useful insight (command == FHIR operation). Updates are actually more complex to implement than commands (both as consumer *and* provider) as you have to build and verify a whole resource. I don't think that you will have lots of fine-grained interactions as you will identify a discrete set of business-oriented operations on the resource. An added complication is that operations often require significant orchestration e.g. if you update the Slot reference on an Appointment, you might have to check that the Appointment begin/end still reflects the Slot begin/end, etc, etc ...

You also identify a key benefit: it is easier to provide granular control over commands than try to write business logic to infer the command from the delta within the resource and then determine if a user is allowed to perform the action.

**Comment by briandiggle** [comment]
After discussion it was felt that an interaction is a spine construct which represents a business process action, and that this cannot easily be mapped onto HTTP Verbs. Therefore to maintain a consistent approach, the `urn:nhs:names:services:gpconnect:fhir:rest:cancel:appointment` interaction ID should be used.
