### ISSUE TITLE
JWT "requested_record" claim for non patient or organization centric requests

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#196]
In the "Cross Organisation Audit & Provenance" part of the specification it lists out a number of expected claims within the JWT.

https://nhsconnect.github.io/gpconnect/integration_cross_organisation_audit_and_provenance.html

The "requested_record" claim says it should be a Patient resource for patient centric operations which is fine for things such as, Patient Search, Patient Read, Book Appointment, etc as you know who the patient is. The other option is to include an organization but it is not always clear what organization this should be. For the following examples some are obvious but some are not:

1. Organization Read and Organization Search - Should this be the organization you are searching for or trying to read?
2. gpc.getschedule operation - should the organization be the organization the getschedule operation is for?
3. Practitioner Read/Search and Location Read/Search - What organization should this be?

This area of the spec is not clear and if we are expecting providers to validate the JWT we need to make clear what should be included in the JWT.

**Comment by adamjlees** [comment]
For patient and org searches I think it's reasonably clear.

The purpose of carrying these items in the token is audit on the provider system.
Logically the claim is for "requested_record" so should refer to that.  If the interaction is a search to resolve the logical Id on the target system _of the consumer's organisation_, it should refer to that org.

Footnote: "2 Patient scope for patient centric APIs (i.e. Get Care Record and Patient’s Appointments, Patient Task) or scope for organisation centric APIs (i.e. Get Organization Schedule)"

1. Should be the org which is the subject of the search/find
2. Should be the org which is the subject of the getschedule
3. Is where I believe the spec is misleading.  

I can read it in two ways  The logical implication of "requested_record" is that this should be the practitioner and location resources you're asking for.

On the other hand what is the "scope for organisation centric APIs"?  Do we deem practitioner and location as "organisation centric" as they are linked to an organisation?

**Comment by james-answer** [comment]
I have been reviewing the test for organization search and organization read and the question of which organization should be in the JWT requested_record is no actually clear for organization search. As the organization search can be a search using ODS Site code it could in theory return multiple organizations which share a site, in this situation which organization would be used in the JWT.

The provider needs to have a more consistent and clear expectation of what to expect in the JWT if we are going to expect them to validate the content like they were expected to in the Access Record testing.

For organization search if the parameter is Organization ODS code then we could include that but if it it Site ODS Code what should it be, the Organization ODS Code of the provider system you are searching on? If so should this be different for when we search by a different type of identifier or should it always be the organization of the endpoint you are performing the search on?

**Comment by briandiggle** [comment]
Suggest we add a sub-section on with "Guidance on use of requested_record" with the clarifications, and examples of expected minimal FHIR resources to be included.



Clarity is needed on the intended use of this claim. If the intended use of this claim to provide auditing details which describe the resource being requested, then I am not clear why this is limited to either Patient and Organisation. For a Patient search, we would seem to lose details of the requested record if a minimal fhir resource describing the Organisation associated with the target logical FHIR server is provided.

Need to also change "The FHIR patient resource being requested (i.e. NHS Number identifier details)" to something not specific to Access Record requests.
e.g. "A Minimal FHIR resource which describes the resource being requested or searched for."

**Comment by ahatherly** [comment]
Dumb question - the resource being requested is in the URL, so why would it need to be duplicated here? 
The ultimate purpose of an access token is for authorising access (accepting that we aren't using it for that yet), and you'd ideally request access once for the scopes you need, then you may use that same token for a series of individual FHIR API calls within those scopes - so you wouldn't really want to duplicate bits of each specific request in the JWT? 
I think the original purpose of this was to have a token that asserts that you have been authorised to make API calls for data about patient X - it doesn't stop you also making calls for organisations using the same token (for example)?
