### ISSUE TITLE
Read an Organisation - Handling of ODS Site Codes

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#197]
[Read an Organisation response body](https://nhsconnect.github.io/gpconnect/foundations_use_case_read_an_organisation.html#payload-response-body)

Response body:
•	SHALL include all relevant business identifier details (i.e. ODS Code and/or ODS Site Code) for the Organization resource.

Does this mean that , where the logical ID of the requested organisation refers to a site within an organisation, both the ODS and ODS Site code business identifiers should be present? I.e. in this instance the ODS Organisation Code will refer to the Organisation of which the site is a part

Additionally, what is the expected behaviour for the use of the partOf element in this case? The partOf elemement is shown with cardinality of 0..1 in the [gpconnect-organization-1]
 (https://www.simplifier.net/GPConnect/gpconnect-organization-1) profile however should a reference to the ODS Organisation resource be present?

**Comment by jackiebarnes** [comment]
Also:  Should there be at least one ODS Org Code in GPConnect-Organization-1 rather than 0..*?

Should the managingOrg of GPConnect-Location-1 be 1..1 rather than 0..1?

**Comment by michaelmeasures** [comment]
@jackiebarnes I don't believe any of the suppliers are currently intending to populate the Location details (so whilst technically you may be correct that managingOrg should be 1..1). I'd suggest staying with the flexibility inherent in the base FHIR standard and leave it as 0..1 until we've got a clear use case and someone who's will to populate it. This is also likely the best course of action because location can be used for things like the Patient's home or Jurisdictions which don't have a managing organisation.

**Comment by michaelmeasures** [comment]
On the other point of if the ODS Code on an Organization should be mandatory then the same logic applies. We know that there are organisation out there that don't use ODS Codes so locking this down would limit future use cases (such as booking into these organisations).

**Comment by michaelmeasures** [comment]
@briandiggle it was only to indicate that if the Organization is a branch surgery then it will have the ODS Site Code and if it's appropriate also the ODS Code. Note, I've never managed to actually find a definitive list of ODS Site Codes. The online GP Practice details are all simply 6 digit ODS codes (even for branch practices). Also, the slicing looks wrong as the cardinality is 0..* on ODS Site Code in the DMS (which doesn't really make any sense). I'd have expected 0..1 with another slice for any additional identifiers. Note, this could just be an issue with the DMS publication tooling which in the past has thrown up a HTML view for the resource which doesn't actually match the intent of the machine readable FHIR profile.

**Comment by adamjlees** [comment]
I think there is no need to change the spec as a result of this ticket so I'm closing it.  Feedback from suppliers indicates little use of ODS site codes in locations.  The spec mandates inclusion of all _relevant_ business identifiers so I think this is ok as is.  
As for cardinality I would recommend keeping the optionality we have, so no change.
