### ISSUE TITLE
Access Rec HTML: Past Medications - Banner Content Discont./Cancelled Meds Msg

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#199]
For Providers not able to differentiate between prescriptions ended 'normally', and those discontinued/cancelled before the original prescribed end date, for Stage 1 specification, to be mitigated by Banner description wording (pending Sub-Section Banner specification uplift):

"Past Medications may include prescriptions which have been cancelled or discontinued before the original prescribed end date" 

HDL-177

**Comment by adamjlees** [comment]
Uplift accessrecord_view_medications
Past Medications section
