### ISSUE TITLE
Split out the capability packs into their own git sub-modules so they can be separately versioned and included into the overarching pack.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#202]
See the following for details at how git repos can be pulled into another git repo inside a folder.

https://github.com/blog/2104-working-with-submodules

**Comment by james-answer** [comment]
As we are moving to a single version for the whole specification then it does not make sense to split out the specification into sub modules as this will cause versioning and release tagging issues. The specification should remain a single github repo.

**Comment by james-answer** [comment]
We are no longer going to split up the specification as we are going to a singel specification version, therefore closing this issue.
