### ISSUE TITLE
Add sequence diagram for the "send a task" API use case to the Task Management capability pack

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#203]
It would be useful to include an introduction page in which the sequence diagram which Adam has produced could provide context on how individual API use fits in with typical business use scenarios, and links with necessary calls to foundation capability APIs.

**Comment by jonnyry** [comment]
Tasks has been moved into the "Phase 2" asynchronous capabilities work stream and so this issue is no longer applicable.
