### ISSUE TITLE
Ensure all HTML Views have a runnable CodePen and a rendered raw HTML version with realistic data

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#205]
See the [Encounters View](https://nhsconnect.github.io/gpconnect/accessrecord_view_encounters.html) for a runnable [CodePen for Encounters](https://codepen.io/gpconnect/pen/rrNKWb) using an Angular template.

**Comment by michaelmeasures** [comment]
See https://github.com/nhsconnect/gpconnect/commit/66ad6562f1a66f1fa6ce7f824c1ef6ab37ce7ce0 for an example of how this can be done using an embedded CodePen which only shows the HTML output. Note, to improve the page load experience I've currently made it so you have to click the CodePen to run the example to generate the HTML, but this can be configured differently so it runs by default if so desired.

**Comment by tim1ford** [comment]
CodePens created for each HTML view, data needs to be checked for accuracy.

**Comment by tim1ford** [comment]
In spec 0.7.0 all HTML views (excluding the Summary page) have a codepen.
