### ISSUE TITLE
Populate the Open API Licence Design Principles page with final commercial details

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#207]
http://gpconnect.netlify.com/designprinciples_open_api_licence_principles.html

High-level design principles related to the commercial licence for participation in the Open API ecosystem.

- Acceptable Use
- Reciprocity of Data Access
- Etc.

**Comment by jonnyry** [comment]
Page has been removed - Open API license is now part of the Connection Agreement which will be added to GitHub as part of the consumer on-boarding work stream.
