### ISSUE TITLE
Clarification of Authorisation header

### ISSUE THREAD

**Issue by ahatherly** [nhsconnect/gpconnect#213]
I assume from the referenced RFC that the JWT will go into an Authorisation: header with the encoded JWT prefixed with "Bearer " (to identify it as a bearer token) - if so it might be worth saying this explicitly on the Cross Organisation Audit and Provenance page to avoid implementors missing the "Bearer " prefix.

**Comment by Dunmail** [comment]
```
//pedantic but important!
req.headers.Authorization !== req.headers.Authorisation
```
[RFC](see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) ;)

**Comment by ahatherly** [comment]
A very good point - apologies!

**Comment by briandiggle** [comment]
Added a quick example to emphasis the format of the bearer token header.
