### ISSUE TITLE
Access Record HTML format

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#214]
For Access Record, in the "HTML Views" pages there are "HTML View" sections (eg. https://nhsconnect.github.io/gpconnect/accessrecord_view_allergies.html#html-view) which show how the HTML should be formatted for all the sections.

These have always been treated as part of the spec, indicating the proposed tag format and structure for the HTML. It was just raised that this is not clear so we should update this to specifically say that the format and tags should be followed for the HTML structure (eg it was proposed that the spec allowed h1 tags to be used instead of h2 tags but this would cause issues for the consumers when rendering the response HTML).

We probaly also want to remove the ng-repeat stuff and replace it with HTML Comments so there is no confusion around requiremnts for suppliers to use specific technologies and attributes.

**Comment by RiChallinor** [comment]
Linked to [HDL-185](https://answerconsulting.jira.com/browse/HDL-185)

**Comment by tim1ford** [comment]
All HTML view sections have been updated:

- ng-repeat removed
- banner `<div>` added for:
  - GP Transfer banner
  - Content banner
  - Date banner
  - Exclusion banner
- IDs and classes have been added to help improve consumer styling (a requirement has been added for these)
- `<H1>` and `<H2>` heading tags have been aligned across all views (a requirement has also been added for these)
