### ISSUE TITLE
Uplift security guidance to remove two temporary ciphers

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#216]
When confirmation is received that temporary use of these ciphers has ceased, remove the following from [Security Guidance](https://nhsconnect.github.io/gpconnect/development_api_security_guidance.html#supported-ciphers)

AES256+SHA (temporary support for limited roll-out/FoT only)
AES128+SHA (temporary support for limited roll-out/FoT only)

**Comment by briandiggle** [comment]
At present, the LTH pilot continues to have a requirement for one of these cipher suites. Plans to upgrade the component are ongoing - but not complete.

Therefore moving to next core release to re-check status.

**Comment by james-answer** [comment]
Moving this onto the next release as the changes required to support the new ciphers have not currently been made by all the providers.

**Comment by jonnyry** [comment]
Merging into #387 Update ciphers list & TLS support
