### ISSUE TITLE
Updates to error handling guidance

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#217]
- Make clear that OperationOutcome is not the base FHIR DSTU resource by profiled resource GPConnect-OperationOutcome-1

- Update examples to point at the https://fhir.nhs.uk/ValueSet/spine-error-or-warning-code-1 value set, for the details codeable concept

- Ensure that https://fhir.nhs.uk/ValueSet/spine-error-or-warning-code-1 contains only newly added status codes and spine error codes. E.g. 501- OPERATION_NOT_IMPLEMENTED

**Comment by Dunmail** [comment]
Is there a link to the latest GPConnect-OperationOutcome-1 structure definition? The examples I can find have a required binding to a specific set of codes. How will unanticipated error scenarios be communicated? For example, technical errors that would normally result in response status 502/503/504
