### ISSUE TITLE
JWT aud claim - correct usage?

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#218]
Re: 
[JWT aud claim](https://nhsconnect.github.io/gpconnect/integration_cross_organisation_audit_and_provenance.html#json-web-tokens-jwt)

This has a fixed value of https://authorize.fhir.nhs.net/token

1. Normally the aud claim would identifyt eh _audience_ for the token. I.e. you would expect the URI of the protected resource here - the FHIR Server Root URL for the organisation as returned from an endpoint lookup.

2. Also, the fixed value indicates the presence of a central NHS OAuth authorization endpoint, which does not at present exist.

**Comment by Dunmail** [comment]
Same question as: https://github.com/nhsconnect/gpconnect/issues/154

**Comment by briandiggle** [comment]
duplicate of #154
