### ISSUE TITLE
Register a Patient - Registration Type values

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect#219]
Clarification is needed on the use of the registration type values that denote what a temporary patient actually is.

In the DMS GPConnect-Register-Patient-1 Registration Type 'T' is listed as a 'temporary resident'. Is this correct? This implies that the patient is for example an overseas visitor, and seems not to be in sync with the notion that patients should be registered as temporary patient by the Provider once they have performed a PDS trace

**Comment by briandiggle** [comment]
Decision has previously been taken that the profile GPConnect-Register-Patient-1 will be updated to make the three registration options optional:
registrationType
registrationStatus
registrationPeriod

It is the responsibility of the provider to populate these fields appropriately on the response.

Analysis continues to establish clearer guidance for providers on how these fields should be populated.

**Comment by briandiggle** [comment]
Linked to clarity required on use of these three fields as described in HDL-160. Awaiting results of analysis

**Comment by james-answer** [comment]
Will be done as part of #233, with guidance on the populating the new extension within "CareConnect-GPC-Patient-1".
