### ISSUE TITLE
Incorrect parameter on payload request body sample for register patient operation

### ISSUE THREAD

**Issue by adamjlees** [nhsconnect/gpconnect#220]
https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html#payload-request-body

Parameter is of type Patient but has no profile.  This should be the profiled patient resource, currently gpconnect-register-patient-1

**Comment by briandiggle** [comment]
Change required:
Update [https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html#payload-request-body](https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html#payload-request-body)

Replace out of date OperationDefinition XML with [https://simplifier.net/GPConnect/gpconnect-registerpatient-operation-1/~xml](https://simplifier.net/GPConnect/gpconnect-registerpatient-operation-1/~xml)

**Comment by briandiggle** [comment]
Also on response, the following change is required:

foundations_use_case_register_a_patient.html#payload-response-body

Example response body indicates that the patient resource is profiled to http://fhir.nhs.net/StructureDefinition/gpconnect-patient-1

However, the DMS indicates that the response patient should be profiled to http://fhir.nhs.net/StructureDefinition/gpconnect-register-patient-1

See https://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.RegisterPatientRequest/gpconnect-registerpatient-operation-1.html
