### ISSUE TITLE
Register a Patient - Clarity on returned resources

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#226]
Outstanding questions from #133 and #168:

The response body..

**SHALL include the Patient, Practitioner and Organization details for the newly registered patient record in a searchset Bundle.**

Regarding resources returned from a successful Register a patient API call:

1. Practitioner resource. I don't believe this can be sourced from PDS by the provider system doing the PDS trace which is triggered by the API request. Does this therefore refer to a practitioner at the _federated_ practice which is assigned by the provider  the 'locally' assigned GP for that patient at the federated practice?
2. Organisation resource? Is this the organisation resource which maps to the ODS code of the PDS registered practice? Or is it the organisation resource which maps to the ODS code of the federated practice where the temporary patient record is created?

**Comment by james-answer** [comment]
Decision made to remove Practitioner and Organization out of specification.
