### ISSUE TITLE
Clarify meaning of Active Patient in relation to "Find a patient"

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#232]
We need to clarify what is considered an active patient, as active patients should be returned for a "Find a patient" request.

After having a meeting to discuss book appointment flow of requests the following covers a definition of Active:

The following image shows the quick diagram of Patient Types and Patient Status. The "Active" Status can apply to any Patient Type, any patient which is active should be returned by "Find a patient" capability. The other status's "Dead", "Left/Deducted" are considered "Not Active" therefore would not be returned by "Find a patient".

![img_20170824_161308 - copy_li 2](https://user-images.githubusercontent.com/12611757/29673905-7df6a734-88e8-11e7-8fdd-91196ba5f857.jpg)

**Comment by lasm1** [comment]
@james-answer @jackiebarnes  Need to consider that there are other patient registration types within the system, eg maternity, private, contraception clinics

Probably need to consider the below

1) clarify if a patient would ever have 2 registration types within one organisation
2) If a patient has only one record,  however this a 'maternity' registration for example, would it be acceptable to use this for a GP connect appointment or would a second record be created in this instance?

**Comment by james-answer** [comment]
@lasm1 1. The registration types written down were just some types our team had come across in the past and they were a good example to represent the definition of active. We agree that there will be different registration types for different providers, these are just an example to help represent that registration type is different to the concept of an "Active" patient. There is nothing stopping a patient having two registration types within a providers system and that patient still be considered "Active" or "Not Active". 

2. If you have a patient which has been registered for maternity, if they needed booking in for another type of appointment on your system would you currently use the same patient record, would you create a new patient record with a different registration type so you have a duplicate patient record or would you add an additional registration type to that same patient record and use the same patient record? 

Currently GP Connect patient does not have an extensive list of registration types for a patient therefore when a "Find a patient" is done you would return the patient and the fact that it is a maternity registration would probably not be reflected therefore a consumer could try and book a different type of appointment against that patient. Depending on the usual process you have for booking appointments you may need to update the patient record when an appointmentment is booked to include an appropriate registration type.

**Comment by james-answer** [comment]
Further discussion was had around meaning of active patient. Re-opening this issue to perform changes to spec.
