### ISSUE TITLE
Incorrect system for patient NHS Number identifier on Find a patient

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#240]
On the "https://nhsconnect.github.io/gpconnect/foundations_use_case_find_a_patient.html" page the system for the identifier parameter and example resource has not been updated to the correct system:

Was and is currently: ***http://fhir.nhs.net/Id/nhs-number***
but should be: ***https://fhir.nhs.uk/Id/nhs-number***

As this is actually wrong I would suggest we do a patch release of "Foundations-1.0.0-rc.1" or do something like "Foundations-1.0.0-rc.1.1" as this needs fixing imidiatly.

**Comment by james-answer** [comment]
The same applies to "Find Practitioner", "Find Organization" and "Find Location"

**Comment by Dunmail** [comment]
For reference, HL7 UK have published a registry of system identifiers here: https://github.com/HL7-UK/System-Identifiers
