### ISSUE TITLE
[From openhealthhub.org] Practitioner language valueset not consistent between Patient resources

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#246]
See https://www.openhealthhub.org/t/gp-connect-appointments-practitioner/383

"Practitioner.communication has required binding to human-language-1-0.html, whereas FHIR STU Practitioner has required binding to IETF language tags. This means that any valid gpconnect-practitioner using *.communication can not simultaneously be a valid Practitioner.

I think this needs amending. Consider:
a) provide an extension with the UK preferred ValueSet
b) amend cardinality to 0..2 and carry UK preferred ValueSet as a second code within the CodeableConcept

It's worth noting that Patient.communication isn't defined, but for consistency it would seem to make sense to add it."

**Comment by briandiggle** [comment]
Careconnect profiles appear to have gone with option a).

https://fhir-test.hl7.org.uk/StructureDefinition/CareConnect-Practitioner-1 has an nhsCommunication extension with language valueset of https://fhir.nhs.uk/ValueSet/CareConnect-HumanLanguage-1
