### ISSUE TITLE
Visibility of decision log process

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#249]
See second issue on https://www.openhealthhub.org/t/gp-connect-appointments-schedule/385

"How do we represent Slot for a home visit where Location is the patients' home?

How do we represent Slot for a virtual consultation e.g. by phone/video? contactMethod extension attempts to be a solution, but it's not clear to me how this will work in a coherent way e.g. an Appointment booked into a Slot of type 'Home Visit' with Schedule.Location 'GP surgery' and Appointment.contactMethod 'VIR'."

**Comment by briandiggle** [comment]
**"How do we represent Slot for a home visit where Location is the patients' home?":**
HDL-70 addressed this question, the decision being: "FoT stage scope will not explicitly include home visit however if home visit is required there can be local agreement to this utilising existing API capability."

**Virtual bookings**
Can we be more specific in our guidance regarding virtual appointments? Schedule location and slot type are defined by the provider (local setup variations would likely apply)
The Appointment extension AppointmentCategory could be used by a consumer to specify a VIR appointment category
The Appointment extension AppointmentContactMethod does not contain a "VIR" value, but does have "ONL" for online

**Comment by james-answer** [comment]
The requirements for home visit is achievable using the existing API capability with local agreements as communicated in HDL-70. The same applies for  virtual bookings which can be fulfilled using the existing API capabilities with local agreements.

The spec says in clinical scenarios that home visit is supported but how this will be done is not elaborated on in any other part of the specification. There is not a reason to add additional information as home visits and virtual bookings will be done using a local agree method so we can not specify one reason in the spec.

**Comment by Dunmail** [comment]
Where is HDL-70 published?

**Comment by james-answer** [comment]
HDL-70 will have been comminicate to the providers through the usual descision log process.

**Comment by Dunmail** [comment]
So how is the decision and associated history communicated to:
a. the reviewer who raised the issue?
b. the standards org (HL7 UK) who have been asked to endorse the spec?
c. a provider considering implementing the interface?

Is there any way that the decision log can be published more widely?

**Comment by jonnyry** [comment]
Clarification on decision 147 -

Suppliers have indicated limited ability to provide values for this field in a nationally consistent manner. Some of these are recorded using locally configurable values in slot and session type.

Decision for Appointments RC1 release is carry existing slot and session type fields with locally recorded values.

During subsequent phases of the GP Connect implementation we will continue to monitor the requirements for this field - and consider ways in which suppliers could be able to populate them consistently with a nationally applicable value set.

**Comment by jonnyry** [comment]
@Dunmail Currently the "HLD" - the decision log - is an internal process for agreeing on and communicating business rule changes for GP Connect.  These are mirrored as Git issues where they cause a change to the specification.

Will speak to colleagues re your specific questions on the decision log.

**Comment by Dunmail** [comment]
@jonnyry: Thanks - it would really lend credibility to the standards creation process if it was conducted in the open. I think this would help to encourage wider participation.

**Comment by briandiggle** [comment]
Original issue has been resolved:

"The spec says in clinical scenarios that home visit is supported but how this will be done is not elaborated on in any other part of the specification. There is not a reason to add additional information as home visits and virtual bookings will be done using a local agree method so we can not specify one reason in the spec."

Re-assigning the remaining question on visibility of the decision log process to the next release of the overview area of the specification so this is not lost.

**Comment by briandiggle** [comment]
See #75  also

**Comment by jonnyry** [comment]
The CareConnect curation process is now the (open) forum for profile curation decisions.
