### ISSUE TITLE
Retrieve a patients appointments - error handling specifics

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#250]
Re: HDL-115

What if the search prefixes are such that it is logically impossible for any records to be returned? So a request is passed that contains <= 2016-09-16 and >= 2016-09-30. Should this be an error or just a null response?

Reponse should be error with OperationOutcome
HTTP Status code: 422
Error Code: "INVALID_PARAMETER" 
Description: Submitted parameter is not valid
Diagnostics can give further specifics.

**Comment by adamjlees** [comment]
This was covered in another issue, possibly in access record (consumer-supplied date ranges).  IIRC the decision was to return an empty response.
