### ISSUE TITLE
[From openhealthhub.org] Business identifiers in profiles

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#252]
Another point: There is a pattern in some of the profiles (e.g. Slot) where an explicit identifier has been documented e.g. 'An identifier used to identify the slot'. I'm not clear what the intent is here. What added value is there from Slot.identifier, over Slot.id?

**Comment by briandiggle** [comment]
In the [gpconnect slot profile](https://fhir-test.nhs.uk/StructureDefinition/gpconnect-slot-1) the business identifier has been constrained to 0..1 from 0..* in the base FHIR DSTU2 slot resource. I guess the description could "a business identifier used to identify the slot". 

Is 0..1 cardinality too restrictive? Could we envisage a slot have >1 business ID?

**Comment by briandiggle** [comment]
Also should consider the related question from https://www.openhealthhub.org/t/gp-connect-appointments-appointment/384:

_What added value is there from Appointment.identifier, over Appointment.id?_

**Comment by briandiggle** [comment]
Decision is to align with the base FHIR profiles for slot and appointment for business identifiers. I.e. leave cardinality at 0..*

There is no clear reason to constrain business identifiers out of the gp connect profile, and there are possible use cases for need for business identifiers (such as eRS UBRN)

@jackiebarnes could you add this to the changes for data standards

**Comment by james-answer** [comment]
The change has been discussed and agreed with data standards to make cardinality 0..* as per base fhir resource. No change is required to spec so closing the issue.
