### ISSUE TITLE
From [openhealthhub.org] Appointment type coding

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#253]
From https://www.openhealthhub.org/t/gp-connect-appointments-appointment/384:

Appointment.type.coding has example binding to SNOMED-CT, but this becomes a de facto required binding as coding.system is fixed. The underlying valueset is a) copyright (which creates potential licensing problems), b) requires mapping from existing coding systems.

The bound ValueSet does not map well to the use case (i.e. all appointments are 408443003	General medical practice) and can't differentiate the range of appointments used within a GP practice (e.g. GP face to face consultation, Nurse well-person clinics, Flu vaccs drop in sessions, telephone consultations, home visits etc). Existing GP systems allow users to configure their own Slot types - how will these be reliably, robustly and usefully mapped to the bound ValueSet?

**Comment by briandiggle** [comment]
Appointment.type to align with base appointment profile. Currently Coding is profiled out. Also include guidance in the specificaiton to indicate that normal gp appointments should use SNOMED CT code 394814009

@jackiebarnes Another change for data standards

Close when both spec and profile updated.

**Comment by james-answer** [comment]
Decision made when going through changes with data standards to go back to the base fhir appointment and change the cardinality back to the base fhir appointment profile cardinality. Data standards are making this change to the profile.

Brian and I agreed that no change is required to the specification as it currently does not pick out any specifics for appointment type and will now match the base fhir appointment resource so no additional information needs added, therefore closing this issue.
