### ISSUE TITLE
Amend an appointment

### ISSUE THREAD

**Issue by Dunmail** [nhsconnect/gpconnect#256]
Spec says provider must raise an error if `any appointment details other than the appointment reason field are attempted to be updated.`

Spec also says: `Choose an Appointment resource and update it’s description and/or comment details.`

These are inconsistent.

**Comment by james-answer** [comment]
The spec has been updated to allow amendment of Comment, Description and Reason. The Cancellation Reason can also be updated if the appointment has already been cancelled. The spec should now be consistent.

Release in Appointments 1.0.0-rc.1 on 22/09/17.
