### ISSUE TITLE
Amend an appointment

### ISSUE THREAD

**Issue by Dunmail** [nhsconnect/gpconnect#257]
Documentation error: `The typical flow to cancel an appointment is:`

Should be: `The typical flow to amend an appointment is:`

**Comment by briandiggle** [comment]
Thanks Dunmail - this has been noted before in #191  and will be released with Appointments1.0.0-rc.1

**Comment by james-answer** [comment]
This has been fixed and release in Appointments 1.0.0-rc.1 on 22/09/17.

https://nhsconnect.github.io/gpconnect/appointments_use_case_amend_an_appointment.html#use-case
