### ISSUE TITLE
Appt Mgmt - IG - Spec Uplifts

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#265]
Seeking IG SME view on appropriateness for this capability of applying patient dissent;

Uplifts to spec will  be required - Find a Patient - to refer explicitly to relevant IG controls - as with AR HTML Impl Guide:

patient dissent to share
PDS S-Flag

**Comment by jackiebarnes** [comment]
Patient Dissent should NOT be applied  given that it's only available at the patient's registered GP Practice whereas Appt Mgmt is precisely about appts beyond the registered practice;  

also primary use case is administrative whereas Patient Dissent is about sharing the medical record;  

Did result  in a decision to restrict Retrieve/Amend a Patient's appointments to future ones rather than historic, given IG SME view that viewing historic appts falls within the 'viewing the medical record' arena, in which case dissent then must be taken into account;  all relevant pages amended, following agreement at Decision Log mtg of 27/11/17 to amend the spec to reflect this

**Comment by jackiebarnes** [comment]
Have included in new Appointment Mgmt IG page, also decided to create a section in Design Decisions page to reflect this - ie Patient Dissent NOT applied

Now assigning to Foundations - assuming that Find a Patient Use Case needs to call  this out?

**Comment by james-answer** [comment]
Should it not be a generic rule in foundations like it is in appointments as there is both "Find a patient" and "Read a patient" capabilities which would need details specifying for not using patient dissent?

**Comment by jackiebarnes** [comment]
Do we need therefore an IG page in Foundations?  Can you create me one and I'll populate it

**Comment by james-answer** [comment]
I have added an foundations IG page.

**Comment by jackiebarnes** [comment]
Seems to me the Retrieve, Amend, Cancel Patients Appointments should have the 'patient dissent does not apply' - can you confirm?

**Comment by james-answer** [comment]
Is this not covered by the general guidance that patient dissent does not apply to any of the appointment mangement capability pack?

**Comment by jackiebarnes** [comment]
That's correct - lost sight of this;   I suppose I'm wanting to minimise the chance of it being missed if itemised with the other actual tech spec items;

see my comment above - ie does the Provider know that its receiving a Foundations API for the purposes of eg Appt Mgmt capability?

**Comment by james-answer** [comment]
I think it should be spelt out seperatly for the foundations on the new Foundations IG page as developers might not look at the appointment pages before they develope the foundations pages. I just think we should go it at the generic foundations and genreic appointment level rather than any specific api use case level.
