### ISSUE TITLE
Appointment Chaperone - Include RelatedPerson reference in appointment.participant

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#267]
To meet potential requirement to support a chaperone, include the original relatedPerson, as well as the other base FHIR elements references in the GPConnect-Appointment Participant.actor element

**Comment by james-answer** [comment]
This requires change by data standards. Once updated the profile change needs adding to the appointments release notes.

**Comment by jackiebarnes** [comment]
Discussing with Data Stds Wed 4/10/17

**Comment by james-answer** [comment]
The latest version of the appointment profile now allows the actor to be a reference to any of the base fhir reference types allowed for the actor.
