### ISSUE TITLE
Participant Status - Book Appointment

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect#268]
The Participant Status description is potentially incorrect - the description states - 'Participation status of the Patient', this should be amended to 'Participation status of the Participant' (as the status can refer to the Practitioner and Location also)

**Comment by briandiggle** [comment]
@AndrewGuiseley Could you clarify exactly where this problem is found in the spec?

**Comment by briandiggle** [comment]
@james-answer indicates that this is in the gpconnect-appointment-1 profile

![image](https://user-images.githubusercontent.com/7500963/30750809-5834de02-9faf-11e7-9e64-9eb2674b26ac.png)

**Comment by james-answer** [comment]
This requires change by data standards. Once updated the profile change needs adding to the appointments release notes.

**Comment by jackiebarnes** [comment]
Discussing with D Stds 4/10/17

**Comment by james-answer** [comment]
This has been changed in the latest release of the Appointment Resource.
