### ISSUE TITLE
Search for free slots SSP-Interaction Id is incorrect

### ISSUE THREAD

**Issue by Chrisjobling** [nhsconnect/gpconnect#270]
Currently, the Ssp-IntercationID is listed as urn:nhs:names:services:gpconnect:fhir:operation:gpc.getschedule

This is now incorrect as the gpc.getschedule operation has now been changed to a GET endpoint, so should, therefore, be a SEARCH. 

The issue is located : http://gpconnect.netlify.com/appointments_use_case_search_for_free_slots.html

**Comment by james-answer** [comment]
This does need updating as it should now be:

urn:nhs:names:services:gpconnect:fhir:rest:search:slot

Do we need to have anything updated by the Spine team for the data sharing within the SSP?
