### ISSUE TITLE
Improve API use case layout

### ISSUE THREAD

**Issue by rpugmire** [nhsconnect/gpconnect#271]
Regarding the new [Search for free slots](https://nhsconnect.github.io/gpconnect/appointments_use_case_search_for_free_slots.html) page, we should align the spec layout to the existing REST API specs for consistency, e.g. [allergies](https://nhsconnect.github.io/gpconnect/accessrecord_rest_structured_data_allergyintolerance.html). Specifically missing but useful is the table of params and data types supported near the top.

**Comment by james-answer** [comment]
Updated format to match the format of the Access Record REST pages.
