### ISSUE TITLE
Uplift Spec on HTML Impl Guidance On Section Default Date-Ranges

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#273]
Make clear that the following:

Per Section Default Time Frames

Section Default Time Frames SHALL be configurable, to be easily amendable if required in response to FoT feedback

is a Provider requirement

**Comment by devmikey** [comment]
Are we doing something similar for other ranges e.g Last X encounters?

**Comment by RiChallinor** [comment]
@tim1ford has this been done / is it needed still?

**Comment by tim1ford** [comment]
Uplifted text to ensure clarity over this being a Provider requirement.

**Comment by tim1ford** [comment]
Date range information added at section/subsection level.
