### ISSUE TITLE
Register Patient operation allows deceased date to be populated

### ISSUE THREAD

**Issue by haydenanswer** [nhsconnect/gpconnect#275]
From the (Foundations 1.0.0-rc.2) spec:

> Where the gender, name, birth date or deceased date are available these SHALL be supplied (as indicated by the Must-Support FHIR property)

See: https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html

Registering a Patient with the deceased date populated should not possible.

**Comment by james-answer** [comment]
Fixed as part of Foundations RC.3
