### ISSUE TITLE
Appointment - Data attributes BookingOrganisation & Created Date

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#278]
Pending full agreement at DL Mtg, ticket 199 (includes validated user stories)

Create new elements on GPConnect-Appointment-1 resource to record the organisation booking the appointment, and the date of booking:
    bookingOrganisation = String value extension containing Consumer Org Name  (meaningful to Provider), ODS Code, followed by Telephone Number 
    bookingdate = base FHIR element 'created'

Provide specification content to describe how Consumer should populate, then how Provider should store - in appropriate database field, and return in View Appts interaction

**Comment by devmikey** [comment]
What will happen if initiated in the future through a patient app and not by an organisation on behalf of patient?

**Comment by briandiggle** [comment]
In a future patient facing implementation of appointment booking, the agreed changes to support patient facing requests include indication in the JWT that the request is a PFS use case - i.e. from the patient. The provider system could then mark the appointment as "patient booked" according to their own processes/data model.

**Comment by devmikey** [comment]
Is the booking organisation left empty in this scenario

**Comment by briandiggle** [comment]
My assumption is that the bookingOrganisation extension will be cardinality 0..1 - @jackiebarnes can you confirm this assumption?

Therefore in a PFS use case, would be blank.

**Comment by james-answer** [comment]
The created date will also have to be an extension as the "created" element is not present in DSTU2, it only appears in STU3:

https://www.hl7.org/fhir/DSTU2/appointment.html
https://www.hl7.org/fhir/appointment.html
