### ISSUE TITLE
Spec content which should be removed

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#284]
The following things are stuff I have noticed in the spec which are not used and not kept up todate so should probably be removed:

* https://nhsconnect.github.io/gpconnect/overview_workshops.html - Out of date
* https://nhsconnect.github.io/gpconnect/development_deliverables.html - What does this page add?
* https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#fhir-timelines - references STU3 fhir as not released yet which is no longer the case.
* https://nhsconnect.github.io/gpconnect/development_api_volume_and_performance.html#external-documents--policy-documents - Still says TODO
* https://nhsconnect.github.io/gpconnect/development_api_non_functional_requirements.html#external-documents--policy-documents - Still says TODO
* https://nhsconnect.github.io/gpconnect/support_faq.html#why-are-you-not-using-the-latest-version-of-fhir-dstu3 - Refers to STU3 being in the future
* https://nhsconnect.github.io/gpconnect/support_communications.html - Most of the things reference on this page are not used or kept up todate so this page should probably be removed.
* https://nhsconnect.github.io/gpconnect/news.html - the news page is out of date and not maintained so should either be removed or a better process of updating should be worked out.

**Comment by jonnyry** [comment]
Agreed.

**Comment by jonnyry** [comment]
Removed altogether:

* https://nhsconnect.github.io/gpconnect/overview_workshops.html
* https://nhsconnect.github.io/gpconnect/news.html

Removed parts:

* https://nhsconnect.github.io/gpconnect/support_communications.html - News, Mailing list (not used), Twitter (not used)
* https://nhsconnect.github.io/gpconnect/support_faq.html#why-are-you-not-using-the-latest-version-of-fhir-dstu3 (removed question on STU3)
* https://nhsconnect.github.io/gpconnect/development_api_volume_and_performance.html#external-documents--policy-documents (removed empty documents table)
* https://nhsconnect.github.io/gpconnect/development_api_non_functional_requirements.html#external-documents--policy-documents (removed empty documents table)

Leaving page for now (logging separate issue regarding whole organisation of sidebar):

* https://nhsconnect.github.io/gpconnect/development_deliverables.html
