### ISSUE TITLE
Access Record capability naming

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#292]
The naming of Access Record HTML and Access Record REST is not consistent -

* HTML refers to the formatting of the content
* REST refers to the architectural style

Recommend that Access Record REST is renamed to Access Record Structured

**Comment by adamjlees** [comment]
This is not consistent with the maturity model.  Access Record REST refers to Stage 3: "unbundled" access to FHIR resources.  Access Record Stage 2 is the operation with returned structured resources in the bundle.

**Comment by jonnyry** [comment]
Renamed as per change in maturity model proposals.
