### ISSUE TITLE
Ssp Headers - Case inconsistency

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#3]
We noticed an issue with the specification for the Spine Security Proxy headers. There is a slight inconsistency with the case of the "Ssp" and "ID" within the header names. JavaScript is case sensitive so having variations in case within the specification may cause compatibility issues therefore the specification should be consistent.

In the documentation the case for the header names is different on the implementation guide to all other references in the specification. It would be good if the implementation guide could be changed to be consistent with the other areas of the specificaiton.

Camel Case:
https://nhsconnect.github.io/gpconnect/integration_spine_security_proxy_implementation_guide.html

Upper Case:
https://nhsconnect.github.io/gpconnect/integration_spine_security_proxy.html
https://nhsconnect.github.io/gpconnect/accessrecord_use_case_retrieve_a_care_record_section.html
https://nhsconnect.github.io/gpconnect/tasks_use_case_send_a_task.html
https://nhsconnect.github.io/gpconnect/appointments_use_case_retrieve_a_patients_appointments.html

Thanks

**Comment by michaelmeasures** [comment]
5b81496efde0fbf11506e65059a3b81481f2bf66 fixes the headers to be in camel case (i.e. Ssp) as per the original implementation guidance.
