### ISSUE TITLE
RegisterPatient - Clarify Address.use element population

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#305]
The RegisterPatient call accepts a patient resource, including the patients address, which is to be recorded in the GP system.

GP systems (and PDS) record address with an address type (home, temporary, work etc), therefore we should be clarify and be explicit around population of the Address.use element.  I.e. make mandatory and specify which elements of the valueset are acceptable to use to allow the GP system to record the address correctly.

**Comment by james-answer** [comment]
Is that not really up to the consumer and provider to decide based on what he patient tells them. Say they are on holiday it might be a temporary address. If they have moved but the records have not been updated on Spine it might be their home address. If we restrict the value which can be sent we could be forcing the consumer or provider to populate the field incorrectly for the scenario.

What is the risk around leaving the field open for use by consumers or providers?

**Comment by timfordta** [comment]
Updated gpconnect/pages/foundations/foundations_use_case_register_a_patient.md:

The following data-elements SHOULD be populated if available:
- Within the patient resource of the `registerPatient` parameter:
  - the `telecom` element SHOULD be populated
	- the consumer SHALL NOT populate the `telecom.use` value with `old`
	- the consumer SHOULD populate only one `telecom` per `telecom.use` value

  - the `address` element SHOULD be populated
	- the consumer SHALL NOT populate the `address.use` value with `old` OR `bad`
	- the consumer SHOULD populate only one `address` per `address.use` value
	- the `address.use` value `home` SHOULD be mapped to PDS Address Use `HP` (Primary Home)

**Comment by timfordta** [comment]
Agreed that no .use values of 'old' or 'bad' should be populated, and only a single value per other use be allowed.

**Comment by james-answer** [comment]
Changes have been made and look good so closing issue.
