### ISSUE TITLE
Slot service type

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#309]
There was a conversation on how a consumer would differentiate on what sort of appointment should be booked into which slot. This is currently possible using the service type but the elment is optional and the potential choices for value are large so there would be no consistency.

The provider systems currently do not support adding a type to slots within the appointment booking system (according to all the people GP Connect has talked to). We found it was done on a practice by practice basis, some colour their appointment book to sepreate out the slot types, some use text as a slot type description.

We have had feed back that even a bit of text saying what the slot type is would be useful for consumers to choose an appropriate slot for the appointment they are trying to book. We also had feedback that if this information was conveyed, practices would be more willing to open up their appointment book.

Suggestion is to make serviceType mandatory, also making the text element mandatory to force providers to send through a slot type atleast as text. Guidance could be uplifted to encourage people to use a standard list of identifier types.

**Comment by Dunmail** [comment]
@james-answer: Our experience of doing this suggests that:
a. as practices configure their own slot types and descriptions, identical text may represent very different appointment types
b. some consumers book patients into any slot, irrespective of the supporting information provided.
c. practices vary widely in their use of slot types as they have evolved different ways of working over the years. Whilst standardisation would be desirable, I'm not sure that practices will embrace this enthusiastically ...

Out of interest, do the GP Connect team not have access to demo instances of the principal systems?

**Comment by james-answer** [comment]
@Dunmail Thanks for the feedback, it is a good point that even requiring text does not guarantee that we would get anything useful that consumers could use.

In GP Connect we are working closly with the providers, so even though we do not have our own access to the principal systems we do have the oportunity for the providers to show us how their systems work if we need them to. We also go out and find out how people actually use the systems as this can be different to how it is intended to be used.

**Comment by jackiebarnes** [comment]
Don't think providers could populate Slot type (DSTU2) by code  value;  the text could be of value to consumer end-user if populated by GP Practice meaningfully

**Comment by james-answer** [comment]
Slot "type" from DSTU2 has become "specialty" in STU3.

**Comment by james-answer** [comment]
As part of #315 for specifying searchFilters we will be engaging with providers, consumers and practices, this may be an oportunity to get providers and consumers to implment a common list of slot types.

If we work with providers and consumers to make it easy for their users to setup the slots with the new types it might encourage them to use it over their current system/processes. Maybe allowing some of the feature they use now to differentiate slot could be brought across to the new functionality such as colouring slots or setting the type by schedule might help transition people.

If we use the standard "specialty" valueset and talk to the people who setup the appointment books then we may get a prefered subset which we can advise providers and consumers use but allow the full list to work for edge cases.

**Comment by devmikey** [comment]
I agree. So how and where do we start this conversation. Openhealthhub?

**Comment by james-answer** [comment]
A resoulution to this github issue will not be achieved by this release so it is going to be moved into the next release when hopefully #315 will have been resolved and there may have been an agreement made on this aswell.

**Comment by jackiebarnes** [comment]
I am doing work around this Jan/Feb 2018 to produce a recommended minimum requirement set ......

**Comment by jackiebarnes** [comment]
See #354 for agreed finalised spec changes
