### ISSUE TITLE
General guidance issues

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#310]
The following pages contain dates or text which are out of date, we need to establish correct dates or re-word to not mention specific dates:

https://nhsconnect.github.io/gpconnect/overview_first_of_type.html#fot-timelines - FOT Nov 2016?
https://nhsconnect.github.io/gpconnect/overview_first_of_type.html#fot-tranche-2--3-selection - early 2017?
https://nhsconnect.github.io/gpconnect/overview_glossary.html#direct-patient-care - The link to definition of direct patient care does not work and it is not obvious what it should point to.

**Comment by briandiggle** [comment]
Made some minor amendments to the FoT page to deal with immediate concerns around out of date content. Really this page needs re-writing by our PM who is overseeing all FoT engagement.

Removed dead link re: direct care definition. IMO Caldicott review reference is sufficient.

**Comment by james-answer** [comment]
The technical architect is currently working through the spec to fix a number of these issues. The out of date content has been removed so this can probably be closed as the remaining work will be covered off by other tasks.
