### ISSUE TITLE
Clarity on the status of which capability packs are ready for consumers to build against

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#312]
Make clear which capability packs are ready for consumers to build against and their current status (Live, in first of type, in development, not started).  Capability packs still in development will not be signed off for clinical safety, IG and will change - therefore consumers should not be considering or starting development against.

**Comment by adamjlees** [comment]
Current status should be reflected in the "alpha", "beta" and "rc" release labels, but use of these on the capability packs needs better consistency across packs and bringing in line with our stated approach:
https://nhsconnect.github.io/gpconnect/design_product_versioning.html#pre-release-labels
https://nhsconnect.github.io/gpconnect/design_product_versioning.html#maturity-levels

There is a warning on the home page 
"This site is provided for information only and is intended for those engaged with NHS Digital in First of Type activities, other parties are advised not to develop against these specifications until a formal announcement has been made."

**Comment by briandiggle** [comment]
I think it would be very beneficial to tie versions of the api (release packages of the spec) to releases of demonstrator and provider test suite which align to these versions.

**Comment by briandiggle** [comment]
Each capability pack home page has the following call out box:

_To do: This capability pack is published as a work in progress version and as such is subject to change. It has been published to show the direction of travel and to serve as a discussion document for parties involved with the implementation and consumption of GP Connect FHIR based APIs._

I would suggest changing wording as follows:
Consumers considering developing client applications which make use of this capability should be aware that 

- The version is this capability back as defined in red reflects the current maturity of the API and associated provider implementations. Please refer to [Product Versioning](https://nhsconnect.github.io/gpconnect/design_product_versioning.html) for further clarity. 

- The following provider implementations exist for this capability: xxx FoT, xxx in development, etc

**Comment by adamjlees** [comment]
I suggest this ticket has been superseded by the introduction of unified spec versioning.
