### ISSUE TITLE
Move Content On ARHTML Impl Guide to 'Core'

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#313]
Suggest that Common User Interface Guidance, Patient Banner, Min Display Resolution, Demographic Cross-Checking moved from the above to somewhere in the core 'Development Guidance' pages, as these will apply to all capabilities

**Comment by adamjlees** [comment]
Display resolution is only relevant to HTML as that is pre-generated from provider system.  For structured, and appointment functionality, the developers of the consuming system have full control of the UI design.
Patient banner guidance applies specifically to displaying above HTML content.  Although it does not preclude banners in UIs consuming other capabilities.

**Comment by james-answer** [comment]
I agree with Adam about the points he has responded to. I think most of the thing listed in the origional issue should be in the Access Record section as they require the providers to format their response to conform to a specific format which should make responses from different providers mostly consistent in format.

For Appointments, Foundations and Structured the consumers will most likely consume the data into their system and then display the information using their standard user interface, in the same way as they do with with native data from their system. Therefore I don't think anything to do with displaying information is relevant for any other sections than HTML.

It might be worth adding information around Demographic Cross-Checking to the core part of the spec as it is probably relevant to Register Patient and some foundation such as patient search.

**Comment by jackiebarnes** [comment]
Added section on Demo Cross-Checking to Cross Org Audit & Prov page

**Comment by jackiebarnes** [comment]
Can see that Demo Cross-Checking has been added to Common API guidance page
