### ISSUE TITLE
Search for free slot filters - for UC Use Case

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#315]
Additional guidance around possible filtering within the "Search for free slots" interaction was added in "Appointments rc.3" release, github issue: https://github.com/nhsconnect/gpconnect/issues/279

The spec was updated to highlight a need for filtering and enable filtering for Urgent care, when the requirements had been finalise, without causing a breaking change to the specification.

At the point of release for "Appointments rc.3 " the `searchFilter` requirements had not been finalised, consultation was needed with providers and consumers to decide on valuesets for the identified filters.

This github issue is to record the additional work and changes required to finish specification of the `searchFilter` within "Search for free slots":

* Work with providers and consumers to create meaningful valuesets for the "Consumer Type", "Disposition code" and "Service-ID" search filters.
* Updated the spec to reflect the created valuesets with examples.
* Updated wording to reflect GP Connect expectations around when and how to implement the filters for both consumers and providers.

**Comment by jackiebarnes** [comment]
I am doing work around Jan/Feb 2018 to produce recommended  minimum viable requirement set

**Comment by jackiebarnes** [comment]
See #354 for agreed and finalised spec changes
