### ISSUE TITLE
nominatedPharmacy

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#319]
Has this added element been included in the Foundations Release Notes - patient element?

**Comment by james-answer** [comment]
No specific elements have been included in the release notes as the profiles are bing updated from dstu2 to dstu3. When providers implement the STU3 profiles they should explore what elements they have and can populate.

**Comment by james-answer** [comment]
Suggested to Andrew as a manual test as it is covered by the general guidance that if a provider has the information theye should include it in the profile.
