### ISSUE TITLE
Further Guidance for other System Req Compliance

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#324]
May need to add further guidance on expectations of Consumers and Providers that their associated workflow at either end of a GP Connect interaction should comply with other 'general' reqs - eg application of Flag checking etc - FGM, CP-IS;  see HDL-206

**Comment by james-answer** [comment]
I think this goes to far outside the specification of the GP Connect API, we have included guidance when it is directly related to the API such as sensitive flags but we should not be including additional guidance around processes which should be done with or without the GP Connect API.

**Comment by james-answer** [comment]
This outside of the scope for GP Connect so should not be included in our specification.
