### ISSUE TITLE
Appointment Booking org clarification around expectations

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#329]
The specification and TOM need updating to specifically state that the appointment booking organization extension should only be the organization making the appointment booking. This relates to the discussions around provider worries that an organization might book an appointment on behalf of another organization, so the booking organization might not reflect the organization actually booking the appointmenet.

**Comment by james-answer** [comment]
Looking at the current specification, on page - https://nhsconnect.github.io/gpconnect/appointments_use_case_book_an_appointment.html#payload-request-body

there is already the wording:
- _the bookingOrganisation extension referencing a contained organization resource within the appointment resource._
  - _the contained organization resource SHALL represent the organization booking the appointment._

JB agrees that this combined with the new wording to put in the TOM will suffice therefore no additional changes to the specification will be included.

The TOM changes need finalising before the git issue can be closed.

**Comment by jackiebarnes** [comment]
Have added this as an explicit requirement in latest draft TOM - Ref ID = 'GPC-BPA-01';
