### ISSUE TITLE
CC-GPC-Patient STU3 Profile - Name 'use value' - change from 'Usual' to 'Official'

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#331]
following Interopen review in Dec 17, Patient Resource Name element 'use' value should now be 'Official' to signify the name held on PDS, rather than 'usual' as this is now in the CareConnect-Patient profile.

@jlellison  - when you've implemented this, please could you confirm in a Comment and move the ticket on the Git project KanBan to 'D Stds Completed';

**Chg request to Data Stds that STU3 CC-GPC-Patient-1.Name**

-  mandatory slice should have additional wording in Description/Constraints column to indicate the PDS mapping for Fixed Value of 'Official'

- further Name slices should have the value 'Official' removed from the value set, such that there will only be one Name with value of 'Official'

- the other mappings of PDS Name values to the FHIR equivalents to be included in the value set description

**Comment by jackiebarnes** [comment]
following discussion, checking again with Data Stds re 1. whether the 'Usual' value should be used rather than 'Official', given that this is the PDS designation of the name we are using - and the profile comment wording should explicitly reflect this, and 2. that other slices of 'Name' should not include the value - either 'Usual' or 'Official' - whichever becomes the PDs representation

Following the question re persistance of another name instance, (if only one can be stored by Provider) - eg from the Consumer which is not the same as a Provider PDS-traced name  - the decision was taken that we should only require the Provider PDS  name to be stored

**Comment by jackiebarnes** [comment]
Confirmed with Data Stds:
this change has been ratified by InterOpen group, so the mandatory slice in CC-GPC-Name should now have the Fixed Value of 'Official' instead of 'Usual'

**Comment by jlellison** [comment]
Can you confirm you are happy for this to be a minor version change? So the new version will be 1.1.0 active.

**Comment by jackiebarnes** [comment]
Although this would be a breaking change and hence justify a major version change, because no-one has implemented it yet, we can stick to the minor version change.

**Comment by Dunmail** [comment]
@jackiebarnes: Black Pear **have** implemented it ... we can cope with the change though ...

**Comment by jackiebarnes** [comment]
@Dunmail - ah thanks for the correction.  Yes - we do need to bear in mind that we're not fully sighted on all usage out there.

**Comment by Dunmail** [comment]
@jackiebarnes  No problem - we're habitual early adopters and have got used to building on loose foundations ;)

**Comment by jlellison** [comment]
Version 1.1.0 active released https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1

**Comment by james-answer** [comment]
@jlellison and @jackiebarnes Thanks for updating the profile, I noticed that we have updated the slice to be 'official' rather than 'usual' but 'official' is still an option for use on the second name slice within the Patient resource.

Should the 'official' use option be removed from the second name slice as the patient should only have one official name?

**Comment by jlellison** [comment]
Hi @james-answer we can't remove a value from a required ValueSet. But have added a comment to state that there should only be one 'official' name.

**Comment by jackiebarnes** [comment]
@Dunmail  - Would it be possible to have a telephone chat about Cross-Org Appointment Booking & Appt Avail Control?

**Comment by Dunmail** [comment]
@jackiebarnes : Of course - happy to chat - can you get hold of my phone number?

**Comment by james-answer** [comment]
@jlellison Is it possible to remove the word 'official' from the human readable profile without removing it from the valueset?

**Comment by jlellison** [comment]
Hi @james-answer, whilst that field is editable so we could remove that value from the human readable profile, we would not remove a code that exists in a required ValueSet as it is misleading.  We would add a statement in the guidance like we have done in the latest release of Patient.

**Comment by james-answer** [comment]
@jlellison We feel that doing what you describle, ie removing 'official' from the human readable second name slice would remove the chance of confusion. We agree it should stay in the valueset as this is used for both slices.
