### ISSUE TITLE
Approved Cryptographic Algorithms Good Practice Guidelines

### ISSUE THREAD

**Issue by Mhitchins** [nhsconnect/gpconnect#332]
At the bottom of development_api_security_guidance.md there's an External policy documents section with a reference to "Approved Cryptographic Algorithms Good Practice Guidelines | NHS Digital | v4.0 | 13/07/2016".

Should I link to this document? If so, where is it (I couldn't find it) and is v4.0 the latest version?

**Comment by jonnyry** [comment]
Yes please - though I couldn’t find it either!

I will drop an email to our security colleagues.

**Comment by jonnyry** [comment]
Sent email to Matt Wyatt to attempt to locate the documents.

**Comment by jonnyry** [comment]
https://nhsconnect.github.io/gpconnect/development_api_security_guidance.html#external-policy-documents

**Comment by jonnyry** [comment]
WES is here:  https://digital.nhs.uk/spine/technical-information-warranted-environment-specification
