### ISSUE TITLE
Data Model Chg Mgmt - using Git and BA/TA ownership

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#334]
a)	Following through on the above, and having discussed with Dave and Jen yesterday re how best to record, communicate and manage FHIR changes across our team and Data Standards, - see bottom of email thread below -  we’ve agreed that in the first instance Data Standards is happy to use the GP Connect Git Issues repository, replacing email collaboration on FHIR changes  to determine whether Git is a good tool for the job.

Have therefore:

•	Created a ‘FHIR Resources Changes’ project 
•	Attached the first Git issues ticket to this - #331, which is also still attached to the appropriate Foundations release Git Milestone 
•	Assigned Jen as well as James to the issue, given the FHIR as well as Spec uplifts required
•	Created some Kanban Columns which are part of the Git Project tooling

See Kanban - https://github.com/nhsconnect/gpconnect/projects/7

None of this is fixed in stone, simply trying something different which may improve collaboration and management for GP Connect and Data Stds, but which may also help improve wider workflow around FHIR going forward.

b)	Thinking about the bigger picture around FHIR Resources, which constitute in effect our solution business data model, I think we also need a BA/TA/Developer/Solutions Assurance common understanding and agreement as to 

i.	documentation assets re FHIR resources and where and how these assets are used and maintained.  

It seems to me we have:
1.	the fhir.nhs.uk repository which is the key source of truth, referenced by and to which the Developer Portal specifications must be aligned 
2.	FHIR Structure Definition spreadsheet-based repositories which hold Provider system mapping and which Solution Assurance rely on to inform their activities;  

I think that ‘2.’ needs to have possibly more formal recognition and therefore intention going forward, based on the current situation that has evolved.

ii.	Understanding as to overall ownership of Programme ‘interface’ to Data Standards/InterOpen work;  Is this required – and if so is this currently Pete, or is Pete’s remit only Structured Data Resources, in which case this activity also needs to be recognised by either BA or TA involved in ‘Core’ as well as individual business capabilities

Welcome everyone’s comments/observations on the above.

**Comment by briandiggle** [comment]
b) i. point 1:
By "Developer Portal" I assume we mean https://developer.nhs.uk/apis/gpconnect/ rather than https://nhsconnect.github.io/gpconnect/?

**Comment by jonnyry** [comment]
Yes very much welcome using Git issues and the Kanban board to track work requests to Dave and Jen, and to track and record subsequent comments.

**Comment by jackiebarnes** [comment]
Process now up and running - adopted
