### ISSUE TITLE
Update metadata interaction id for STU3 version to allow identification seperate to DSTU2 version

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#335]
We need to update the metadata InteractionId for the STU3 release so that it can be differenciated within SDS from the DSTU2 InteractionId.

DSTU2 : urn:nhs:names:services:gpconnect:fhir:rest:read:metadata
STU3 (Suggested): urn:nhs:names:services:gpconnect:fhir:rest:read:metadata-1

We will need to do a hot fix to the spec, change interaction ID on api use case page and add to release notes.

We need to talk to environment and SSP team to ask them to add the new InteractionId to the SSP tooling and datasharing configuration stuff.

**Comment by james-answer** [comment]
The plan is to go to metadata-1 as a fix for the issue of metadata going from DSTU2 conformance profile to the STU3 CompatibilityStatement. When the Access Record RC.6 is released and we go to one spec version we should bump all the interactions IDs so they have the suffix -1. This can be done as a seperate ticket.

**Comment by adamjlees** [comment]
Do we have anywhere in spec or code (SSP) that makes the assumption that the interaction ID without a version suffix refers to either a specific version number or "latest"?

**Comment by james-answer** [comment]
There is a bit in the spec that it assumes it should be 1 if it is not present. This is a temp fix for the issue of being able to differentiate between the DSTU2 and STU3 metadata endpoints within the SDS.

**Comment by james-answer** [comment]
The new interactionId is going to be added to the GPC Foundations message set next week so should be available to be used when providers have completed their development and wich to test.

I had a look at the "SHALL be assumed to be 1" requirement and it only appears to be in relation to the major version included in the provider URL. There is no mention of interactionIds without a suffixed version number being assumed to be 1.

**Comment by james-answer** [comment]
Martin has added the new interaction id to the foundations message set so closing the gitissue.
