### ISSUE TITLE
Appt Avail Mgmt - Spec Changes

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#354]

**Comment by jackiebarnes** [comment]
1.Complete new page on Provider reqs - Slot Availability Mgmt - all business rules requiring mandatory use of Practitioner Role, Delivery channel values, max slots bookable .....

2. Search Free Slots:  
    a) Uplift wording on SearchFilter section to reflect 
       Booking Org ODS Code
       Booking Org Type value set 
  
    b)  create link to Slot Avail Mgmt page and reference that returned slots should match GP Practice end-user slot avail configuration

**Comment by james-answer** [comment]
For the location, me and Jonny discussed it and we think we should just specify that the location contains the Name and address, we should not include any changes for the display text on the reference element as this will make it inconsistent with the rest of the specification.

**Comment by james-answer** [comment]
I have updated the search for free slots page with the new search filters.

**Comment by jackiebarnes** [comment]
@briandiggle @james-answer Have done the Prov Reqs page;  please review

**Comment by james-answer** [comment]
I have updated the wording a bit and linked to the valuesets, where they should appear when they go live and linked to other relevant pages.

**Comment by james-answer** [comment]
All the requirements set out on this ticket have been covered with the page updates that have been done so closing off this ticket.
