### ISSUE TITLE
Schedule Branch Surgery (as opposed to main Practice location) Availability

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#355]
UC consumer systems currently don't necessarily have available from GP systems the location of Schedules/Slots if these are at a branch surgery, rather than the main practice.

Solution - Uplift Spec:

a) GPC Schedule has a mandatory Location requirement – will mandate in business rules that this is populated with text of name & address of either the GP Practice where there are no branch surgeries, OR the branch surgery including ODS Site Code.

b) Display Text on the reference to Location resource within the Schedule resource SHALL contain same name and address details of either the GP Practice where there are no branch surgeries, OR the branch surgery including ODS Site Code.

To enable more targeted matching of available appointment slots at a patient's preferred branch surgery:

Patient’s preferred branch surgery on Patient resource, Registration Details extension to be made Must Support and hence required to be populated;  UC system could then use GPC Find Patient against patient’s registered practice to find logical id of preferred branch surgery;  this then used to match against logical id of location returned in Schedule/Location via Search Free Slots, allowing Consumer sys to identify slots at patient’s preferred branch surgery

**Comment by james-answer** [comment]
Talking to Jonny we agreed that the Display text on the reference in the Schedule to the Location is not nessersary as the Location is already mandatory, so we can probably skip doing b).

**Comment by james-answer** [comment]
Updated spec business rules to make clear the expectations around the location linked from the schedule.

**Comment by jackiebarnes** [comment]
@james-answer 
Shouldn't we call out the  'mandatory' cardinality of this  in the Search Free Slots page to support the section on the Slot Avail Mgmt page, given that it's not mandatory in the resource?

**Comment by jackiebarnes** [comment]
Related to previously:  Are the following reqs as aligned as they could be?  why shouldn't the preferred branch surgery of the patient be populated either with the GP Practice, or with the Branch Surgery if they have it?

Find a Patient:  **SHOULD** populate the preferred branch surgery within the registration details extension of the patient resource with a reference to a location resource which represents the patients preferred branch surgery including ODS Site Code where available OR the GP Practice where they are registered if there is no preferred branch surgery.

Slot Avail Mgmt:

Branch surgery location
The Schedule resource has a mandatory ‘Location’ reference within the actor element. The referenced location **SHALL be populated** by Provider systems with the name and address of the location where the appointment will take place. This will either be the GP Practice where there are no branch surgeries OR the branch surgery (including ODS Site Code where available).

**Comment by james-answer** [comment]
@jackiebarnes The mandatory requirement of the location on the schedule resource is called out within the search for free slot page.

I think we need some common resource population guidance pages for each of the resources. For example for all places where the patient resource is used the provider SHOULD populate the preferred branch surgery, if we create a common resource guidance page we don't have to have the same wording on each capbility.

**Comment by jackiebarnes** [comment]
agree that this would be a better idea - to keep 'one source of truth' to maintain, but if this common page is likely not to be read as much as individual API pages, feel that it's still also worth calling out specifically those elements that we know are serving a specific business purpose, as these pages represent for me the actual real tech spec

**Comment by jackiebarnes** [comment]
Shall we not make this extension element explicitly 'MUST SUPPORT'  - as was described in initial comment?

**Comment by james-answer** [comment]
I have added additional guidance within the search for free slots page to clearly state that the location reference within the schedule is for the location of the appointment, either a gp practice or branch surgery where there is one.

**Comment by jonnyry** [comment]
@jackiebarnes @james-answer is this still open?

**Comment by james-answer** [comment]
Changes have been made for location on schedule. Preferred branch surgery is must support and inherited but Jen is going to add the flag to the specific element to make it more clear.
