### ISSUE TITLE
Patient Resource - Preferred Branch Surgery

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#356]
To enable within the Consumer system more efficient identification of appropriate available appointment slots at a patient's preferred branch surgery:

Patient’s preferred branch surgery on Patient resource, Registration Details extension to be made Must Support and hence required to be populated; UC system could then use GPC Find Patient against patient’s registered practice to find logical id of preferred branch surgery; this then used to match against logical id of location returned in Schedule/Location via Search Free Slots, allowing Consumer sys to identify slots at patient’s preferred branch surgery

**Comment by jlellison** [comment]
Updated profile released to https://fhir-test.nhs.uk/ for review.

**Comment by james-answer** [comment]
Looks good, when these have been released to live we will close this github issue.

**Comment by jlellison** [comment]
Released to live.

**Comment by jackiebarnes** [comment]
@jlellison  Don't think this has been done:  Patient’s preferred branch surgery on Patient resource, Registration Details extension to be made Must Support and hence required to be populated

**Comment by jlellison** [comment]
Hi Jackie, this was done in the last release https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1 the Complex Extension for Registration Details has an S Flag next to it meaning it carries the must support flag.  This extension contains a slot with a Location reference with the description Location of usual branch surgery.  If anything further is required please let me know.

**Comment by james-answer** [comment]
We also have wording in the specification which says that the providers SHOULD populate the preferred branch surgery for Find a patient so that with the must support on the complex extension which filters down to the preferred branch surgery element this should be strong enough guidance/requirements.

**Comment by jackiebarnes** [comment]
@james-answer 
Is there alignment between the different spec items to meet the requirement for Providers to supply the patient's preferred branch surgery?

The business rules indicate that the Provider 'SHOULD' populate with either the pref branch surgery OR the GP Practice if there aren't surgeries;  
_why shouldn't this be a SHALL, _

The CareConnect-GPC-Patient-1 RegDtls ext is Must Support, therefore the Preferred Branch Surgery inherits this

This ext references a Location resource;  in this the identifier is 0..*, but there is only the ODS Site Code slice represented
_if the business rules state that this should contain either the pref branch surgery or the GP Practice -is the identifier only describing ODS Site Code sufficient given that 
a) even if the Providers system does recognize a branch surgery at the target practice which is distinct from the main pracitce, it will not be represented by an ODS Site Code
b) we have indicated in business rules that where there is only the main GP Practice at the target Org, then the pref branch surgery should be populated with the main practice details_

**Comment by james-answer** [comment]
We have aligned everything and put stronger guidance for the preferred branch surgery on the Search and Read a patient interaction specificaiton pages. These align and enable the stuff we need for urgent care location for preferred branch surgery.

I suppose we could make the SHOULD a SHALL, I am just aware that some of the providers don't have that information at the moment, but saying that they could populate it with the main organization details but there is a difference between the main organization being their surgery and not knowing the branch surgery so defaulting to the main surgery.

Even though the Location resource only has a slice for ODS Site code it does not restrict other identifiers being included. For example the Org ODS code could be included in the location resource. The main information urgent care are interested in are the name, address and logical ID so they can map the location to the location referenced from the schedule resource. We could add another slice for Org ODS code to the location resource as well if we wanted to.

**Comment by jackiebarnes** [comment]
Agreed that the 'Should' be changed to 'Shall';  

Changes to the Location Profile to more explicitly represent the main GP Practice tbc - whether by adding another slice for Org ODS code to the location resource as a 0..1, or by using the 'managingOrganization' element?

**Comment by jackiebarnes** [comment]
From James:
I think the managing organization is a link to a legal entity not a location so I would still say that the location should be used to identifiy the actual location of the main practice, and there is possibly a use case for having this location resource contain the organization ODS Code rather than having to do an organization read interaction on the reference in the location to get the organization resource so that you can get the Org ODS Code.
I think if we have a location referenced from the schedule and in the paitent resource then it should still be a SHALL, there is then no ambiguity where the consumer needs to go to get the information for name, address and national identifier.
I have made the change to the specification to include SHALL, I have also added guidance that the location should contain the Organization ODS Code when it is the main surgery and not a branch surgery.

**Comment by james-answer** [comment]
Agreed this has now been done.
