### ISSUE TITLE
Appointments use cases wording

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#360]
From Mike Hitchens:

There's a bit of inconsistency in the Appointments use cases. Retrieve, Search and Read all start with "This specification describes a single use case. For complete details and background please see the Appointment Management Capability Bundle." and that link just goes to the intro. Book, Amend and Cancel each have a 'typical flow', which seems a lot better.
 
I would suggest replacing the two sentences in the first three with a similar flow or, if there's no time to do that, a simple description of the use case.

**Comment by jackiebarnes** [comment]
Done;  @james to review

**Comment by james-answer** [comment]
I think Jackies changes do make this clear now.
