### ISSUE TITLE
Introduction Page - Wording uplifts

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#362]
Remove 'Roadmap' ref to more granular slot control

Amend wording in 'Note' box re UC cons to UC provider use case - make more explicit scope of GPC pgm etc

'Tip' box - creation of Schedule and Slot resources - out of scope - remove this box as content longer correct

Standardise on grammar conventions - use of Upper Case etc

**Comment by jackiebarnes** [comment]
@james-answer @jonn]
Made changes, please review specifically the 'GP practice apt slot availability' paras, and the Note on the FoT care setting deployments, vis a vis Nick's email

**Comment by james-answer** [comment]
Changes look good and I think you have covered off Nicks suggestion.
