### ISSUE TITLE
Design Decisions Page - Wording Uplift

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#366]
Search Parameters section
  -  Include in 'Selected', the booking organisation ODS code and organisation type code to be sent

**Comment by jackiebarnes** [comment]
@james-answer 
Please review Access to available slots and Search Parms secftions

**Comment by james-answer** [comment]
Changes look good and make requirements clearer. @jackiebarnes Good spot on removing the mention of appointment reason on the design decisions page.
