### ISSUE TITLE
Search Free Slots - Wording Uplift

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#368]
Typo in 'Enhanced Slot Filtering' Important box - 'outlined' rather than 'outline'

'Note' box - ....."Therefore slots found in the past can not - should be 'cannot'

@james-answer 
Should we be explicitly calling out as we have with date range, that Schedule/Slots returned should match the organisation/org type designation sent in the Search Filter?

**Comment by jackiebarnes** [comment]
Done - @james-answer  to review

**Comment by james-answer** [comment]
@jackiebarnes Maybe we should do, it is included on the appointment availability mangement page but I suppose it is not completly clear and we do want providers to actually use the schedule availability control to select which slots should be returned.

**Comment by james-answer** [comment]
Changes made by jackie look good and make the requirements clearer.

**Comment by james-answer** [comment]
This is in dev so will be release with final release of 1.1.0
