### ISSUE TITLE
Create Operation Definition for Structured - GPConnect-AccessStructuredRecord-1

### ISSUE THREAD

**Issue by tim1ford** [nhsconnect/gpconnect#371]
Create GPConnect-AccessStructuredRecord-1 using the parameter structure below:

<Parameters xmlns="http://hl7.org/fhir">
	<id value="b28bbed9-55b1-46ea-b019-b984a156decc"/>
	<meta>
		<profile value="https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-AccessStructuredRecord-1"/>
	</meta>	
	<parameter>
		<name value="patientNHSnumber"/>
		<valueIdentifier id="4569871235"/>
	</parameter>
	<parameter>
		<name value="includeResourceGroup:Medication"/>
			<part>
				<name value="timePeriod"/>
				<valuePeriod>
					<start value="2017-01-01"/>
					<end value="2018-02-01"/>
				</valuePeriod>
			</part>
			<part>
				<name value="includeIssues"/>
				<valueBoolean value="true"/>
			</part>
	</parameter>
	<parameter>
		<name value="includeResourceGroup:AllergyIntolerance"/>
			<part>
				<name value="includeResolvedAllergies"/>
				<valueBoolean value="true"/>
			</part>
	</parameter>
</Parameters>

Separate email request has been sent to Data Standards.

**Comment by jonnyry** [comment]
The operation name is gpc.getstructuredrecord
 
http://gpconnect-structured.netlify.com/accessrecord_structured_development_retrieve_patient_record.html
 
Could we also call this GPConnect-GetStructuredRecord-Operation-1 so the operation definition name ties in with the operation name?
 
The -Operation part aligns with the the other operation definitions on the FHIR server:
 
https://fhir.nhs.uk/OperationDefinition

**Comment by jlellison** [comment]
Does this Operation Definition need to be 'draft' or 'active'?

**Comment by tim1ford** [comment]
It would need to be 'draft' Jen.

I'm just working on a few amendments, I'll have them over to you asap.

**Comment by jonnyry** [comment]
Jen,

Here's the changes for the OperationDefinition that I can see:

1. element values:

	a. name = GPConnect-GetStructuredRecord-Operation-1 or something similar to the old HTML operation definition
	b. code = gpc.getstructuredrecord
	c. description = Get a patient's clinical record in a structured coded format
	d. kind = operation
	e. resource = Patient
	f. system = false
	g. type = true
	h. instance = false
	i. status = draft

2. profile elements, remove from the following places (as profile applies to what's specified in the type element and not what is output in the final bundle):

	a. patientNHSnumber parameter
	b. includeResourceGroup:Medication parameter
	c. includeResourceGroup:AllergyIntolerance parameter

3. following feedback from RK, change the following parameter names:

	a. "includeResourceGroup:Medication" to includeMedication
	b. "includeResourceGroup:AllergyIntolerance" to "includeAllergiesAndIntolerances"
	c. "includeIssues" to "IncludePrescriptionIssues"

4. Add a constraint (if possible) that one of includeMedication or includeAllergiesAndIntolerances must be supplied

5. documentation elements:

	a. patientNHSnumber - "The NHS number of the patient whose record is being extracted, which must be traced or verified against the national demographics index"
	b. includeMedication - "Include resources representing a patient's medication record in the response bundle"
	c. timePeriod - "Restrict the patient's medication record to a specific time period"
	d. includePrescriptionIssues - "Include individual prescription issues in the response bundle"
	e. includeAllergiesAndIntolerances - "Include resources representing a patient's allergies and intolerances in the response bundle.  By default, resolved allergies and intolerances are not included."
	f. includeResolvedAllergies - "Include resolved allergies and intolerances in the response bundle."
	g. response - "The patient structured coded record. This is returned as a bundle containing resources representing the record as requested by the given input parameters."

6. Bundle profile - could you create us a specific profile for our GetStructuredRecord bundle?  Don't need much specifying in it - basically that the type is a Collection.
I want us to have flexibility to extend it down the line without breaking providers or consumers, in case we need to send back any Bundle level "flags".

Thank you.

**Comment by jlellison** [comment]
I'll leave this ticket open until we can get the Operation Definition rendered on the fhir server.

**Comment by jlellison** [comment]
This has now been published on the production server https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-GetStructuredRecord-Operation-1.
