### ISSUE TITLE
Clarify current position re XML vs JSON for consumers

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#376]
Find suitable place in the specification to make it clear the current preference to build in JSON (for universal provider support).

**Comment by jonnyry** [comment]
https://github.com/nhsconnect/gpconnect/commit/bc3eb6c78b9e43440d94539b00d838c8ffc8fab0

**Comment by jonnyry** [comment]
Also needs making clear somewhere in the introductory consumer guidance pages.

**Comment by RiChallinor** [comment]
To be applied to 1.2.0 and 0.5.1 also##

**Comment by jonnyry** [comment]
Also added to 0.5.1.

Will be added to 1.2.0 when master is merged down to develop (at 1.1.1 release time).
