### ISSUE TITLE
Remove old GP Connect DMSes on developer.nhs.uk except for the HTML DMS

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#377]
The old GP Connect DMSes, excluding the HTML DMS are no longer in use.

Can we remove the following from the Developer Network?: 

https://data.developer.nhs.uk/fhir/candidaterelease-250816-appts
https://data.developer.nhs.uk/fhir/candidaterelease-170816-tasks
https://data.developer.nhs.uk/fhir/candidaterelease-240117-getrecordstructured

Leaving the following remaining (to support HTML):

https://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord

Thanks

**Comment by jlellison** [comment]
The specs have been removed/retained as per the above instruction.
