### ISSUE TITLE
CareConnect admin profiles alignment

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#378]
Message from @jlellison :

I have impacted aligning the foundations profiles for GP Connect with the latest CareConnect profiles post curation.  I have listed the required/optional changes below, however can you confirm which if  these changes can be made and won’t break any of the current streams that are being built to before I apply the changes.

`Organization`

No changes required this still conforms to CareConnect.

`Location`

No changes required this still conforms to CareConnect.

`Practitioner`

name.family – the cardinality has been relaxed in CC to 0..1 from 1..1.

`PractitionerRole`

No changes required this still conforms to CareConnect.

`Patient`

Registration Details Extension has been removed.

New optional Extension for Death Notification Status.

A Concept map has been created to map values for name.use to PDS name types.

Contact.relationship the CodeableConcept cardinalities are as per base and have not been constrained down.

**Comment by jonnyry** [comment]
Jen

Could you explain this one a bit more, I'm not sure what the change is?

Contact.relationship the CodeableConcept cardinalities are as per base and have not been constrained down.

Thanks
Jonny

**Comment by jlellison** [comment]
The previous Care Connect profile had previously constrained down the elements within the CodeableConcept that had been adopted by GPConnect.  This has since been relaxed so it is whether you want to adopt this. I have attached some examples.
![careconnectnow](https://user-images.githubusercontent.com/24409763/37151061-f8409888-22cb-11e8-9530-8a3aa35dc214.PNG)
![currentgpc](https://user-images.githubusercontent.com/24409763/37151068-fac82026-22cb-11e8-8da7-7be9416aa6d6.PNG)

**Comment by jackiebarnes** [comment]
@james-answer   - could you confirm against Jen's items above what we agreed with regard to the changes for CareConnect-GPC equivalent profiles;  ta

**Comment by james-answer** [comment]
I think we agreed to include it as the fields are optional but we probably want the system code and display to be 1..1 as they currently are to be non breaking but also consisten with other GP Connect CodableConcepts.

**Comment by jlellison** [comment]
Hi @james-answer I can see the changes you want me to apply to releationship. Do you have the responses for the other changes so I can get these applied before I go on leave please.

**Comment by jlellison** [comment]
Hi as you are aware we have sent some questions back to INTEROPen around the extension that was removed from base. Their response is currently unclear. @DaveBarnet will follow it up when we he returns from leave, and I will make the changes to Patient the w/c 26th March when I return from leave.

**Comment by jonnyry** [comment]
Email to Amir re registrationDetails extension:

Hi Amir
 
Sorry for the delay in getting a response to you.
 
The RegistrationDetails extension has four sub-elements against it:
 
registrationPeriod
registrationType
registrationStatus
preferredBranchSurgery
 
We have use cases only for the fourth sub-element – preferredBranchSurgery – which are:
 
To restrict/filter the GP organisation’s appointment book to appointments available at the patient’s preferred branch
In an urgent care call centre, to be able to confirm the patient’s preferred branch surgery
 
I’ve advocated for the removal of the registration details extension for some time as the first three elements are problematic in a number of ways (I won’t go into detail here), however since then two things have happened:
 
preferredBranchSurgery had been added to it
One GP principal provider is developing against this profile now, and one about to start development, and several consumers are building against this profile
 
Possible routes to proceed (as I see them):
 
Maintain the structure of the RegistrationDetails in its current form, AND:
 
EITHER put the extension back in CC.
 
OR keep the extension in GPC only as level 3 extension.  Add to GPC Patient profile only.
 
Delete RegistrationDetails extension entirely, from both CC and GPC.  Recurate preferredBranchSurgery as level 2 or level 3 simple extension
 
Breaking changes – will create a cost and time implication on the GP Connect programme.
 
Let me know your thoughts.
 
Regards
Jonny

**Comment by jackiebarnes** [comment]
Agreed with Data Stds to keep Patient Reg Dtls extension

**Comment by jlellison** [comment]
Apologies for the delay the updated Patient resource (1.4.0) has been released to the server https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1.
