### ISSUE TITLE
Change Retrieve patient appointment search parameter requirements

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#380]
Solution proposal agreed to uplift spec to reflect the following:

·         Consumer to be required to supply mandatory date search parameters as with 'Search Free Slots' (SFS) - ie lower boundary = greater than or equal to; upper boundary = less than or equal to  (currently this is not mandated in the spec)

·         Consumers should not provide a Time – as with SFS

·         If any part of the date range supplied is in the past, then Provider returns an error

·         Specific error message to be defined to cover this scenario

·         Current (today's) date is valid - pending agreement to be sought by JB from Peter Short for IG perspective;  he’s back on Monday

·         Enhance guidance for consumers to reflect that current date is earliest date to be processed and that they should make clear to end-users that only appointments in the future will be returned

 

Proposal to be validated with EMIS & TPP – I/Jonny/James or you tomorrow.

These changes are breaking and will need to be implemented in 1.0.0 spec and then uplifted into 1.1.0.

**Comment by james-answer** [comment]
I have made the proposed changes for the "Retrieve a Patients Appointments" on the following feature banch:

https://github.com/nhsconnect/gpconnect/tree/feature/retrieve_patients_app_new_date_range


There is a netlify version of that branch:

https://gpconnect-retrieve-app-change.netlify.com/appointments_use_case_retrieve_a_patients_appointments.html

**Comment by jackiebarnes** [comment]
@james-answer From Jonny:
•	provider shall return an error if a time is sent by the consumer.

•	If we are requiring two dates, needs to be clear that if the consumer does not provide two dates, an error (OperationOutcome) shall be returned. 

•	explicitly prohibit partial dates – an error shall be returned in this case.

Are the changes here to be reflected also in functionality with the Search For Free Slots call?

**Comment by james-answer** [comment]
I have updated the wording to specifically state the above:

The consumer:
- SHALL only include the date component of the search parameter and not a time component. The date - SHALL include day, month and year elements.

The Provider:
- SHALL return an error if either either of the date parameters contain a time element.
- SHALL return an error if either of the two start date parameters are not sent with the consumers request.

For search for free slots the requirements only restrict the consumer to send through two date parameters, one with the prefix of `le` and one with the prefix `ge`. The time element and partial dates can be included and there is no guidance for errors when the consumer sends anything different.

**Comment by jackiebarnes** [comment]
Obtained agreement on IG re 'Retrieve Patient Appointment' including past appointments as a by-product if they occur today;  updating AM IG guidance pages, and 'Core' IG Principles page

**Comment by james-answer** [comment]
Branch containing changes has been merged into develop branch from feature branch now the change has been agreed by IG and providers.

**Comment by james-answer** [comment]
Changes have been made and is published for 1.1.0
