### ISSUE TITLE
Structured Record Discrepancies

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect#381]
The [API definition](http://gpconnect-structured.netlify.com/accessrecord_structured_development_retrieve_patient_record.html#payload-response-body) page states that the bundle returned for a structured record request should be of type searchset. 

The examples show a [structured record bundle](https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-GetStructuredRecord-Bundle-1) with a type collection. The type has a fixed value of collection in the structure definition.

**Comment by lucywilcock** [comment]
[OnsetDateTime](http://gpconnect-structured.netlify.com/accessrecord_structured_development_allergyintolerance.html#onsetdatetime) is marked as Mandatory but the text states that it only needs to be populated if the GP system records it (aka Required?).

**Comment by lucywilcock** [comment]
The [Additional Parameters](http://gpconnect-structured.netlify.com/accessrecord_structured_operation_definition_parameters.html#includeallergies) page states that the allergies section is made up of AllergyIntolerance, Patient and Practitioner but the [API definiton](http://gpconnect-structured.netlify.com/accessrecord_structured_development_retrieve_patient_record.html#payload-response-body) states that an Organization must also be included.

**Comment by lucywilcock** [comment]
The [parameter details](http://gpconnect-structured.netlify.com/accessrecord_structured_development_retrieve_patient_record.html#parameter-details) lists one of the parameters as inlcudAllergies - this is probably missing an 'e'

**Comment by lucywilcock** [comment]
In the [FHIR Example 1](http://gpconnect-structured.netlify.com/accessrecord_structured_development_fhir_examples_1.html) the allergy with id 561850bd-360c-4d17-b3c8-a837ef0cbfba is in the 'Active ALeergies' list but has a clinical status of resolved.

**Comment by lucywilcock** [comment]
The allergy [end date field](http://gpconnect-structured.netlify.com/accessrecord_structured_development_allergyintolerance.html#extensionallergyendenddate) references status, I think this should be clinicalStatus.

**Comment by lucywilcock** [comment]
The [Medication Statement](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medicationstatement.html#basedon) referes to basedOn as an Identifier. The [FHIR Definition](https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-MedicationStatement-1) calls it a Reference.

**Comment by lucywilcock** [comment]
The FHIR resources refer to BasedOn for [MedicationStatement](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medicationstatement.html#basedon) as an Identifer but the[ FHIR structure](https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-MedicationStatement-1) refers to it as a Reference.

**Comment by tgmay** [comment]
[BasedOn](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medicationstatement.html#basedon) for the MedicationStatement states the cardinality should be 1..* but as outlined in [MedicationGuidance](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medication_guidance.html) the cardinality should be 1..1.

**Comment by lucywilcock** [comment]
The FHIR Resources page for [MedicationRequest](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medicationrequest.html#prescriptiontype) has presctionType as a Code, the [FHIR StructureDefinition](https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-MedicationRequest-1) has it listed as an Extension.

**Comment by lucywilcock** [comment]
For the FHIR Resources page on [Lists](http://gpconnect-structured.netlify.com/accessrecord_structured_development_list.html#title) the 'title' parameter has a datatype of title and a optionality of Code. This seems to be one step out.

**Comment by lucywilcock** [comment]
In the FHIR Resources page for [List](http://gpconnect-structured.netlify.com/accessrecord_structured_development_list.html) the Code parameter is shown as a Code data type. In the [StructureDefinition](https://fhir.nhs.uk/STU3/StructureDefinition/ITK-Medication-List-1) it is a CodeableConcept

**Comment by tgmay** [comment]
The [statusReason.reason](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_medicationrequest.html#statusreasonreason) is shown as a valueString extension. In the [StructureDefintion](https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-MedicationStatusReason-1) it is a valueCodeableConcept extension.

**Comment by lucywilcock** [comment]
In the [Operation Definition](http://gpconnect-structured.netlify.com/accessrecord_structured_development_operation_definition.html) the includePrescriptionIssues is documented as 'Include resources representing a patient's allergies and intolerances in the response bundle. By default, resolved allergies and intolerances are not included.'

**Comment by tgmay** [comment]
In the [Medication Request](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medicationrequest.html) there is a contradiction: The [dispenseRequest.quantity](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medicationrequest.html#dispenserequestquantity) states "If the units are text then the extension dispenseRequest.quantityText SHOULD be used"    . The [dispenseRequest.quantityText](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medicationrequest.html#dispenserequestquantitytext) states  "Only to be used if there is no numerical value". 

As the units will always be text (String in the [Structure Definition](https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-MedicationRequest-1)), it is unclear value which should be used if both quantity and quantityText exist.

**Comment by lucywilcock** [comment]
[LastOccurence](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_allergyintolerance.html#lastoccurrence) in the Allergy resource is listed as optional but the cardinality is 1..1 (on the [FHIR structure definition](https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-AllergyIntolerance-1) it is listed as 0..1)

**Comment by lucywilcock** [comment]
On the List resource the entry.item has a cardinality of 0..1, on the FHIR site it has a cardinality of 1..1

**Comment by lucywilcock** [comment]
The FHIR response examples show the list meta.profile as https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Allergy-List-1 for allergies and https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Medication-List-1 for medications. In the spec they are listed as having a fixed value of https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-List-1. Additionally, the examples do not have an id for list which is mandatory.

**Comment by lucywilcock** [comment]
The FHIR response examples have list.subject using an absolute reference. This should be changed to a standard relative reference.

**Comment by lucywilcock** [comment]
The lists on the allergy FHIR examples do not have a subject reference which is listed as mandatory in the spec.

**Comment by lucywilcock** [comment]
The effective field on the medication statement - should the text be a SHOULD NOT instead of a SHOULD

**Comment by lucywilcock** [comment]
The text on the medication request basedOn is a little confusing, I think it is missing an 'an' before the last issue.

**Comment by lucywilcock** [comment]
Titles are specified for the lists in the allergy section but the medication list is never given a specific title - should it have one or can it be called anything?

**Comment by lucywilcock** [comment]
Meta.profile and meta.lastUpdated are listed as mandatory but have a cardinality of 0..1 (this is the same everywhere)

**Comment by lucywilcock** [comment]
In the medication request the repeat information is listed as mandatory but there is no guidance on what should be included if the medication is an acute prescription. In the FHIR documents the repeatInformation is listed as optional.

**Comment by lucywilcock** [comment]
The [Allergies Guidance](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_allergies_guidance.html#negation---handling-no-known-allergies) states that if there isn't a specific 'no known allergies' code and no allergies are returned then the list should have an emptyReason code and a note that reads: There are no allergies in the patient record but it has not been confirmed with the patient that they have no allergies (that is, a ‘no known allergies’ code has not been recorded). 

The [FHIR resources](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_list.html#emptyreason) state 'A FHIR code of No Content recorded SHALL be used if a query returns no results to enter into a list. In this case the ‘note’ field SHALL be populated with the text ‘Information not available’.'

The two seem to contradict one another.

**Comment by lucywilcock** [comment]
In MedicationStatement taken is listed both as [mandatory](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_medicationstatement.html#taken) and as [SHOULD NOT be populated](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_medicationstatement.html#taken-1).

**Comment by lucywilcock** [comment]
In MedicationReason basedOn, requester, groupIdentifier and dispenseRequest.expectedSupplyDuration are all listed as required while also being in the SHOULD NOT be populated section.

**Comment by lucywilcock** [comment]
In MedicationRequests it is noted that groupIdentifier should NOT be populated for any requests with an intent of 'plan'. However, the [instructions](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_medicationrequest.html#groupidentifier) on how to fill it in state: All repeat prescribed and repeat dispensed medications SHOULD have a group identifier that is populated for the ‘plan’ and all ‘orders’ relating to them.

**Comment by lucywilcock** [comment]
There is a typo on the MedicationStatement page: [dosagepatientintstruction](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_medicationstatement.html#dosagepatientintstruction)

**Comment by lucywilcock** [comment]
Recorder is listed as required (cardinality 0..1) in the GpConnect AllergyIntolerance FHIR resource. In the FHIR spec it has a cardinality of 1..1.

**Comment by tim1ford** [comment]
All issues addressed in 1.2.0.
