### ISSUE TITLE
Structured profiles change

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#382]
Jen

Could you make a couple of small changes to the Structured profiles?

1) The operation GPConnect-GetStructuredRecord-Operation-1, could you change the name of the parameter `timePeriod` to `medicationDatePeriod`?

Could you also change the description of the above parameter to "Restrict the patient's medication record to a specific date period. Only whole date values (and not time) may be provided."?

2) Could you change the name of the Bundle `GPConnect-GetStructuredRecord-Bundle-1` to `GPConnect-StructuredRecord-Bundle-1`?

Thanks
Jonny

**Comment by jlellison** [comment]
Hi Jonny

The change to the Operation is straight forward.

Changing the name of the bundle, in turn changes the URL so it would create a new instance on the FHIR reference server and I would need to request Adam Hatherly removes the existing GPConnect-GetStructuredRecord-Bundle-1.

I will aim to get these changes complete before I go on leave.

**Comment by jonnyry** [comment]
Thanks - have updated the list above slightly (sorry) - basically changing `medicationTimePeriod` to `medicationDatePeriod` as we're only allowing searching on dates (and not times).

I've also updated the associated `documentation` element.

**Comment by jlellison** [comment]
The new bundle has been released on to the server, and I have requested the old one is removed.

The Operation Definition is available from the develop branch of STU3 FHIR Assets:
https://github.com/nhsconnect/STU3-FHIR-Assets/blob/develop/Operations/GPConnect-GetStructuredRecord-Operation-1.xml

Thanks

Jen
