### ISSUE TITLE
Retrieve Patient Appt - Date Range (& other?) Changes to align to 1.1.0

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#383]
To ensure that the changes being uplifted to 1.1.0 are implemented in 1.0.0 as appropriate.

**Comment by james-answer** [comment]
linked to #380

**Comment by jonnyry** [comment]
@jackiebarnes @james-answer is this now concluded?

**Comment by james-answer** [comment]
Yes, I think this is now done.
