### ISSUE TITLE
AM Error Messaging

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#386]
@jonnyry @james-answer 

Do we need a more specific Spine error message value to reflect the scenario 'Appointment Slots Not Available' to cover this scenario for SFS and Book Appointment - conveys more meaning than 'No Record Found' - or are we, as a principle, wanting to hold to more generic operation outcome messages?

**Comment by james-answer** [comment]
I think in FOT the chance of two people booking into the same slot at the same time is small but there is a risk as the federations and number of people booking into the same appointment book from multiple consumer organization there is a greater risk of when booking that the selected slot will be already be taken by another booking. We could add an error to make the it more clear to the consumer that this is the cause for an error when they try to book an appointment.

It does not help stop the issue though, this was raised as a concern by urgent care as something which might happen. If we think this is something that might happen and that we might want to prevent then we might want to implemnet some sort of slot hold/reserve operation which holds a slot for an appointment against a specific patient, which stops the slot being returned in search for free slots for a set period of time before being release. There is quite a lot of complexity around this if we were to do it, we would need a reserve slot operation, a cancel reserve slot operation if the consumer decides not to book an appointment against the slot, we would need to tackle the risk everyone will raise about consumers reserving slots over and over then just cancelling the reservation when they actually want to use the slot. There would be a risk of miss use which we would have to cover off some how.

**Comment by Dunmail** [comment]
@james-answer: The race condition does occur on Black Pear production services; we therefore provide a Slot/{{id}}/$reserve operation (as you describe). Checking our logs, in around 1% of cases the $reserve operation is rejected because the slot has been reserved for another patient.

**Comment by james-answer** [comment]
Thanks @Dunmail that is very useful information for us making the decision on how vital this sort of functionality might be in live. It will also be useful if we have to go back to the providers to ask them to implement this additional functionality.

**Comment by briandiggle** [comment]
A "reserve slot" function for me would be appropriate where there is a genuine two-stage process, as seen on eRS. A slot is reserved, but the booking is confirmed later through a, probably offline, business process. 

The appointment management API as it stands has a fundamental design of a one stage booking process which is much simpler to implement. So the best approach to align with that would be simply to a provide clear error message should the slot actually have a booked status upon submission of the "book an appointment" request.

Should a "reserve slot" be introduced, there would be following additional the error condition to handle:
1. Search for free slots called
2. Reserve slots called
3. Error returned because another consumer has reserved the slot.

**Comment by james-answer** [comment]
Check if the automated test suite tests for this scenario

**Comment by RiChallinor** [comment]
To be applied to 1.2.0 also?##

**Comment by james-answer** [comment]
Currently the test suite does not test for this scenario so I will up date it, the most appropriate error to return would be:

A http "409 Conflict" with spine error code "DUPLICATE_REJECTED" as this indicates the issue and is not likely to be used in another appointment scenario.

**Comment by james-answer** [comment]
I have updated the test suite with a new test which books an appointment into a slot then tries to book an appointment for a different patient into the same slot.

**Comment by james-answer** [comment]
Furing FOT and beyond we will evaluate the impact of this race condition to assess if we need to take a more proactive approach to tackling this issue. I will close this github issue and open a new one if we need to re-visit this issue.
