### ISSUE TITLE
Update versioning policy

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#388]
Update versioning policy to allow some flexibility in changes during early stage development where breaking changes have no material impact on consumers and providers.

**Comment by RiChallinor** [comment]
Add to 0.5.1 also

**Comment by RiChallinor** [comment]
To be applied to 0.5.1 and 1.2.0 also##

**Comment by jonnyry** [comment]
Added to develop (1.2.0) and feature/0.5.1.
