### ISSUE TITLE
Publish sidebar & page re-organisation

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#389]
(@Mhitchins changes)

**Comment by RiChallinor** [comment]
@Jonny to review Mike H work and look to incorporate in to merging
@tim1ford to support adding to 0.5.1
@james-answer to support adding to 1.1.1

**Comment by RiChallinor** [comment]
To be applied to 0.5.1 and 1.2.0 also##

**Comment by jonnyry** [comment]
After spec review workshop, have scaled back the size of this change - now only adding the Tags and External Links top level menu items under Help & Support.  The proposed changes to create a new Develop menu items have been postponed pending the outcome of the larger scale user pathways work.

**Comment by jonnyry** [comment]
This will get merged to 1.2.0 when the 1.1.1 release is made -

1. feature/1.1.1 is re-integrated to master
2. master is branched to create release/1.1.1
3. master is merged down to develop (containing 1.2.0)

0.5.1 will need manually updating (though we don't have a branch for this yet.

**Comment by jonnyry** [comment]
Manually added to 0.5.1.
