### ISSUE TITLE
Update version number in 1.1.1

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#394]
Sidebar and conformance statement.

**Comment by james-answer** [comment]
I updated the feature branch with this just after I create it, so when we merge down to Master it should bring the version number change down with it.

**Comment by jonnyry** [comment]
Ah!  I hadn't synched your change.  Closing the issue.

**Comment by jonnyry** [comment]
https://github.com/nhsconnect/gpconnect/commit/db9790e8dc3f9736112efb2c606f9cb1ad3c2292
