### ISSUE TITLE
AM:  Appt Reason - Non-Usage

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#395]
More guidance needed in spec to cover off gaps/inconsistency - see #359:

- change Should Not to Shall Not on Book Appt
- On Retrieve/Read Appt, add guidance around only desc/comment and not reason to be supplied
- Consumer Demonstrator and Provider test suite to be updated to check for non-inclusion of Reason
- Update TOM
-

**Comment by james-answer** [comment]
- Changed wording on Book Appointment to make SHALL.
- Added wording on Read and Retrieve appointments to say SHALL NOT include reason in appointment resource.
Merged into 1.1.1 release branch and dev.

**Comment by james-answer** [comment]
Test suite and demonstrator have been updated with these stronger requirements for appointment reason. The only outstanding change is now the changes to the TOM.

**Comment by jackiebarnes** [comment]
A draft version of the TOM reflecting this has been created.  Will progress merging of this into Enablement team latest overall TOM version.
