### ISSUE TITLE
FHIR CapabilityStatement should be in JSON rather than XML

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#397]
Since we are encouraging consumers to build against JSON rather than XML, the FHIR CapabilityStatement response body should be in JSON and not XML.

https://nhsconnect.github.io/gpconnect/foundations_use_case_get_the_fhir_capability_statement.html

**Comment by james-answer** [comment]
I have done this for the 1.1.1 release, the same needs doing for the 1.2.0 release so I have raised another github issue #398
