### ISSUE TITLE
ARHTML - IG Reqs Uplift

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#399]
Review required taking into account new format constructed by Tim to ensure IG reqs/expectations adequately represented

eg Needs para on Intro page making more explicit around being 'incorporated into Electronic Patient system - remove ambiguity re viewing NOT storing of data - this then aligns to Priv Impact Assessment (DPIA) doc

**Comment by RiChallinor** [comment]
@tim1ford to draft wording

**Comment by tim1ford** [comment]
The following wording has been added on the introduction page in the top information section:

Access Record HTML is delivering the capability to view a patient record and **MUST NOT** be used as a means to store data.

@jackiebarnes is this sufficient to align to the DPIA doc?

**Comment by tim1ford** [comment]
Text amended to, see below, following review:

Access Record HTML is delivering the capability to view a patient record and **MUST** be used in real time.
