### ISSUE TITLE
Find Patient - Preferred Branch Surgery (PBS)b Spec Gap

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#400]
We have spec'd this as SHALL populate - either with branch surgery or GP registered Practice.  However if the Find a Patient is sent to a practice other than registered one, then Prov sys, req'd to do a PDS trace to determine the registered GP Practice?

**Comment by james-answer** [comment]
This scenario relates to temp patients, when a temp patient is registered then the provider where the patient is being registered will need to link the patient to a branch or a organization.

As patient registration is currently part of the appointment booking the consumer could send a the preferred branch surgery with the registration which is the location of the appointment, but this would be additional complexity on the consumer and not add any useful information for our use cases, it would probably be better to let the provider just default it to the preferred branch surgery to the location which represents the provider system organization and not ask the consumer to populate the element.

**Comment by jackiebarnes** [comment]
@jonnyry 

Further discussion 

Spec Uplift:

Find a Patient:   reword  "where they are registered" on 'Shall populate the Preferred Branch Surgery' to something that more accurately represents the location of the Organisation targeted in the request

**Comment by jackiebarnes** [comment]
Spec Uplift:

Find a Patient:   reword  "where they are registered" on 'Shall populate the Preferred Branch Surgery' to something that more accurately represents the location of the Organisation targeted in the request

**Comment by jonnyry** [comment]
Option b) is problematic as it couples the use of Register Patient to Find Free Slots and the two might not necessarily be used together.

**Comment by james-answer** [comment]
Final decision is to make it optional for the consumer, if they have a location such as in appointment booking they should supply that otherwise provider if no branch surgery is included in register patient they should default to the main organization location.

I will update the specification.
