### ISSUE TITLE
Patient Resource - 'Contact' Element - 'Relationship' Value

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#412]
Can the values for this 'relationship' type be restricted to eg 'Next of Kin', and Emergency Contact?  

current valueset is very restricted - doesn't contain familial relationships etc

Two relevant values above can be mapped to, but if there is a requirement to capture all the other relationships, then more mapping needed between SNOMED code representation of these relationships

**Comment by jackiebarnes** [comment]
Discuss with Data Standards re extending this value set to include the familial relationships based on SNOMED;  in meantime, EMIS can continue to use NoK and Emer Con. mapping their values appropriately

**Comment by jackiebarnes** [comment]
Identifying suitable additional patient 'relative' values to discuss further with Data Stds team.

**Comment by jackiebarnes** [comment]
Structure Def allows for each patient contact to have a relationship value - to which NoK/Emer Contact can be mapped if these are distinct values, or the source system snomed codes and string values?  taking this plus question as to population of all patient contact (as in telecom, address etc etc) and population of the patient's Contact (as in relation/etc) contact details to Clin Ref Group given the  IG context - validate (or not) that the general IG operating model for GP C should mitigate concerns/risks around this

**Comment by jackiebarnes** [comment]
@ James - does the FHIR element structure accommodate the fact that EMIS could send back a SNOMED code and text representation of the relationship between the Patient Contact & the Patient, rather than having to map to the extensible FHIR value set?

**Comment by jackiebarnes** [comment]
Raised for discussion at Clin Ref Grp of 25/6/18 - whether we suggest that only certain relationship types need to be populated - suggested NoK, Emer Contact, Carer

**Comment by jackiebarnes** [comment]
Decision from Clin Ref Grp:

All data as recorded in the provider system should be populated 

do we need additional guidance on FHIR server or possible new Foundations page as for ticket #403 re population with extensible values

**Comment by RiChallinor** [comment]
Add additional guidance when adding common population guidance

**Comment by jackiebarnes** [comment]
Agreed to leaving this element and value set as is - and to be populated by Providers according to the 'contact' purposes of their patient contacts.
