### ISSUE TITLE
Register Patient - Contact Details - Storing/Sending - EMIS

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#413]
Register Patient spec currently requires Prov to store any contact details sent from Consumer and for these not to be overwritten by any PDS-sourced details if different.

EMIS Web: 

Consumer-sent **telecom** details are stored until a Provider system smart-card user accesses the patient details, triggering a PDS trace 
if the PDS details are different to those received from consumer a warning of the mis-match is presented to the end-user with options:

1. End-user can choose to ignore warning, in which case consumer-sent telecom details remain on the temp record, PDS NOT updated, and the data item will be returned in a subsequent Find Patient API request
2. End-user can choose to accept consumer details in which case these continue to be stored against the Patient record, and PDS is updated
3. End-user can choose to accept PDS details in which case the consumer-sent details are overwritten and stored in the audit trail,  but cannot be subsequently sent from the Provider in response eg to Find a Patient etc

Current test script requires the Provider to be able to 'store and **return**' the original consumer-sent details in this scenario; EMIS currently only do this in scenario 1. above for Telecomms;  need to change the test script to reflect the current spec re Providers expected to store.

The **address** details are currently being overwritten by PDS;  **have requested the same handling as Telecom details**

**Comment by james-answer** [comment]
For a) you have put "if the consumer details are accepted, then these are stored against the Patient record, and PDS is updated" does that mean that if a temporary registration is done in an emis system and the consumer has sent temp contact detail, maybe their hotel or something, if a user selects those contact details that the emis system updates the patients main Spine demographics with the temp contact details?

**Comment by jackiebarnes** [comment]
Q: Will the user be aware that syncing the patient is going to update the spine and affect the main registered practice. 
A: This will happen the next time a user opens the patients record (the trigger for a PDS synchronisation).
A manual synchronisation screen will be presented to the user to allow them to select which is the correct telephone number.
It’s not that they are specifically updating the main registered practice – PDS is a read/write demographic store for the whole of the NHS, not just for registered practices – and as such anyone with “full PDS” access can update it.  Users at other organisations who are interested in the patient (including the registered practice) will receive a notification of the update via a manual synchronisation screen and be asked whether they want to accept or reject the update (in which case PDS will be set back to the original value).
Q: Will the practitioner confirm with the patient before making the decision?
A: They are not mandated to speak to the patient, however in order for them to make a decision as to which telephone number is correct, they should have some way of checking this (speaking to the patient would be the usual method).  Though it’s often said that practice’s will just take their local value to be correct without checking – sometimes creating a ‘ping-pong’ synchronisation battle between two divergent organisations!

**Comment by jackiebarnes** [comment]
3/5/18 sent request for validation of handling to PDS Compliance team

**Comment by jackiebarnes** [comment]
Response from PDS Compliance team:

"It would indeed be preferable if the contact details were held locally. The concern would be that any update to PDS may well amend the address contact details incorrectly by putting a temporary contact address into the usual address field. 
 
If a PDS update is performed then any temporary contact address should be passed as a temporary address with an end-date (I believe that the NHS England guidelines state that temporary registration must only be for a maximum of 3 weeks, so this should be reflected in the temporary address end-date). If no end-date is passed then the temporary address will remain long after it is required"

**Comment by MikeStacey** [comment]
Do we distinguish between permanent and temporary contact details in the FHIR profiles. Based on everything above it sounds like an update from PDS should be possible for permanent contact details but for temporary ones.

**Comment by jackiebarnes** [comment]
1.1.1 Uplift Proposal:

Consumer requirements
The consumer must send the following as a minimum:
•	NHS number, Date of birth, gender, official name
The consumer may optionally send the following temporary contact details, if available:
•	Telecoms with a contact-use of temp
•	Address with a contact-use of temp
No other fields or types of telecoms or address should be sent by the consumer.

Provider requirements
Upon receipt of the register patient details, the provider should then perform a PDS retrieval on the NHS number and perform a local cross check on NHS number and DOB:
•	If the NHS number and DOB are not matching, an error should be returned.
•	If the PDS record is superseded, invalid, sensitive or deceased, an error should be returned.
•	If the provider cannot contact PDS, an error should be returned.
The provider should then perform check their local patient index for matching registrations on NHS number and DOB:
•	If an active patient (of any registration type exists):  (presumably this scenario would be extremely edge case, as Find Patient checks for this)  
o	any temporary address or telephone contact details provided by the consumer should be added to the record and marked as temporary address and telephone contact details
o	and the patient should be returned to the consumer
•	If an inactive patient exists, 
o	the patient record should be re-activated as a temporary registration type, 
o	any temporary address or telephone contact details provided by the consumer should be added to the record and marked as temporary address and telephone contact details
o	and this record should be returned to the consumer
•	If a deceased patient exists, 
o	an error should be returned
•	If no patient exists:
o	a new local record should be created, using the demographic details returned from Spine.
o	any temporary address or telephone  contact details provided by the consumer should be added to the record and marked as temporary address and telephone contact details
o	and this record should be returned

Explicit wording re NO updates from Prov to PDS of temporary contact details

**Comment by james-answer** [comment]
Updated as per the agreed position.

**Comment by jackiebarnes** [comment]
From Nick Apperley
PDS Compliance Solution Architect
Demographics Team

If I understand the issue correctly I think it is difficult for me to generalise about whether the locally stored data provided as part of the booking should be updated on to PDS. As Eric has said, if it relates to an address then that would need to be handled very carefully in order to prevent an incorrect usual address ending up on PDS as the patient’s permanent address.

If it is telephone contact details then it could be that the patient has provided a mobile phone number which they haven’t told their own GP about and which would ideally go on to PDS.

But again it could be a home telephone number which is only applicable for the period of their temporary registration and then again needs to be handled carefully as with address to avoid losing their permanent home telephone number. One suggestion to handle this could be to add it on to PDS as a type “HV” (A vacation home, to reach a person while on vacation).if that is appropriate, or add as a type “H” address (used for a secondary home telephone number). With each of these suggestions it would be essential to provide both a business effective from and a business effective to date to indicate the dates for which it is applicable.

I suppose best practice by a user does need to be reinforced in these situations, i.e. the user needs to have some way of confirming whether the local data or the PDS data is more up to date before choosing to update PDS with local data e.g. by the patient confirming it themselves. The system may then need to determine how to update PDS along the lines described above.

**Comment by jackiebarnes** [comment]
As we have called this out explicitly on Register a Patient, is there value in explicitly calling out the req on Prov to return the temp contact details on Find a Patient - as we're meeting a specific 'temp contact details' for the purpose of the appt req?
