### ISSUE TITLE
Patient Address Elements 

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#414]
EMIS currently returning 6 address elements ( ie including 'State', which is in the base FHIR resource but not in the GP Connect one).  The mandatory address items in EMIS are line, town, county:
   line = 1 Trevelyan Square
   city = Leeds
   district = named area within town - eg 'Horsforth'
   state = county
   postal code
   country = UK, Gibraltar etc

Base FHIR resource elements:
line
city
district
state
postal code
country

GPConnect-Patient-1
line
city
district
postal code
country
 
Either GPConnect address needs to have another sub-element, or area of town should not be populated

**Comment by james-answer** [comment]
If you were writing the address on a letter Horsforth would be another line in the address not a state which you would put below the district, so the fhir resource should reflect this as there line element is cardinality 0..*:

line = 1 Trevelyan Square
line = Horsforth
city = Leeds
district = West Yorkshire
postal code= {post_code}
country = GBR

State is not in the GP Connect profile and is not needed for UK addresses.

**Comment by jackiebarnes** [comment]
Indicated to EMIS that addresses should be populated to sub-elements as above
