### ISSUE TITLE
FHIR API Population - Principles

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#415]
Contact details are not generally being returned by EMIS because the elements are optional - this may be the same for other optional elements

? Need to call out in the Spec the general principles re:

1. alignment to base FHIR profiles - therefore some elements are included in FHIR profiles but not applicable to our deployment settings - eg 'specialism' in Appointment etc#
2. Optional FHIR profile elements are still expected to be populated if Provider have corresponding fields
3. Keeping flexibility where possible, therefore not making FHIR profile elements mandatory unless absolute certainty that this cardinality will apply for all existing and future use cases

**Comment by james-answer** [comment]
It might be moving the must-support guidance from "development_fhir_api_guidance.html" to be with the additional guidance for this issue as they seem relevant.

On the `feature/1.1.1` and `development` branchs I have added generic element population guidance, on the "development_fhir_resource_guidance.html" page, for population of the `address` elements. The additional guidance for this issue would probably sit well on the same page.

**Comment by james-answer** [comment]
Wording has been added to improve guidance around the population of optional fields.
