### ISSUE TITLE
Align GP Connect specification with Spine Core

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#417]
The Spine Core FHIR API specification,  [https://nhsconnect.github.io/FHIR-SpineCore/](https://nhsconnect.github.io/FHIR-SpineCore/), currently in Alpha,  describes common technical guidance required to successfully develop against National FHIR APIs for spine services.

As such there are a number of areas of commonality within the GP Connect specification. As the Spine Core specification is published it would be highly desirable to remove duplication of advice from the GP Connect site, and link appropriately to Spine Core.

This issue captures this requirement, and will detail areas where content will need to "migrate" to Spine Core.

**Comment by briandiggle** [comment]
System topologies content migrated to spine core. Merged "spine integration illustrated" and "system topologies" into one "overview" page

**Comment by RiChallinor** [comment]
Pending review of updated content and publication of updated Spine Core spec
