### ISSUE TITLE
Uplift the Bundle type to be document (and not searchset) in the GitHub & DMS

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#42]
This is for the Access Record DMS and $gpc.getcarerecord operation.

**Comment by michaelmeasures** [comment]
@farzanahnahid can we please include this change in the next version of the DMS.

**Comment by InteropAdmin** [comment]
Hi @michaelmeasures . I'm not sure I agree with this change as it does not align with the base FHIR specifications. probably best we have a chat to discuss the rationale behind this.

**Comment by michaelmeasures** [comment]
@InteropAdmin happy to have a chat, both James and myself have reviewed the FHIR standard and feel this change is consistent (and it has also been raised by the implementer community). From my perspective we've not returning a set of things (i.e. a searchset) we are always returning a single thing (a Composition populated inline with how a document would be). Marking it as a document gives implementers certainty that the Composition will be the first item in the Bundle and all links fan out from there - so in my opinion it simplifies the handling of the response payload. Can you please provide a link to the part of the FHIR specification that you feel we'd be misaligned on if we made this change.

**Comment by clarotech** [comment]
The definition of a document is not that a Composition is the first resource in a bundle, that's certainly a characteristic of a document but does not by itself make it a document.

Places you in the FHIR standard include :
https://www.hl7.org/fhir/valueset-bundle-type.html (look at the definition for searchset)

Also, admittedly not exactly the same but see the operation definition here: https://www.hl7.org/fhir/patient-operations.html#everything

Also refer to https://www.hl7.org/fhir/composition.html especially the penultimate paragraph of 6.8.2

**Comment by InteropAdmin** [comment]
The definition of a document is not that a Composition is the first resource in a bundle, that's certainly a characteristic of a document but does not by itself make it a document.

Places you in the FHIR standard include :
https://www.hl7.org/fhir/valueset-bundle-type.html (look at the definition for searchset)

Also, admittedly not exactly the same but see the operation definition here: https://www.hl7.org/fhir/patient-operations.html#everything

Also refer to https://www.hl7.org/fhir/composition.html especially the penultimate paragraph of 6.8.2

**Comment by james-answer** [comment]
@InteropAdmin For the "gpc.getcarerecord" operation the bundle type should be a "document" as it meets the criteria for being a "document" and does not meet the requirements for being a "searchset".

The main focus of the "gpc.getcarerecord" operation is the generated HTML included in the composition resource and  the other resources in the response bundle are there to support the html document, not as a direct result of the operation.

Looking at the links you have included, the first link for the definition of the "**Document**" type, the definition is "**The bundle is a document. The first resource is a Composition.**" This does not really define what makes it a document so from this alone yes we could not say that this is a "document".

For the "**Searchset**" type definition, "**The bundle is a list of resources returned as a result of a search/query interaction, operation, or message**.", the definition specifically states that the response should be a list of resources which all relate to the origional operation, or supporting resources for those resources. As for "gpc.getcarerecord" the only resource which is returned as a result of the origional operation is the composition and all the other resources are supporting the composition this does not make it clear if it should be a "document" or "searchset" either.

You linked to the "**fetch patient record**" page for the "everything" operation, which is very different to the "gpc.getcarerecord" operation and re-enforces the point made above. The "everything" operation just returns all the resources that relate to the patient and any supporting resources, it does not generate a new resource based on the requesting operation. In the gpc.getCareRecord operation the composition and HTML is generated based on the patient information and is not just a resource relating to the patient. This is why the "everything" operation is a bundle of type "searchset" but we expect the "gpc.getcarerecord"  response bundle to be a "document" as it is not just returning a set of resources based on the operation it is creating a document. But maybe you could still argue either way.

The third link to the fhir Composition reference page opens with a paragraph which perfectly describes the ouptup of the "gpc.getcarerecord" operation, 

"A set of healthcare-related information that is assembled together into a single logical document that provides a single coherent statement of meaning, establishes its own context and that has clinical attestation with regard to who is making the statement. While a Composition defines the structure, it does not actually contain the content: rather the full content of a document is contained in a Bundle, of which the Composition is the first resource contained."

The "gpc.getcarerecord" operation pulls together all the relavant patient data into a single html document and any other supporting information is also included in the response bundle. The HTML view is correctly being used as a document to create a Composition and the other resources are supporting resources, not a direct response to the origional operation call so this would clearly make it a response bundle of type "document" not "searchset".

**Comment by james-answer** [comment]
The decision was made on HDL-187 to stick with "searchset" rather thank "document". No spec changes required.
