### ISSUE TITLE
Correction to CareConnect-GPC-Patient-1

### ISSUE THREAD

**Issue by jlellison** [nhsconnect/gpconnect#420]
I have recently reviewed the Patient profile and have noticed that there is an extension (Nominated Pharmacy) that I have not localised properly for GPC use. Are you happy for me to make this correction?

**Comment by james-answer** [comment]
Do you mean the "https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-NominatedPharmacy-1" url being wrong?

@jackiebarnes I am not sure if anyone is populating it at the moment, do you think we need to talk to the providers? I think we should fix it for the 1.1.1 release.

**Comment by jackiebarnes** [comment]
Yes - agreed this needs to be fixed for 1.1.1;  confirm at mtg today

**Comment by jlellison** [comment]
Released to live https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1
