### ISSUE TITLE
GetStructuredRecord OperationDefinition change

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#426]
Hi Jen

We'd like to slightly change the GetStructuredRecord OperationDefinition:

https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-GetStructuredRecord-Operation-1

Could you look at the following changes?

1.  Make the includeAllergies.includeResolvedAllergies part parameter mandatory (1..1)?
2.  Make the includeMedication.includePrescriptionIssues part parameter mandatory (1..1)?
3.  Swap the order of the includeMedication.medicationDatePeriod and includeMedication.includePrescriptionIssues parameters so that includeMedication.includePrescriptionIssues comes first?

Many thanks
Jonny

**Comment by jlellison** [comment]
I have made the changes listed above and have released this to the test server https://fhir-test.nhs.uk/STU3/OperationDefinition/GPConnect-GetStructuredRecord-Operation-1. If you are happy with this I will release it to the production server.

**Comment by jlellison** [comment]
Released to live https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-GetStructuredRecord-Operation-1
