### ISSUE TITLE
AM: Practitioner Role Cardinality

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#427]
To meet functionality where a Provider system will have more than one Practitioner Role assigned to a slot, proposal is to change the cardinality of this element to 0..* Must Support rather than 0..1 Must Support

**Comment by jlellison** [comment]
This change has been applied and released to the server https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Schedule-1
