### ISSUE TITLE
AM Book Appt API - Should Booking Org Type be sent by Consumer

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#433]
In response to Provider request, to aid with the use of the 'Max number of bookable slots' in Slot filtering:

__If the Organisation Type is not included there could be concurrency issues when filtering if there is no way of ensuring that an organisation type hasn’t gone over its max bookable limit in the time between returning free slots in Search Free slots and then booking an appointment i.e two users at the same organisation do a search for free slots, one of them books an appointment which uses up all of the slots for their organisation type, how to prevent the second user from booking an additional appointment if re-validation can't occur  without the booking organisation type_ 

Of relevance:

- Search Free Slots API currently has sending the Booking Org Type as a 'Should', so this may not always be sent

**Comment by james-answer** [comment]
Org Type is currently within the Organization resource in the "type" element. Based on the requirement that if a consumer or provider has information they should populate it, if the consumer has a org type they should be populating it in the booking organization sent with the appointment resource.

We should probably add guidance to make the expectation clear that they SHOULD send it if they sent it with the search for free slots.
