### ISSUE TITLE
Delv Channel & Prac Role to Slot Profile rather than Schedule?

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#437]
Currently these elements are part of the Schedule profile rather than at individual slot level, on the basis that this provided more straightforward processing for Consumers and in the case of Prac Role, recognizes that there can be more than one Prac allocated to a Schedule, without this being recorded at Slot level.  The Prac role cardinality has been uplifted in the 1.1.1 release from 0..1 Must Support to 0..* Must Support.

Given that Providers may have Delv Channel currently at slot level and hence more than one Delv Channel within a Schedule, 
a) should the FHIR structure definitions be uplifted - ie move the element to the Slot resource
or
b) should the provider in this scenario create more than one Schedule representing the slots' different Delv Channels respectively

**Comment by jackiebarnes** [comment]
On the basis of Consumer simplicity, and not causing breaking changes, the option b) approach is recommended

**Comment by james-answer** [comment]
The decision has been made to keep the Practitioner Role and Delivery Channel on the schedule, due to it being a breaking change and that it would add complexity to the consumer. No specification update is going to be made.
