### ISSUE TITLE
Uplift documentation to highlight ValueSet mappings and their case sensitivity (or not).

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#44]
i.e. NHS data dictionary / data sets from the MIM era.

http://www.hl7.org.uk/repository/mim.asp

**Comment by michaelmeasures** [comment]
Testing should cover-off mapping from the GP2GP valuesets, to internal valuesets, back to external GPC valuesets.

**Comment by jackiebarnes** [comment]
Covered in various other tickets
