### ISSUE TITLE
Location - Population of 'Logical Id'

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#449]
The use case for this element is to enable the consumer system to  identify available slots at a Patient's preferred branch surgery;  the Location resource is referenced as the Preferred Branch Surgery on the Patient resource, and on the Schedule resource as the Location for the slots.

The element is not however a mandatory requirement, as with Name & Address, therefore needs to be.

**Comment by RiChallinor** [comment]
Create general rule on common resource guidance about logical ID population

**Comment by briandiggle** [comment]
https://www.hl7.org/fhir/resource.html#id
