### ISSUE TITLE
Structured operation definition changes

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#451]
Following discussions with Adam Hatherly, it has been agreed to amend the GP Connect GetStructuredRecord OperationDefinition.

[example payload.txt](https://github.com/nhsconnect/gpconnect/files/2154305/example.payload.txt)

Could you update the operation definition to align with this example payload?

(Note:  the following parameters are mandatory:  patientNHSNumber, sectionName.  The rest (including part parameters) are optional.

This will also require a valueset creating to bind to the sectionName parameter value.  It should hold the values 'allergies' and 'medication' with a name of 'GPConnect-StructuredRecordSection-1'.

Thank you.

**Comment by jlellison** [comment]
Hi @jonnyry, for consistency should both the section name values be plural, so 'allergies' and 'medication**s**'?

**Comment by jonnyry** [comment]
Hi @jlellison I think medication is OK and consistent as its the usual plural form of 'medication' anyway, though I know people do sometimes use 'medications' as the plural form.

**Comment by jonnyry** [comment]
Hi @jlellison After much discussion and due to the issues highlighted, we've decided to keep the existing definition.  Thanks very much for looking at it for us.  Cheers, Jonny.
