### ISSUE TITLE
Cancelling/Amending Guidance 

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#453]
Feel that an obvious question around whether an organisation can cancel/amend ANY appointment, and not just those which it has booked arises regularly and needs to be answered more explicitly in the specification, therefore:

Call out explicity on Design Decisions page and 'Use Case' sections of the above APIs that these actions can be performed on ALL appointments, not just those booked by the requesting organisation.

Likewise re access to ALL appts via Retrieve a Patient's Appts and Read Appt APIs

**Comment by RiChallinor** [comment]
@jackiebarnes to look at wording to make this more explicit in the guidance

**Comment by jackiebarnes** [comment]
Updated Design Decision pages;  please review

**Comment by jackiebarnes** [comment]
Updated opening para on Retrieve and Read API Use Case pages to indicate retrieval irrespective of booking org

**Comment by james-answer** [comment]
Wording change looks good and no more detail needs to be added as slot availability guidance says that the additional underlying slot availability only applies to search for free slots not the other capabilities.

**Comment by jackiebarnes** [comment]
Also amended opening para of Amend/Cancel appt

**Comment by james-answer** [comment]
Further changes look fine too.

**Comment by jackiebarnes** [comment]
Updated Release Notes pages with above
