### ISSUE TITLE
Tentative Slot Booking

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#454]
This business req is fulfilled via use of Book Appt, and then Cancel Appt if tentative booking not 'confirmed'.

Need to call this out more explicitly  in guidance on Design Decisions and Book Appt pages and  provide example of expected practice (or 'not-expected bad practice')

**Comment by briandiggle** [comment]
I think this has been considered in #386 

The API has been designed as a single stage booking API - though this has not been called out in the API. I.e. there is no concept of a "tentative" booking akin to reserving a slot prior to confirmation.

**Comment by RiChallinor** [comment]
@jackiebarnes to look at supporting wording around business scenario

**Comment by jackiebarnes** [comment]
Updated Design Decisions Page

**Comment by jackiebarnes** [comment]
Updated Release Notes page
