### ISSUE TITLE
Register a patient - duplicate requirement?

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#458]
Date of birth is required twice in the text at https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html#payload-request-body

I assume that there is no reason for this?

- The NHS Number and Date of Birth as a minimum SHALL be populated to enable a provider to perform a PDS trace.
- Where the gender, name or birth date are available these SHALL also be supplied (as indicated by the Must-Support FHIR property)

**Comment by RiChallinor** [comment]
Changed in 1.2.2 already. Close
