### ISSUE TITLE
Uplift API guidance to tie together / make clearer the expected default Date Range behavior.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#46]
Currently, we've agreed to return All when no date range is provided by the consumer. This could be made clearer in the API guidance.

**Comment by michaelmeasures** [comment]
It looks like the Design Decisions page around the handling of the default date ranges in the Access Record pack is out of date and needs updating.

https://nhsconnect.github.io/gpconnect/accessrecord_design.html#section-time-frames

**Comment by jackiebarnes** [comment]
Done these - see branch jackiebarnes-patch-2
