### ISSUE TITLE
Update Spine Core references to 1.0.1 after new Spine Core spec is published

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#460]

**Comment by briandiggle** [comment]
My thinking is that, since the versioned URLs to spine core are only major-minor (i.e. not patch), therefore when the release of spine core 1.0.1 is done, it will overwrite https://developer.nhs.uk/apis/spine-core-1-0/ and no changes will be required to links in the GP Connect FHIR API site.

**Comment by jonnyry** [comment]
Ah cool, OK will close this issue then.
