### ISSUE TITLE
FHIR server profile clean up

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#463]
The FHIR server on https://fhir.nhs.net

* has a number of out of date and unused GPC profiles
* and is missing some GPC profiles that are in use

**1.  Please could you remove the following unused profiles:**

| FHIR version  | Type | Profile name						 | Reason | 
|---------------|-----|--------------------------------|--------| 
| DSTU2		| StructureDefinition | GPConnect-Appointment-1			 | No Appointments in DSTU2 |
| DSTU2		| StructureDefinition | GPConnect-Slot-1					 | No Appointments in DSTU2 |
| DSTU2		| StructureDefinition |  GPConnect-Schedule-1				 | No Appointments in DSTU2 |
| DSTU2		| OperationDefinition | GPConnect-ScheduleOperation-1	| No Appointments in DSTU2 |
| DSTU2 		| Extension | Extension-GPConnect-Appointment-Cancellation-Reason-1	 | No Appointments in DSTU2 |
| DSTU2 		| Extension | Extension-GPConnect-Appointment-Created-1	 | No Appointments in DSTU2 |
| DSTU2 		| Extension | Extension-GPConnect-Booking-Organization-1	 | No Appointments in DSTU2 |
| DSTU2 		| Extension | Extension-GPConnect-Practitioner-1	 | No Appointments in DSTU2 |
| DSTU2		| OperationDefinition | GPConnect-RegisterPatient-1			 | No Foundations in DSTU2 |
| DSTU2 		| StructureDefinition | CareConnect-GPC-Patient-1			 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2		| StructureDefinition	| CareConnect-GPC-Organization-1     | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2		| StructureDefinition | CareConnect-GPC-Location-1	 	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| StructureDefinition | CareConnect-GPC-Practitioner-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | CareConnect-GPC-Practitioner-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | Extension-CareConnect-GPC-EthnicCategory-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | Extension-CareConnect-GPC-MainLocation-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | Extension-CareConnect-GPC-NHSCommunication-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | Extension-CareConnect-GPC-NHSNumberVerificationStatus-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | Extension-CareConnect-GPC-RegistrationDetails-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | Extension-CareConnect-GPC-ReligiousAffiliation-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | Extension-CareConnect-GPC-ResidentialStatus-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| DSTU2 		| Extension | Extension-CareConnect-GPC-TreatmentCategory-1	 | CareConnect aligned profiles not used in HTML DSTU2 |
| **STU3** 		| StructureDefinition	| GPConnect-CareRecord-Composition-1 | 	No HTML in STU3 |
| **STU3** 		| OperationDefinition	| GPConnect-CareRecord-Operation | 	No HTML in STU3 |
| **STU3** 		| CodeSystem	| GPConnect-RecordSection | 	No HTML in STU3 |
| **STU3** 		| ValueSet	| GPConnect-RecordSection-1 | 	No HTML in STU3 |
| **STU3** 		| OperationDefinition	| GPConnect-ScheduleOperation | 	Appointments STU3 went for a fully RESTful approach  |

**2. Please could you re-add the DSTU2 HTML profiles (or update where there is already an existing version)**

The DSTU2 HTML profiles in use are those in the original HTML DMS:

https://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord/Chapter.1.About/index.html

I believe the source of these profiles can be found at:

https://github.com/nhsconnect/gpconnect-fhir/tree/release/0.5.0

**Comment by jlellison** [comment]
I have removed the assets listed above from the staging and live servers. As part of the cleanup I will need to remove the STU3 Assets from our STU3 FHIR Assets repository. @jonnyry do you require a back up of any of these files?

I still need to look into re-publishing the DSTU2 assets to see if it is still possible to do this.

**Comment by jlellison** [comment]
Hi @jonnyry the profiles in the repository https://github.com/nhsconnect/gpconnect-fhir/tree/release/0.5.0 cannot be released to the FHIR server as they have a fhir.nhs.net url and the the server only allows profiles with a fhir.nhs.uk url.

**Comment by jonnyry** [comment]
Hi @jlellison sorry just seen your comments.

A backup would be useful of the STU3 assets thanks - perhaps one of the branches?

The DSTU2 assets can remain in the DMS I guess.  At some point we'll upgrade HTML to be STU3.

Thanks for your help on this.

**Comment by jonnyry** [comment]
Actually thinking about it, because we can't put the DSTU2 DMS assets on the FHIR server, we might as well remove the remaining GP Connect DSTU2 profiles from the FHIR server as they don't serve any purpose - Access Record HTML is the only capability which uses DSTU2 and the correct place to find those profiles is in the DMS and the gpconnect-fhir/release/0.5.0 GitHub branch.

Therefore please could you also delete:

**Comment by jlellison** [comment]
@jonnyry the remaining GP Connect DSTU2 profiles have been removed from the staging and live reference servers.
