### ISSUE TITLE
GP Connect Structured profile updates

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#464]
[Request from @PeteSalis @PeteSalisbury]

Can you make the following changes to our GPC structured profiles:

1.  In the List resource could the warning message valueset definitions be updated to match the associated text on the List page. (netlify link http://gpconnect.netlify.com/accessrecord_structured_development_list.html)

2. In the Medication Request profile can the PrescriptionType be made Must Support instead of mandatory

3. Add a slice to the identifier element to carry the cross care setting identifier which will be a GUID and the codeSystem will be https://fhir.nhs.uk/Id/cross-care-setting-identifier

In addition to these 3 changes we are waiting on confirmation of a valueset for the PrescribingAgency extension that was discussed at curation on Wednesday and Andrew Perry has taken away to put some SNOMED codes to. 

We are not sure how long this is going to take but dependent on that we may need you to add that in. If it is not done in time we will probably just add it to the ‘do not use’ fields in the guidance.

**Comment by jlellison** [comment]
Documentation of decisions made offline:

The identifier change is to MedicationStatement, MedicationRequest and AllergyIntolerance.

For the Prescribing Agency valueset Can we just have a FHIR code set with 2 values:
Prescribed at GP practice
Prescribed by another organisation

All prescription should be either one or another can we make the extension (prescribingAgency) Mandatory too.

**Comment by jlellison** [comment]
@PeteSalis The changes have been published to the staging server, can you have a quick look before I push them to live.
https://fhir-test.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-AllergyIntolerance-1
https://fhir-test.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-MedicationStatement-1
https://fhir-test.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-MedicationRequest-1
https://fhir-test.nhs.uk/STU3/ValueSet/CareConnect-ListWarningCode-1

**Comment by jlellison** [comment]
Changes published to the live server.
