### ISSUE TITLE
warningCode for Data awaiting filing

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#472]
The details relating to the warningCode for 'Data awaiting filing' on the List resource are out of date.

There was a decision made to change the requirements to how data awaiting filing could work. These are detailed in the business requirements. The acceptance criteria are,

'' - Where the provider system contains clinical data that has been electronically tranmitted to the GP practice system but has not yet been fully incorporated into the GP practice record (for example an electronic hospital discharge letter that requires a local review before being incorporated), the provider system must not return that clinical data.
- Where data has been excluded the following warning message must be returned. "Patient data may be incomplete as there is data supplied by a third party awaiting review before becoming available."

So needs to be brought in line with this.

**Comment by MikeStacey** [comment]
The requirements catalogue has now been updated. The exclusion requirement remains the same however the associated warning message has been removed.

**Comment by jonnyry** [comment]
Agreed with Mike and Pete.
