### ISSUE TITLE
Egton codes URI should be https://fhir.hl7.org.uk/Id/egton-codes

### ISSUE THREAD

**Issue by tim1ford** [nhsconnect/gpconnect#479]
EMIS have identified that the Egton codes URI is incorrect in 1.2.0.

Need to check with team before updating.

**Comment by Dunmail** [comment]
Code system should be added here as well: https://github.com/HL7-UK/System-Identifiers

**Comment by tim1ford** [comment]
Updated value in GP Connect spec:

https://github.com/nhsconnect/gpconnect/commit/f6e3799b7d7c05062a57ce85185abb5bc78f3a82

Confirmation of correct URI supplied by John George.
