### ISSUE TITLE
PrescriptionType in MedicationRequest is incorrect

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#494]
This should be a Required field with a cardinality of 0..1 and for the description which needs changing to the following,

If a medication is an acute, acute-handwritten, delayed acute, repeat or repeat dispense.
This field provides an explicit repeat/acute flag rather than deriving it from presence of extension elements or repeatNumber.
In exceptional cases where for legacy data there is no prescriptionType recorded in the system then this MUST be populated with the text ‘No information available’.

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/20bcfaf549f5cc3df321207a11cf24f4c5205140
