### ISSUE TITLE
GP Connect Interaction - GP Principal System Data-Sharing Model Implementation

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#5]
As Data-Sharing validation is being carried out by the Spine Security Proxy (SSP), GP Connect interactions must be responded to independently, and not change any locally-implemented data-sharing settings.  

This needs to be included in guidance, design principles etc.

**Comment by michaelmeasures** [comment]
@jackiebarnes I've closed this out as I believe this has been stated in the guidance now that any local data sharing functionality needs to be turned-off.

**Comment by briandiggle** [comment]
This is stated at 
https://nhsconnect.github.io/gpconnect/designprinciples_ig_principles.html 

"Organisational Data-sharing validation will be implemented by the Spine Security Proxy (SSP) and therefore Provider GP Connect go-live must not be dependent on local organisational data-sharing configuration to support this; local organisational data-sharing rules SHALL NOT be applied as part of GP Connect operation and SHALL NOT be changed as a result of GP Connect"
