### ISSUE TITLE
Cross Organisation Audit & Provenance needs updating to include machine readable FHIR profiles for the embedded FHIR resources in the JWT

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#50]
@ahatherly when we've got these can we review and then I can get them added into the correct repository.

**Comment by ahatherly** [comment]
@michaelmeasures : There are some draft profiles here:
http://fhir-test.nhs.uk/StructureDefinition/Audit-Patient-1
http://fhir-test.nhs.uk/StructureDefinition/Audit-Practitioner-1
http://fhir-test.nhs.uk/StructureDefinition/Audit-Organization-1
http://fhir-test.nhs.uk/StructureDefinition/Audit-Device-1
They are also in github here: https://github.com/nhsconnect/visitor-and-migrants/tree/develop/Audit

**Comment by james-answer** [comment]
There is not time to get STU3 profiles published before this release of the spec. We have added detail to the business rules to mandate required fields within the FHIR resources. We will look at adding profiles for the next release but if stratigic auth becomes available this will be used to generate the JWT.

**Comment by briandiggle** [comment]
We should hold off on adding programme specific profiles in the JWT as strategic authorisation solution may use base FHIR resources  - to which we are currently aligned.

**Comment by james-answer** [comment]
We are not going to update the JWT until the strategic auth solution has been created after which we will not have any control over the content of the JWT. As we are going to leave the JWT and FHIR resources in the JWT as they are until the stratigic auth solution is ready there is nothing to do for this issue and a new issue will be created for the uplift with integration of the stratigic auth solution, therefore I am closing the issue.
