### ISSUE TITLE
Update the Access Record capability pack to align with the final published DMS guidance.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#51]

**Comment by michaelmeasures** [comment]
We need to address the issue of thier being a mismatch between the NHS vs. FHIR communication/language value sets, as this is currently breaking FHIR DSTU2 compatibility.

**Comment by james-answer** [comment]
The new STU3 profiles use the FHIR language and communication valueset so this is no longer an issue, therefore closing the issue.
