### ISSUE TITLE
Move GPConnect-DeliveryChannel extension from Schedule to Slot

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#513]
Jen

After discussing with the suppliers, delivery channel is best located on Slot, rather than Schedule, as this fits with their data models.

Could you remove the Extension-GPConnect-DeliveryChannel-1 extension from the GPConnect-Schedule-1 profile, and re-add it to the GPConnect-Slot-1 profile with a cardinality of 0..1 ?

Many thanks
Jonny

**Comment by bushra** [comment]
Changes as requested above have been published to the live server, please see:
https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Schedule-1
https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Slot-1

**Comment by jonnyry** [comment]
Many thanks
