### ISSUE TITLE
Update guidance for MedicationStatement PrescribingAgency 

### ISSUE THREAD

**Issue by MikeStacey** [nhsconnect/gpconnect#514]
Update guidance for MedicationStatement PrescribingAgency to include include the following.

"For repeat and repeat dispensed mediations the value identifies the care setting where the medication plan (rather than any specific issue in the plan) was authorised."

**Comment by jonnyry** [comment]
@MikeStacey to review wordinig before publication

**Comment by MikeStacey** [comment]
Updated the wording, it just needs to be added at the end of the guidance for MedicationStatement PrescribingAgency.

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/d63c989c41c33134ac0bfbadcba7b121a2dc8273
