### ISSUE TITLE
Query - Degraded dm&d code when other code available

### ISSUE THREAD

**Issue by MikeStacey** [nhsconnect/gpconnect#518]
Current guidance says
In some cases, drugs may be recorded as free text or may be present in the original system’s drug dictionary, but not in dm+d. Where no dm+d code is available to describe the medication then the medication code MUST be expressed using the degrade (196421000000109, Transfer-degraded medication entry) with the original drug name present in CodeableConcept.text

However I thought we agreed a degraded code would only be used where there is no code available in any codeset, not when there was no SNOMED code available.

**Comment by jonnyry** [comment]
In agreement with Mike and Pete.
