### ISSUE TITLE
Delivery Channel and Practitioner Role not available after booking appointment

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#521]
The focus of delivery channel and practitioner role has been on the transmission of that data to the consumer so that they can choose an appropriate slot when booking an appointment. There is a shortcoming with the current requirement in that once you book that appointment there is no way of retrieving the delivery channel or practitioner role for the appointment as we do not have a slot or schedule read endpoint.

When you retrieve a patients appointment you only get the appointment resource back which has a reference to a slot but not the slot or schedule resource, on which the delivery channel and practitioner role are stored, therefore there is no way of knowing if it is a face to face, telephone or whatever appointment.

We probably need to include delivery channel and practitioner role on the appointment or expose additional endpoints.

**Comment by jonnyry** [comment]
Decision to add practitionerRole and deliveryChannel to the Appointment resource.

**Comment by jonnyry** [comment]
See https://github.com/nhsconnect/gpconnect/issues/530 for FHIR profile changes.

**Comment by jonnyry** [comment]
**Ensure release notes of 1.2.1 are updated**

**Comment by jonnyry** [comment]
Awaiting decision by @RiChallinor

**Comment by jackiebarnes** [comment]
Decision made by Programme that changes to be made for 1.2.1
