### ISSUE TITLE
Medications Prescribed Elsewhere                            

### ISSUE THREAD

**Issue by Jfadal** [nhsconnect/gpconnect#523]
The inclusion of a Medications Prescribed Elsewhere (MPE) was considered to be out of scope for HTML View specification release. Further investigation and clinical engagement has indicated that there is a significant need for this information in the HTML View.

**Comment by tim1ford** [comment]
The following section has been added to cater for prescribed elsewhere:

### Prescribed elsewhere ###

All subsections (except All Medication Issues) **MUST** include items which are recorded on the system as a prescription but prescribed elsewhere (for example, hospitals or special clinics) or ‘Over The Counter’ drugs taken by the patient and recorded on the system as a prescription. This Type column will identify a medication item as prescribed elsewhere by including the Agency Type after the medication type (Acute / Repeat) or ‘Unknown Prescriber’ where an agency type cannot be determined.
