### ISSUE TITLE
Medication Issues                                                       

### ISSUE THREAD

**Issue by Jfadal** [nhsconnect/gpconnect#524]
Feedback from EMIS clinicians' review.

There is a usability issue within the “Current Medication Issues” section. Specifically the handling of multiple entries for repeat medications (every issue is itemised). 

There is also the issue of the repeat medication entries and acute medication entries being bundled together, which makes it difficult for a clinician to review.

Feedback from FoT has highlighted that large amounts of data in the Current Medication Issues subsection of the Summary section reduces its effectiveness as a quick overview and risks subsequent subsections being overlooked.

**Comment by tim1ford** [comment]
The Medications page has been completed transformed in 0.7.0. following clinical review/sign-off.

Current Medication Issues has been replaced by Recent Acute Medications.

The following list of subsections now comprises the Medication view:

- Recent Acute Medication
- Current Repeat Medication
- Discontinued Repeat Medication
- All Medication (Summary)
- All Medication Issues

Please see the Medications page for further information.
