### ISSUE TITLE
Foundations APIs - PDS 'S-Flagged' Patients

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#526]
Update Find a Patient/Read a Patient API pages to align handling of S-flagged patients to the specification within Appt Mgmt - ie replacing the original req to replace the location dtls of an s-flagged patient with their registered GP details to a 'non-handling' of such patients - returning appropriate operation outcome message.

Also update AM Info Gov page wording - to specify 'Patient not Found' message

**Comment by jonnyry** [comment]
Yes, recommend removing the following as its no longer valid:

"If, in response to the Find or Read a Patient API, the provider system determines that a patient has a PDS 'S-Flag', then the patient's location and contact details are to be replaced by those of the target GP practice."

Also recommend adding information to say a consumer should not query GP Connect APIs if it receives an S Flag for a patient from PDS and/or DBS.

**Comment by jackiebarnes** [comment]
Have made amendments to AM IG and Foundations IG pages;  Jonny reviewed Foundation's Page
