### ISSUE TITLE
S-Flag patients to return Patient Not Found in ARHTML

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#528]
Version 0.5.0 of ARHTML HTML implementation standards states that demographic details are to be redacted for patients which are S-flagged on Spine e.g. 'May be redacted if patient is flagged on Spine as Sensitive demographics.' This has been queried and subsequently changed in other capabilities for providers not to return patient records for S-flagged patients but to return a 'Patient Not Found' error.

Change the HTML implementation standards section to include this requirement:

Patient has informed the NHS that their location information is not to be shared

Where a patient is flagged on the GP Clinical System as sensitive (and as such the GP practice must not identify that the patient is registered at this location), the provider system must not return any clinical records and instead return the error "Patient not found"

Where a patient is flagged on PDS as sensitive (and as such it is not possible to confirm their registered GP practice), the consumer system must not use GP Connect

**Comment by tim1ford** [comment]
All redacted statements have been removed.

The following text has been added:

Where a patient is flagged on the GP clinical system as sensitive (and as such the GP practice must not identify that the patient is registered at this location), the provider system **MUST NOT** return any clinical records and instead return the error `Patient not found`.

Where a patient is flagged on PDS as sensitive (and as such it is not possible to confirm their registered GP practice), the consumer system **MUST NOT** use GP Connect.
