### ISSUE TITLE
Appt Resource - Add Extensions (Data Standards)

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#530]
The Practitioner Role and Delivery Channel extensions on the Schedule/Slot Resources respectively need to be added with the same cardinality and Must Support flags etc to the Appointment resource, so that when the Retrieve/Read Appointments APIs are sent, these elements will be populated by the Provider systems in their response.

**Comment by jonnyry** [comment]
[ See https://github.com/nhsconnect/gpconnect/issues/521 for spec change. ]

**Comment by jackiebarnes** [comment]
Awaiting program decision re implementation of this change

**Comment by jackiebarnes** [comment]
Changes made on FHIR server;  release notes updated
