### ISSUE TITLE
Reason for discontinued and cancelled medication

### ISSUE THREAD

**Issue by Jfadal** [nhsconnect/gpconnect#531]
It   is extremely important for the details regarding the ending of a medication   to be available to a clinician, as this will highlight any clinical issues   (e.g. stopping a medication due to an allergy etc.) and allow the clinician   to make an efficient and informed clinical decision.       Specification   v0.5 only requires a cancelled / discontinued and date to be included in the   Details column. The reason is not specified as required.       “Where   the medication was cancelled (Acute) or Discontinued (Repeat), this should be   included in the Details column as Cancelled followed by Date of Cancellation   or Discontinued, followed by Date when discontinued.”
--

**Comment by tim1ford** [comment]
The Medications page has been completed transformed in 0.7.0. following clinical review/sign-off.

Requirements for discontinued an cancelled reason have been added, where applicable.

Please see the Medications page for further information.
