### ISSUE TITLE
Current is not explicitly defined for medication subsection content

### ISSUE THREAD

**Issue by Jfadal** [nhsconnect/gpconnect#532]
It is imperative that the application of rules for the placement and transition of individual medication item entries within the 3 sub sections is clearly understood and any mitigating text is appropriately provided.

Currently this is not the case, therefore a clinician will get differing views depending on the supplier providing the data (and potentially the specific GP Practice where a local configuration setting can determine the age for ‘current’) and there is no text explaining the differences.

**Comment by tim1ford** [comment]
The Medications page has been completed transformed in 0.7.0. following clinical review/sign-off.

Each subsection now contains greater detail as to what is being displayed.

Please see the Medications page for further information.
