### ISSUE TITLE
Separate the dosage information from the medications details columns

### ISSUE THREAD

**Issue by Jfadal** [nhsconnect/gpconnect#533]
Clinician   feedback has highlighted that it would be useful to have a separate dosage   column across all of the medications sub sections. The information is   currently available within the text about the medication item, making this a   usability issue.       The   availability of a separate dosage column makes it easier or a clinician to   ‘compute’ and make clinical assessments and decisions.
--

**Comment by tim1ford** [comment]
Separate `Dosage Instruction` and `Quantity` columns have been provided following clinical feedback/sign-off.

See the Medications page for more details.
