### ISSUE TITLE
Add a definition for the application of decimal places for numeric values

### ISSUE THREAD

**Issue by Jfadal** [nhsconnect/gpconnect#534]
First of Type feedback has noted that some values are presented to a number of decimal places which could misrepresent the accuracy of recording or make it less user friendly to read the values e.g. in the Observations section.

**Comment by tim1ford** [comment]
Section added to the Implementation Standards page to add CUI reference to Medication Representation documentation:

### Medication representation ###

[Medications Management - Medication Line](http://webarchive.nationalarchives.gov.uk/20160921150545/http://systems.digital.nhs.uk/data/cui/uig)

Updated in https://github.com/nhsconnect/gpconnect/commit/588285e0d1090b48af93f92c7593cb63f362d6c2

**Comment by tim1ford** [comment]
Specifically page 5 of in this PDF:

http://webarchive.nationalarchives.gov.uk/20160921162642/http://systems.digital.nhs.uk/data/cui/uig/medlineqig.pdf
