### ISSUE TITLE
Separate section related guidance from the general guidance in the html implementation guide

### ISSUE THREAD

**Issue by Jfadal** [nhsconnect/gpconnect#535]
The html implementation guidance has a mix of general / technical guidance and guidance relating to the sections. Various changes are covered by other tickets which requires additional content and some re-ordering of the content. The section related guidance (e.g. defining the layout of the sections) may be more readily accessible to the site user if it was moved to a new first section within the ‘html views’ section.

**Comment by tim1ford** [comment]
The HTML Implementation Guidance page has now been split into the following two pages:

- Implementation standards
- Layout guide

The content of each has been reviewed and updated.
