### ISSUE TITLE
Uplift Access Record pack with more detailed guidance around handling patient in transit conditions

### ISSUE THREAD

**Issue by adamjlees** [nhsconnect/gpconnect#54]
GP Connect request to "new GP" scenarios
1. This is my patient, previous GP data "not integrated" yet via GP2GP, no new GP data added from new practice
2. This is my patient, previous GP data "not integrated" yet via GP2GP, some new GP data added to record from new GP.  

GP Connect request to "old GP" scenarios:
1. not my patient, but GP data not yet integrated into new practice system
2. not my patient, GP data fully integrated into new practice system.

**Comment by michaelmeasures** [comment]
We also need to consider manual transfer of patient records in transit as the time-frames on these could be much longer than the GP2GP mechanism.

**Comment by adamjlees** [comment]
assign to Russell once registered

**Comment by adamjlees** [comment]
@rbutterf As you're writing manual test scenarios you'll be aware of the requirements.  Will show you how to make commits to the repo.

**Comment by jackiebarnes** [comment]
now dealt with in #391
