### ISSUE TITLE
Verbosity of GPConnect-DeliveryChannel-1 extension

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#544]
Since the delivery channel extension is now attached to Slot rather than Schedule and so will be more populous in the Search for free slots call, it's serialised size is more important.  The delivery channel extension uses the CodeableConcept which contains several superfluous fields for our usage.  This extension should be changed to use a Code rather a CodeableConcept in order to reduce the size of the extension and the overall search for free slots payload size.

Therefore the following profile changes are required:

1. Create Extension GPConnect-DeliveryChannel-2 with the element datatype code and bind to existing GPConnect-DeliveryChannel-1 valueset.
2. Update GPConnect-Appointment-1 – minor version change
  a. Add the Extension DeliveryChannel-2 to Appointment with cardinality 0..1 and must support flag
  b. Remove Extension DeliveryChannel-1
3. Update GPConnect-Slot-1– minor version change
  a. Add the Extension DeliveryChannel-2 to Appointment with cardinality 0..1 and must support flag
  b. Remove Extension DeliveryChannel-1

**Comment by jlellison** [comment]
The changes have been made and the release has been prepared in branch https://github.com/nhsconnect/STU3-FHIR-Assets/tree/release/GPCAppointments1-2-1(2). As discussed I will release this when the server environments stabilise.

**Comment by jlellison** [comment]
This has now been released to the server.
