### ISSUE TITLE
Uplift "integrate with pds" with more guidance around how PDS sensitive patients are to be handled

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#55]

**Comment by adamjlees** [comment]
Uplift accessrecord_design and integration_personal_demographic_service

PDS response for patients flagged as having sensitive demographic redacts location (address, postcode) and contact (email, telecoms) information, but also removes GP Practice information.  This makes it impossible for consumers to resolve the FHIR endpoint.  A workaround will be allowed for consumers to use ODS code from locally-held GP registration information to perform the SDS query.

**Comment by michaelmeasures** [comment]
Would be good to include a few solution architecture topologies with details of how these requirements can be met in each circumstance.

**Comment by jonnyry** [comment]
Duplicate #391.
