### ISSUE TITLE
Rules for provider return when default date range is not all items

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#550]
The specification supports application of a default date range, but the specification does not include the business rules for applying a default date range other than where the default is ALL items.
The specification should include rules and date banner message definitions for an applied default date range. 
This is further to #114 and #162

**Comment by RiChallinor** [comment]
@martinhillyard has this been done in recent work?

**Comment by martinhillyard** [comment]
@RiChallinor This is under review with the intention of adding further definition - see JIRA GPC-630.

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/d6f90630d80a5e4920c3be341fdad3d272e31b09
