### ISSUE TITLE
GPC Spine error response codes

### ISSUE THREAD

**Issue by swk003** [nhsconnect/gpconnect#554]
There are some GPC Spine error response codes specified in the [error handling guidance](https://nhsconnect.github.io/gpconnect/development_fhir_error_handling_guidance.html) section that are not supported in the ValueSet: [Spine Error Or Warning Code](https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1).  These are: 

INVALID_PATIENT_DEMOGRAPHICS
NOT_IMPLEMENTED
REFERENCE_NOT_FOUND

Apologies if this has already been logged.

**Comment by jonnyry** [comment]
Updated release notes to describe change to valueset.

Awaiting change to valueset before closing ticket.

**Comment by swk003** [comment]
@briandiggle @jonnyry - We are happy to add codes to valueSet. I have assigned task to Jen. Thanks

**Comment by jlellison** [comment]
Released to the Reference Server
