### ISSUE TITLE
Provide additional guidance for display of numbers with decimal places

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#555]
Guidance has been provided for the display of numeric values to decimal places for medication items and included in the observations specification for the numeric values for such test and measurement results.
This states "Do not put a trailing zero after a sub-decimal value (that is, ‘0.5’ is correct but ‘0.50’ is incorrect)". 
Should the guidance be expanded for display of numeric values for observations and any other circumstances than medications to allow a trailing zero(es) ONLY where that represents the degree of accuracy to which the reading was made and the unit is already the lowest level e.g. 4.0 mmol/L is valid if the measurement is taken to a level of accuracy of .1 mmol/L and that degree of accuracy is retained in the provider system (i.e. it has been stored as 4.0 and not 4).

**Comment by RiChallinor** [comment]
@martinhillyard has this been done with recent work?

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/a9807ca2f503996b17a01f7f82facd07b28c019e

and https://github.com/nhsconnect/gpconnect/commit/85575b0359ea80b523dfc8691f52ecdf01a2a8b0
