### ISSUE TITLE
FHIR Resources List cardinality for id and meta.profile are wrong

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#557]
The cardinality for Id and meta profile should be 1..1 as the items are Mandatory but on the page they are currently listed as 0..1.

**Comment by jonnyry** [comment]
The cardinality on the underlying profile is 0..1.  Do you want the elements on the profile updating to be 1..1, as well as the documentation?

**Comment by PeteSalis** [comment]
@RiChallinor Discussed with @jonnyry  that it is probably the best course of action to update the guidance to say mandatory and leave the profile as optional. This means that we are specifying via our guidance that this will be populated and can test for it but that if at some point we may need it not to be populated for writeback then we won't have to change the profile.
Happy to update to go in the next release but not uptodate with when it's planned for.

**Comment by PeteSalis** [comment]
Updated as per above.
