### ISSUE TITLE
Foundation Resources - element exclusions and population guidance

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#558]
New ticket created to represent the work required to ensure that only those optional personal data FHIR elements for which there is a specific use case/user story, are populated by the Providers/Consumers.

Take into account information in previous tickets:
#403
 #441

Patient, Practitioner, Appointment, Schedule, Slot elements (ie fields/attributes) to have speedy use case review and validation by team and Clinical Input Ref Group.  Seek input also from CareConnect team as to any previous work already done.

**Comment by RiChallinor** [comment]
For 1.2.2 high priority to call out explicitly which elements not to populate

**Comment by jonnyry** [comment]
In anticipation of use case review, have added requirement to not populate the following elements on the Patient resource:

 - SHALL NOT populate `ethnicCategory`, `religiousAffiliation`, `patient-cadavericDonor`, `maritalStatus`.

This requirement has been added to the Read a patient, Find a patient and Register a patient pages.

It can be amended as the use case review concludes.

**Comment by jackiebarnes** [comment]
The elements to be excluded are:

**Patient**
Ethnic Category
Religious Affiliation
Donor Indicator
Residential Status
Treatment Category
Place of Birth
Marital Status
Multiple Birth Indicator

**Practitioner**
Telecom 
Address
Birthdate
Photo
Qualification

**Appointment, Schedule, Slot**
Specialty
