### ISSUE TITLE
/Patient/$gpc.getstructuredrecord not working

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect#562]
I'm trying to retrieve structured records via swagger interface 

https://orange.testlab.nhs.uk/swagger/v1/#/

This is returning 500 error "text": "Failed to call access method". 

Also getting the same from a client I'm getting 
"text":"Failed to parse request body as XML resource. Error was: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'\r\n at [row,col {unknown-source}]: [1,1]"

tried on NHS Number 9476719931

**Comment by jonnyry** [comment]
Closing as resolved with Kev.
