### ISSUE TITLE
GPConnect-GetStructuredRecord-Operation

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#565]
The output Bundle is listed with a profile URL of:

`https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-GetStructuredRecord-Bundle-1`
 
Whereas the actual Bundle has a profile URL of:
 
`https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-StructuredRecord-Bundle-1`
 
Could you change the Bundle URL in the OperationDefinition to reflect the actual profile URL?

**Comment by jlellison** [comment]
Released to the Reference Server
