### ISSUE TITLE
Location & Organization 'must support' elements

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#566]
Jen

Could you make the Location name, address, telecom and managingOrganization elements 'must support' please?

Could you also make Organization name, address and telecom 'must support' please?

Thanks
Jonny

**Comment by jlellison** [comment]
Hi @jonnyry I have added the must support flag to Organization address and telecom. Organization.name is 1..1,  do you still want the flag adding to this element?

**Comment by jlellison** [comment]
Released to the Reference server
