### ISSUE TITLE
List & Bundle meta.profile cardinality

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#578]
Could the meta.profile cardinalities to be changed from 0..1 to 1..1 on the following profiles?

https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-List-1
https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-StructuredRecord-Bundle-1

Thanks

**Comment by jlellison** [comment]
Hi @jonnyry meta.profile is 0..* in the base so I would advise changing this to 1..* instead of 1..1. Please can you confirm the cardinality you want to go with? Thanks Jen

**Comment by jonnyry** [comment]
Hi Jen, good point - 1..* makes the most sense.

Thanks.

**Comment by jlellison** [comment]
Published to the reference server

**Comment by jonnyry** [comment]
#557
