### ISSUE TITLE
Patient contacts - Emergency, NOK, Carer

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#583]
Population of these hasn't been specifically called out for:

- Find a patient
- Read a patient
- Register a patient (request or response)

Are we expecting these to be populated?

Should it be explicitly ruled out or in?

If not explicitly ruled out, then do we need to mention:

“Contact covers all kinds of contact parties: family members, business contacts, guardians, caregivers. Not applicable to register pedigree and family ties beyond use of having contact.”

Is it an issue that these can only be sent where register a patient is called?

Also see #444 #412

**Comment by jackiebarnes** [comment]
Confirm that we need a 'good practice' caveat to underline the purpose of why this information is to be populated - to support key contact individuals, eg Next of Kin,  Carer, Next of Kin or Emergency

**Comment by jonnyry** [comment]
See https://www.hl7.org/fhir/patient-definitions.html#Patient.contact

**Comment by jackiebarnes** [comment]
Agreed that:
the information for a patient's Carer, NoK, Emer Contact etc is required, therefore the element should not be explicitly excluded either from Consumer or Provider
need to review and obtain agreement from Clin Ref group re which sub-elements are reasonable and proportionate to populate
instances of a Patient Contacts to only reflect what is obtained directly from the Patient's record rather than from other db table sources
formulate and obtain clinical approval of wording to guide this population

**Comment by jackiebarnes** [comment]
Had agreement from Clin Ref Group of 23/10/18 for the following:

•	Not to be populated by Consumer, given data model does not support this – Consumer only sends the Patient resource carrying this info when Registering a Patient, so if an existing active record at target GP practice, then wouldn’t be sent – therefore inconsistent 
•	Only information obtained directly from the Patient’s record – ie not constructed from other locations where information may be recorded – related to material contacts – not family tree
o	The Patient.contact element SHALL be populated where demographic information is available in the Patient record for those individuals who may need to be contacted in connection with the Patient’s appointment.  In accordance with the FHIR definition, it is “Not applicable to register pedigree and family ties beyond use of having contact”.
•	No elements excluded 
•	For Patient.contact.relationship - only populate Patient.contact.relationship.text  - which would include indication where available of Next of Kin etc
