### ISSUE TITLE
Bring Patient / Practitioner / Organization resources in line in Structured Bundle examples

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#584]
The Structured examples containing Patient, Practitioner, Organization resources are not in line with those in the Foundations capability.

Also remove the "display" element from fields that are references - only the "reference" element should be populated.

Ensure "Patient.generalPractitioner" field is populated as per structured requirements.

**Comment by tim1ford** [comment]
https://github.com/nhsconnect/gpconnect/commit/eb91479550aa936f2f20f6c6a92214308aaf53ab

**Comment by tim1ford** [comment]
Final versions uploaded to develop branch 

https://github.com/nhsconnect/gpconnect/commit/b1a952a1a315db92813320edcb413c7f65a0c578
