### ISSUE TITLE
PDS cross check

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#589]
Check that cross check returns full demographics in order that registration details can be populated

**Comment by tim1ford** [comment]
Full demographics are returned by the full PDS cross check. 

The mini service supports the full demographics by returning the getPatientDetails payload, which can be requested by any of the following:

- getPatientDetailsBySearch
- getPatientDetailsByNHSNumber
- getPatientDetails

See attached pdf for the full cross check response.

[CrossCheckTraceResponse Tabular View.pdf](https://github.com/nhsconnect/gpconnect/files/2514315/CrossCheckTraceResponse.Tabular.View.pdf)

See the attached for the mini service details:

[PDS - Spine Mini Service Provider Requirements-v1.0.pdf](https://github.com/nhsconnect/gpconnect/files/2514331/PDS.-.Spine.Mini.Service.Provider.Requirements-v1.0.pdf)

**Comment by jonnyry** [comment]
Cross Check Trace brings the set of demographics associated with a trace back, which is a smaller set than returned by a Retrieval - so need to:

* Either do a Retrieval and perform a cross check manually using the demographics returned
* Or do a Cross Check Trace, following by a Retrieval
