### ISSUE TITLE
EXAMPLE/DUMMY CLINICAL RISK ISSUE: Incomplete Record Displayed

### ISSUE THREAD

**Issue by pacharanero** [nhsconnect/gpconnect#595]
**this is a dummy issue created to illustrate how we could possibly use an issue tracker to manage the clinical risk process**

## Description
Partial or full elements of the intended Patient Record are not adequately supported by the GET_RECORD API specification. (wrong or incomplete specification)

## Clinical scenario and _potential impact_
A health care professional may not be fully aware of required patient conditions, history or other key data elements. This may lead to delayed or inappropriate care. This may also result in an incorrect assessment being made if incomplete data elements are not detected.

## Mitigations

- [x] this needs to be done
- [x] this also needs to be done

##

**Comment by pacharanero** [comment]
review meeting today

actions for @pacharanero:
* [ ] one
* [ ] two

actions for @jonnyry 
* [ ] something else

**Comment by pacharanero** [comment]
@jonnyry you can ignore anything in this dummy issue - i'm showing Cath J how we could use GH for clinical risk tracking using issues

**Comment by Dunmail** [comment]
@pacharanero 👍 for looking at tracking issues in the open!

**Comment by pacharanero** [comment]
I woke up in the middle of th night with an idea about this - can't we just do what they did in SCR?

**Comment by pacharanero** [comment]
@Dunmail we're just testing out the functionality and doing a dummy run through a clinical risk review round with a colleague
