### ISSUE TITLE
Fix menu styling in 0.5.1

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#598]
Menu styling / CSS seems to have gone awry in 0.5.1 - compare with previous 0.5.0:

https://gpconnect-0-5-0.netlify.com
https://access-record-html-0-5-1.netlify.com

**Comment by tim1ford** [comment]
Fixed by realigning the theme-blue.css

https://github.com/nhsconnect/gpconnect/commit/c35efe87f368d88b62881248286c36f619a99f67
