### ISSUE TITLE
GP Connect Postman collection does not have the correct environment variables with it

### ISSUE THREAD

**Issue by pacharanero** [nhsconnect/gpconnect#599]
The Postman collection here https://nhsconnect.github.io/gpconnect/system_reference_postman.html does not have the environment variables included.

**Comment by jonnyry** [comment]
@pacharanero This has now been fixed - the Postman button on the spec (https://nhsconnect.github.io/gpconnect/system_reference_postman.html) and on the demonstrator (https://orange.testlab.nhs.uk/) now imports the examples plus the environment variables.

Let us know if you are still experiencing an issue.
