### ISSUE TITLE
Uplift the guidance to include explicitly which fields from the structured patient record should be utilised to cross-check demographics.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#60]

**Comment by michaelmeasures** [comment]
https://nhsconnect.github.io/gpconnect/accessrecord_development_html_implementation_guide.html#demographic-cross-checking is the page which needs uplifting.

**Comment by adamjlees** [comment]
Returned from SMSP (so is pointless for provider to return more than this for comparison purposes)

Name, NHS Number, Gender, Birth Date, Address (main)
Contact( Telephone, Mobile and emails)
GP (Practice Code, Name and Address)
