### ISSUE TITLE
Patient Nominated Pharmacy

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#602]
This extension may not be populated given lack of Appt Mgmt use cases;  ongoing need for this element to be reviewed as part of upcoming Structured data requirements analysis

**Comment by RiChallinor** [comment]
@MikeStacey can this be closed?

**Comment by MikeStacey** [comment]
This will be looked at when we look at demographic data in the structured work. Depending on how well we progress that should be in the second half of this year.

**Comment by mstephens-xsl** [comment]
This information is held on PDS and can be accessed there.
