### ISSUE TITLE
Search for free slots - consumer display requirements

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#606]
**Update Feb 2019**:  the 2019 GMS Contract, aligning to the NHS LTP, is intentionally describing the offering of appointments via GP Practices delivered by other healthcare professionals, including physios, pharmacists etc.  Consumers need to therefore be displaying this information being returned from Provider systems.

Given that:
- the Prac Role and Delv Channel were included as mandatory requirements in the spec for Providers to support as part of their schedule/slot data model, so that more useful, standardised information about the available appt slots could support more accurate/appropriate appointment booking
- TPP consumer has not displayed the practitioner role and delivery channel information sent by the Provider on the retrieved slots (included as mandatory attributes)
- Advanced asking whether this was required by the spec for the Adastra consumer

No value added here and pointless mandatory req on Providers if Consumers don't display to their end-users;  **propose that the spec be uplifted to include the requirement on the consumer to display this information**

**Comment by jackiebarnes** [comment]
Location,  "please be aware" - guidance

**Comment by jonnyry** [comment]
@jackiebarnes Please see the following for review:

https://gpconnect-1-2-3.netlify.com/appointments_use_case_search_for_free_slots.html#consumer-display-requirements

**Comment by jonnyry** [comment]
Spec meeting:

Reword:
  - start date and time
  - duration and/or end date and time

Change wording:
  "SHALL support the follow fields"
