### ISSUE TITLE
Clarify meaning of organisation groups in Appointments Availability Management

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect#608]
Raised in Vision workshop: Is the spec clear that management of org groups is done by ODS code. To review current wording in the spec.

**Comment by jackiebarnes** [comment]
Potential Changes:
Slot Avail Mgmt page - Additional Provider Reqs :
Add additional bullet in the Appt avail control section of 'Provider systems SHALL'
Suggest
"- ensure ODS code is used as unique org identifier for organisations in the organisation grouping functionality"

**Comment by jonnyry** [comment]
As discussed with @jackiebarnes also change the name of organisation groups to organisation lists, as these are essentially just lists of organisations, and do not have any implied hierarchy as may be inferred from the word group.
