### ISSUE TITLE
Find and fix any broken links in the Access Record pack prior to cutting the final version.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#61]
When NHS Digital updated there website it broken a number of links across the GitHub site. This included the links to the Common User Interface guidance and likely others. Hence, they need to be fixed up to point to the new location.

**Comment by michaelmeasures** [comment]
@adamjlees can you please put the links here for the new CUI guidance location that you've discovered on the National Archives. cheers!

**Comment by adamjlees** [comment]
Link to main list
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig

Patient Banner
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/patben.pdf

Patient name
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/patnamedisp.pdf

Time display
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/timedisplay.pdf

Date display
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/datedisplay.pdf

Date/time input
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/datetime.pdf

Address input and display
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/address.pdf

Sex and gender input and display
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/sex.pdf

NHS No input and display
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/inputdisplay.pdf

Telephone number input and display
http://webarchive.nationalarchives.gov.uk/20160921135207/http://systems.digital.nhs.uk/data/cui/uig/tele.pdf

**Comment by jonnyry** [comment]
Fixed links in 0.5.0 and AccessRecordHTML feature branch.
