### ISSUE TITLE
Patient Identity - Demographic Cross-Checking

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#612]
Currently the spec details that the following elements received from the Provider MUST be checked by the consumer - see https://nhsconnect.github.io/gpconnect/development_general_api_guidance.html#demographic-cross-checking

Family name | patient.name.family
Given name | patient.name.given
Gender | patient.gender
Birth date | patient.birthDate

This is potentially overloading the checking requirements on Consumers who are already using full PDS connectivity for ID checks and PDS retrieval, therefore recommend that the spec is amended to accommodate the following option:

_Where a consumer supports full read/write PDS and therefore synchronises demographics with PDS, then the following demographic cross check (based on the PDS Cross Check Query) will be suitable:
 
Perform a cross check of key fields between consumer and provider
 .	The patient’s identity is considered confirmed across the two systems if:
o	The NHS number and the date of birth returned by the provider exactly match the date of birth and NHS number held by the consumer
 .	OR should 2 out of 3 parts of the date of birth match (a single ‘part’ being CCYY, MM or DD)
o	AND the first 3 characters of the Family Name (Surname) match and the initial character of the First Given Name (Forename) match
 .	If both of the above checks fail to find a match then the patient’s identity could not be confirmed and the transaction does not proceed_

**Comment by jsmrkhm** [comment]
This requirement is also a possible concern for us, where our product's integration config doesn't provide capability to add user interaction. We can either a) return results, b) return a static/boiler plate error message or c) return no results.

We only consume GP Connect APIs for patients with T&V NHS numbers on the assumption that this provides sufficient confidence that a match is reliable. T&V status is retrieved via the PDS Cohort Management interface. However, we do not have full read/write PDS integration.

Can any change to the the documentation include clarification that this is/is not sufficient, please?

**Comment by rajiv-bhatia** [comment]
The specs already mandates the consumer to first get the patient details from PDS. So, in most of the cases, the consumer system will have the same patient details as the GP.
But in rare cases where the GP system has not yet sent updates to PDS, the consumer system may have different patient details. In this case, consumers are required to highlight any differences in details from PDS and those from GP, to the end user.
https://developer.nhs.uk/apis/gpconnect-1-5-0/development_general_api_guidance.html#managing-return-content
If the consumer, at this point, performs further cross checks with PDS, it may still not return the updated details.
So, the current guidance is sufficient for the given scenario.
