### ISSUE TITLE
Provider variance - add EMIS line item redaction text

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#614]
Following implementation of #604 update the EMIS line item message in the Exclusion banner message table could be updated to include their redaction text. EMIS return either 'Confidential Item' or 'Sensitive Item' according to the reason for the exclusion

**Comment by RiChallinor** [comment]
@tim1ford has this been done in recent work?

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/47642a07b16f344521bda00cee892bb24edee0b4
