### ISSUE TITLE
Change spec name of "GP Connect" to "GP Connect API"

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#616]
This is to co-ordinate with the new release of the GP Connect Messaging specification.

**Comment by RiChallinor** [comment]
@jonnyry to do this week.

**Comment by tim1ford** [comment]
Uplifted on release branches:
0.5.1
0.7.1
1.2.2

Jenkins jobs have not been run to update on Developer Network yet.

**Comment by jonnyry** [comment]
In 1.2.3, changed spec name on:

- site name in _config.yaml (now GP Connect API - FHIR&reg; APIs for GP IT systems)
- page title on index.html
- page title on overview_engage.html
- page title on overview_priority_capabilities.html
- page title on release notes

**Comment by jonnyry** [comment]
No demonstrator or test suite changes expected.
