### ISSUE TITLE
HTML Broken Link

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#617]
In the section Development > API use cases > Retrieve a care record section, the link in the paragraph 'Refer to HTML Implementation Guidance - Per Section Default Time Frames for details of the default time periods that MUST be applied per care record section.' is not direct to the referenced content.

Current link is to 
https://developer.nhs.uk/apis/gpconnect-0-5-1/accessrecord_development_html_implementation_guide.html#per-section-default-time-frames

Direct link would be to
https://developer.nhs.uk/apis/gpconnect-0-5-1/accessrecord_development_html_layout_guide.html#per-section-default-time-frames

**Comment by tim1ford** [comment]
Fixed in both 0.5.1 and 0.7.0
