### ISSUE TITLE
Changing casing of patientNHSnumber parameter in GPConnect-GetStructuredRecord-Operation-1 

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#618]
Change the name of the NHS number parameter to “patientNHSNumber”, so that the ‘N’ in ‘Number’ is in capitals.

The Access Record HTML Operation Definition is cased that way, and also our examples in the specification for Access Record Structured are cased that way.

Changing the ‘N’ in ‘Number’ to capitals in the Operation Definition will bring everything in line.

**Comment by jlellison** [comment]
Change made and released to the reference server https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-GetStructuredRecord-Operation-1
