### ISSUE TITLE
Uplift the PDS and $gpc.getcarerecord guidance to make it clear how to handle superseded record access.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#62]
Please see https://nhsconnect.github.io/spine-smsp/demographics_reqs.html

- DEMOG-0007
- DEMOG-0022
- DEMOG-0040
- DEMOG-0042

Should all trigger an error and NOT return the patient's record.

As specified we only return active and traced patient records.

In the case of a superseded the latest active and traced patient record SHALL be returned.

- DEMOG-0017

**Comment by jonnyry** [comment]
Incorporated into Overarching PDS/DBS guidance #391
