### ISSUE TITLE
Remove use of work and old address for register patient

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#620]
Addresses with 'Use' value of Work cannot be stored by all Providers;  'Work' telecoms can be stored.

This means that either:

- Consumer-sent data is silently 'lost
- Providers should store this to a 'Notes' field if available
- Spec is changed to exclude this type of address being sent

**Comment by jackiebarnes** [comment]
Internal agreement that the spec needs to be uplifted such that consumers do not send an address with use value of 'work'.

**Comment by RiChallinor** [comment]
@jackiebarnes to be discussed with Jonny asap

**Comment by jackiebarnes** [comment]
Following consultation as to whether this element+use value has already been implemented in Consumer development, the Register Patient API spec will be uplifted to provide clarification as to its non-usage

**Comment by jonnyry** [comment]
Released, closing ticket.
