### ISSUE TITLE
ARHTML Medications - Minor alterations to wording

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#622]
Subsection - Recent Acute Medication

Change the content banner message to: Scheduled End Date is not always captured in the source; where it was not recorded, the displayed date is calculated from start date and days duration

Subsection - Current Repeat Medication

Change the Note following the table definition to: 'The medication below is taken from a list of Repeat Medication Templates in the patient record which may have been amended since they were last issued. See the All Medication Issues subsection for all repeat prescriptions issued'

Subsection - Discontinued Repeat Medications

Change second sentence of description to: This should be the date the clinician has entered as the discontinuation date if available, otherwise the system date of the discontinuation action'
Change the column title 'Discontinued Reason' to 'Discontinuation Reason'

Subsection - All Medication (Summary)

Change 1a in the Date Filter rules to: The provider system MUST return the medication summary data items for all medications whose effective periods overlaps the date range (inclusive) sent by the consuming system
Change the column title 'Discontinued Details' to 'Discontinuation Details'
In column description change references to discontinued reason to use discontinuation

Heading - Additional medication information

Change 2nd paragraph: Details of change to follow as a comment
Change 3rd paragraph to: Naturally Ended medications MUST NOT be included in the Discontinued Repeat Medication subsection and end date and reason MUST NOT be included in Additional Information in Recent Acute Medications or the Discontinuation Details in All Medication (Summary).

Codepen

Apply above changes to column names to the codepen

**Comment by RiChallinor** [comment]
@martinhillyard has this been completed with recent work?

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/0cea609f4053d1b1688ca3117016d083635e6962

and https://github.com/nhsconnect/gpconnect/commit/cb7e8d7098de460dc55877434ea0c527683ade5f
