### ISSUE TITLE
Specify layout for Summary view in accordance with implementation guide for other views

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#623]
The Implementation Guide gives detailed instructions for the layout of the views where they are single or multiple table views, but this excludes the Summary view and cross references the HTML definition for the Summary view. That page does not provide the same level of guidance as the implementation guide.

Apply an equivalent definition for the Summary view or include it in the multiple table views / remove the exclusion.

Provide additional guidance for the use of the section content banner in the Summary view and its relationship to the associated views section content banners and sub-section content banners.

**Comment by RiChallinor** [comment]
@martinhillyard has this been completed with recent work?

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/cd63424bc116964eaa48282fae9476f6ad502d65
