### ISSUE TITLE
Book appointment - description field character limit handling clarification

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#625]
Spec needs uplift to clarify Provider handling:

•	Where Appointment.Description exceeds the specification limit of 100 characters:
o	If the number of characters is less than the corresponding receiving provider field length, then accept and store
o	If the number of characters is more than the corresponding receiving provider field length , then reject as an error with an INVALID_RESOURCE message
 
This represents the most appropriate solution given the need to ensure consumer-sent data is not silently lost, whilst accommodating the differences in Provider systems.
 
We will continue to expect consumers to send 100 characters or less (via the specification), so the above only represents edge cases where a consumer has exceeded the 100 character limit.

**Comment by jackiebarnes** [comment]
Amend spec to ensure Provider systems do not truncate data sent in excess of number of character restraints

**Comment by jonnyry** [comment]
Adding suggested clarified wording from Jackie  "Due to differences in the respective provider system field capacity and to mitigate the risks of silently losing data, the Provider systems SHALL handle as an error consumer sent data which exceeds their capacity."

**Comment by jackiebarnes** [comment]
This wording needs to replace that in the  Book API 'Resource Guidance' warning box:
https://gpconnect.netlify.com/appointments_use_case_book_an_appointment.html#resource-guidance:

On both Book & Amend, this wording needs to be added to the 'Error Handling Provider Systems' section

https://gpconnect.netlify.com/appointments_use_case_book_an_appointment.html#error-handling
https://gpconnect.netlify.com/appointments_use_case_amend_an_appointment.html#error-handling

**Comment by jackiebarnes** [comment]
@jonnyry @MorganB24 @AndrewGuiseley   -  just checking the spec in response to latest assurance query - and any changes to be made to spec for this, need to incorporate corresponding wording not only on the Book Appt page, but also the Amend Appt page, and ensure the 'no truncation' is clear enough, even in Prov response

**Comment by jonnyry** [comment]
As agreed with @jackiebarnes @MorganB24:

- Providers shall never truncate these fields
- Providers shall support the minimum character limits imposed on consumers (description 100 chars, comment 500 chars)
- If providers receive more characters than they can support, an error must be returned to the consumer
- If providers don't support two appointment text fields, they may concatenate the fields together before storing, in order that data isn't lost

**Comment by jonnyry** [comment]
`description` is mandatory - need to update the spec to say so.

**Comment by jonnyry** [comment]
(Move from MAY to MUST)

**Comment by jonnyry** [comment]
Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#book-appointment---description-and-comment-field-character-limit-handling-clarification
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/625
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/221
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/203
