### ISSUE TITLE
HTML example payload doesn't contain all the required resources

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#626]
https://developer.nhs.uk/apis/gpconnect-0-5-1/accessrecord_use_case_retrieve_a_care_record_section.html#payload-response-body

“MUST include the Patient, Practitioner and Organization details for the retrieved care record in a searchset Bundle”

The example payload does not meet the requirement directly above it.

Suggest we find out what providers are returning in order to give a representative payload of what they are returning.

**Comment by jonnyry** [comment]
Also the \r\n shouldn't be present in the payload.

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/3f43a052622a0861d9f2fe675d002832692cb845

**Comment by jonnyry** [comment]
Tim is this fixed in 0.5.1 also?

**Comment by jonnyry** [comment]
It does.
