### ISSUE TITLE
Add a column for Range in the Observations view

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#627]
Range is specified as an optional content in the Value column. It is not defined in the heading and the specification does not give a format for how to return range. 
It should make it clearer for users to view the information if range is given its own column.
Providers should return this information where it is supported in the provider system.

**Comment by martinhillyard** [comment]
See GPC-632 for further detail

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/85481d443202d78597eeae8d863a8f23b06b1f96
