### ISSUE TITLE
Revise Medication headings

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#628]
Change the following headings (and reference to the headings)

Recent Acute Medication > Acute Medication (Last 12 Months)
applies to Summary and Medications view

All Medication (Summary) > All Medication
applies to Medications view only

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/c7c59313db8ff1f0e14a4c2553dac5f9c4396a8a
and https://github.com/nhsconnect/gpconnect/commit/72eb128c9e42c2cb1ae3af2551fd85799b61996d
