### ISSUE TITLE
Separate Major Inactive Problems and Issues into a separate subsection

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#629]
The clinical importance of significant past problems has been raised. This information is sufficiently important to be included in the Summary view. The problems and issues view therefore requires uplifting to separate the content of the inactive problems and issues into two subsections
- Major Inactive Problems and Issues
- Other Inactive Problems and Issues
Supporting definition of major to be included along with definitions for handling no significance for individual records or provider systems not supporting significance levels which meaningfully translate to Major / Minor

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/a1d262c862df01f62c5ccd603a09821e96a43183
and  https://github.com/nhsconnect/gpconnect/commit/199a17d4d60ec09ca9b45d732102b97a1b34e16e
and https://github.com/nhsconnect/gpconnect/commit/3deefb8657c435e9eb8d659f1491903c9b3ce50d
