### ISSUE TITLE
Minor changes to wording

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#631]
Small changes to correct typos or make small non-consequential changes to improve the text. A collection of changes from reviewing the draft copy. Details of changes added in comments.

**Comment by martinhillyard** [comment]
Design decisions

Existing text
Record ‘In-transit’ as a result of GP transfer
...DECISION The provider MUST display a banner message when a record in in-transit.

Change to
Record ‘In-transit’ as a result of GP transfer
...DECISION The provider MUST display a banner message when a record is in-transit.

**Comment by martinhillyard** [comment]
Known issues

Existing text (list item)
some section and subsection content banner messages have been included to assist providers and consumers to understand content population across the providers, for instance to assist consumers to scope test and training activities. These are examples only. Individual provider content messages are not mandated by the specification and may be changed by providers without update to the applicable specification version.

Remove list item - Provider variance page covering provider banner messages has been removed

Existing text (list item)
the scope of the contents for sections and subsections will sometimes vary across providers. Where variances are known, these are described in the sample provider content banner details in each of the HTML view section descriptions.

Change to 
the scope of the contents for sections and subsections will sometimes vary across providers. Consumers should consider this in their testing and training approaches.

Existing text (list item)
not all provider variances (differences between the content returned by each provider within the scope of the specification) are listed within this specification. Consumers should consider this in their testing and training approaches.

Remove list item - provider variance page removed for this version

**Comment by martinhillyard** [comment]
HTML implementation guidance > Layout

Existing text
Subsection content banner
Any exclusion descriptions for a subsection MUST be applicable to that subsection only. Where the exclusion description applies to more than one subsection (but not all), it MUST be repeated in the applicable subsections. A subsection exclusion description MUST NOT be replicated as section content.

Change to
Subsection content banner
Any content descriptions for a subsection MUST be applicable to that subsection only. Where the content description applies to more than one subsection (but not all), it MUST be repeated in the applicable subsections. A subsection exclusion description MUST NOT be replicated as section content.

Existing item - Per Section Default Time Frames table
Recent Acute Medication

Change to
Acute Medication (Last 12 Months)

Existing item - Per Section Default Time Frames table
Inactive problems and issues

Change to
Major Inactive Problems and Issues
Add row item
Other Inactive Problems and Issues        Consumer supplied

**Comment by martinhillyard** [comment]
HTML Views > Summary

Existing item - Purpose
The purpose of this section is to provide a summarised view of the pertinent clinical information regarding a patient within a single screen...

Change to
The purpose of this section is to provide a summarised view of the pertinent clinical information regarding a patient within a single view...

Existing item - Sections
There is only a single main section for the summary section with five subsections:...

Change to
There is only a single main section for the summary section with six subsections:...

Existing item - Last 3 Encounters
This section is an exact replica of the Encounters section with a filter applied to show the three most recent encounters. Further details about this section can be found there including any date range filtering and business rules.

Change to
This section is an exact replica of the Encounters section with a filter applied to show the three most recent encounters. Further details about this section can be found there, including any business rules.

Existing item - Active Problems and Issues
This section is an exact replica of the Active Problems and Issues subsection, which is the first subsection within the Problems and issues section. Further details about this subsection can be found there, including any business rules.

Change to 
This section is an exact replica of the Active Problems and Issues subsection, which is the first subsection within the Problems and Issues section. Further details about this subsection can be found there, including any business rules.

Existing item - Major Inactive Problems and Issues
This section is an exact replica of the Major Inactive Problems and Issues subsection, which is the second subsection within the Problems and issues section. Further details about this subsection can be found there, including any date range filtering and business rules.

Change to
This section is an exact replica of the Major Inactive Problems and Issues subsection, which is the second subsection within the Problems and Issues section. Further details about this subsection can be found there, including any business rules.

**Comment by martinhillyard** [comment]
HTML Views > Problems and issues

Existing item - Active Problems and Issues Date filter
A date filter is applicable for the ‘Active Problems and Issues’ subsection.

Change to
All relevant records MUST be returned.

Existing item - Major Inactive Problems and Issues Table Content
...Provider systems MUST NOT include problems without a significance level in this subsection (for example, if significance is not mandatory)...

Change to
...Provider systems MUST NOT include problems without a significance level in this subsection (for example, if significance is not mandatory and has not be recorded)...

Existing item - Major Inactive Problems and Issues Table Content
...return a subsection content banner to indicate that major problems included in the ‘Other Problems and Issues’ subsection...

Change to
...return a subsection content banner to indicate that any inactive problems are included in the ‘Other Problems and Issues’ subsection...

Existing item - Other Inactive Problems and Issues Table Content
The significance of the problem

Change to
The significance of the problem (meaning, Major or Minor)

**Comment by martinhillyard** [comment]
HTML views > Medications

Existing item - Section Date filter
A date filter is applicable to this section. The date filter MUST be applied to the All Medication (Summary) and All Medication Issues subsections only. All other subsections MUST return all records as defined in the subsection descriptions below, subject to exclusions.

Change to
A date filter is applicable to this section. The date filter MUST be applied to the All Medication and All Medication Issues subsections only. All other subsections MUST return all records as defined in the subsection descriptions below, subject to exclusions.

Existing item - ...

**Comment by martinhillyard** [comment]
HTML views > Referrals

Existing items - Purpose
The purpose of this section is to provide details of any referrals to other care providers.

Change to
The purpose of this section is to provide details of any referrals to or from other care providers.

Existing item - Table columns
Practitioner or Organization

Change to
Practitioner or Organisation

**Comment by martinhillyard** [comment]
Clinical scenarios

Existing item
Patient’s allergies and adverse reactions available to MIU

Change to
Patient’s allergies and adverse reactions available to Minor Injuries Unit (MIU)

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/2009f776e7e523c68319ec8290dc09ea6caace40

**Comment by martinhillyard** [comment]
Correction to the above change requests

HTML implementation guidance > Layout

Existing text - Subsection content banner
... A subsection exclusion description MUST NOT be replicated as section content.

Change to
... A subsection content description MUST NOT be replicated as section content.

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/15f54f3af9689b8312b00da568e116686e398cfe
