### ISSUE TITLE
Realign requirements for date handling in html implementation guidance

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#632]
The HTML implementation guidance layout page covers the requirements for date filtering and standards for date banners. The content has been added to and is set within the requirements for the layout and descriptions of standard banners. The date filtering is not specifically about the layout. 
The flow of the details about the layout and standard banners may be improved by moving the date filtering details outside of the banners section. The clarity of the rules regarding date filters and default dates may be clearer if presented together in its own section with banner content covered separately.
Some additional narrative may need to be added to introduce the sections and cross reference. Specific content to be finalised.

**Comment by tim1ford** [comment]
Updated in https://github.com/nhsconnect/gpconnect/commit/2009f776e7e523c68319ec8290dc09ea6caace40
