### ISSUE TITLE
Provider Variance - Minor wording changes

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#635]
Some of the content banner messages shown on the Provider Variance page are not as currently presented in responses from Vision. Details as follows

Clinical Items
The section content banner differs from the documented one. The banner message in the current Vision response is "Contains clinical items including, but not limited to, Procedures, Diagnoses, Symptoms, Conditions; may include items included in other sections such as Linked Problems"

Problems and Issues
The subsection content banner for Active Problems and Issues has additional content to the documented one. The full banner message in the current Vision response is "All problems included in Active Section. Problem related details are included in other sections."

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/52ff38ad49d1afbe365cdf878c3504bdd7cf7aa5
