### ISSUE TITLE
Migrate core changes from 1.2.3 into 0.5.2 and 0.7.2

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#641]
Migrate core / foundations changes from 1.2.3 release into 0.5.2 / 0.7.2.

Following tickets:

- JWT timing validation issue #640
- Clarify ASID requirements and topologies for "aggregators" #639
- SDS changes to support multiple consumers at a site #638
- Improve clarity of JWT page #634
- Change spec name of "GP Connect" to "GP Connect API" #616
- Consumer shall not amend the Provider service root URL as retrieved from SDS #652

**Comment by tim1ford** [comment]
#616 uplifted in 0.5.1/0.5.2 & 0.7.1/0.7.2

**Comment by tim1ford** [comment]
#637 version updated to 0.7.2 in 0.7.2 spec only

**Comment by jonnyry** [comment]
@tim1ford 

Also adding issue:

Consumer shall not amend the Provider service root URL as retrieved from SDS #652
