### ISSUE TITLE
Some CareConnect-HumanLanguage-1 CodeSystem language descriptions do not match the ISO639-2 list

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#643]
The following languages descriptions in the CareConnect-HumanLanguage-1 CodeSystem do not  match the ISO639-2 language description:

Code | CC Description | ISO Description
-- | -- | --
bh | Bihari | Bihari languages
ii | Sichuan Yi | Sichuan Yi; Nuosu
ps | Pushto | Pushto; Pashto
ro | Romanian | Romanian; Moldavian; Moldovan

Please could this be updated?

Thanks.

**Comment by jlellison** [comment]
This has been updated in line with ISO and released to the FHIR Reference Server https://fhir.nhs.uk/STU3/ValueSet/CareConnect-HumanLanguage-1
