### ISSUE TITLE
Relax cardinality for crossCareSetting identifier 

### ISSUE THREAD

**Issue by mstephens-xsl** [nhsconnect/gpconnect#644]
The cardinality needs to be relaxed for identifier on the following profiles:
- CareConnect-GPC-MedicationStatement-1
- CareConnect-GPC-MedicationRequest-1
- CareConnect-GPC-AllergyGuidance-1

The population guidance will need to be updated to reflect this.

**Comment by jonnyry** [comment]
This change has been backed out:

de5981e374d64bda07c9680b15c8a57aea17bc8a
