### ISSUE TITLE
Allow more than one warning code in the Extension-CareConnect-GPC-ListWarningCode-1 profile

### ISSUE THREAD

**Issue by mstephens-xsl** [nhsconnect/gpconnect#647]
The cardinality for warningCode.code needs to be updated to 1..* so that more than one warning code can be included in a List resource.

The guidance for populating a List will also need to be updated to clarify how it should be populated.

**Comment by jonnyry** [comment]
Removing from 1.2.3 release as per @mstephens-xsl
