### ISSUE TITLE
HTML Implementation Guidance Layout - Change Multitable example

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#649]
The multiple table example in the layout section of the HTML Implementation Guide uses the Problems and Issues view and shows 2 subsections.
The Problems and Issues view was changed from 2 subsections in v0.7.0 to having 3 sections in v0.7.1.
This example should be updated to reflect this or use a different view as the example.

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/93d77fc5216a14dffeb6c8b56107a02e550fbb94
