### ISSUE TITLE
Uplift guidance to call out timePeriod start and end dates are inclusive

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#65]
The end value includes any matching date/time. For example, the period 2011-05-23 to 2011-05-27 includes all the times from the start of the 23rd May through to the end of the 27th of May.

**Comment by jackiebarnes** [comment]
Created content to reflect this on HTML Impl Guide

**Comment by michaelmeasures** [comment]
This is addressed under commit eb4e6761fbf21230dd2247b3d6848d64b8593026
