### ISSUE TITLE
Change warning message for patient transfers

### ISSUE THREAD

**Issue by MikeStacey** [nhsconnect/gpconnect#650]
Change:
“Patient record transfer from previous GP practice not yet complete; any information recorded before dd-Mmm-yyyy has been excluded.”
To:
“Patient record transfer from previous GP practice not yet complete; information recorded before dd-Mmm-yyyy may be missing.”

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/b679d5e653050a64835f92cbb637e5a911e44cb8

**Comment by tim1ford** [comment]
Message applied to 0.7.2 only

**Comment by MikeStacey** [comment]
Also needs to be fixed in structured. The release to fix this needs to be determined.

**Comment by tim1ford** [comment]
@mstephens-xsl - is this going into 1.2.3?
