### ISSUE TITLE
Observations view does not include requirement for units of measure

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#651]
Currently the value field is defined as "Value of the observation". The inclusion of unit of measure is not stated. Units of measure are required where available, so the specification should include reference to them. Range does not require the units of measure to be included, provided the range is at the same unit of measure as stated for the value. If the unit of measure differs between value and range then it should be included in each.

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/63f2a3ca88398a632f8186d54826e6cccf9d4db3
and https://github.com/nhsconnect/gpconnect/commit/262349838ff9d7386faf0ce966330f0d9196b4ac
