### ISSUE TITLE
Provider variance - EMIS content banner message change

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#656]
EMIS have removed the medications content banner message "Medication Max Issues are not shared currently" following a change to populate the Max Issues column.

The change for the Current Medication Issues means the entry for the medication business rules is no longer required, so remove "Repeat medication issues are included as current whilst the repeat course is current (meaning, has not been stopped/expired)"

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/57c7135458c76e115907373195b2a86fe9bce6ec
