### ISSUE TITLE
Add list title codes to List page

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#670]
Add new codes to the list valueset in the page and the profile as per Malcolm's email below. Will also need to decide what consultation values that we want to use.

Peter

Apologies for having taken a week to get back to you on this...

<Peter>
we will need to expand the valueset to include the following areas for which I have suggested some codes:

    Immunisations - 1102181000000102
    Problems – 717711000000103
    Consultaion encounter type - 325851000000107 ?
    Uncategorised data - ?
</Peter>

I agree these are suitable:
•	1102181000000102 | Immunisations (record artifact) |
•	717711000000103 | Problems (record artifact) |
•	325851000000107 | Consultation encounter type (record artifact) |

For 'Uncategorised data' a good fit is ..
•	826501000000100 | Miscellaneous record (record artifact) |
http://www.diseasesdatabase.com/snomed/826501000000100

<Peter>Also for our tiered list representation of a consultation we have picked the following codes. We have a clash here around consultations and would much rather have 2 separate codes. Again would you be able to take a look and let us know what you think would be best?

    Consultation encounter type - 325851000000107 ?
    Topic (EHR)- 25851000000105
    Category (EHR)- 24781000000107
</Peter>

I agree
•	24781000000107 | Category (EHR) (record artifact) |
•	25851000000105 | Topic (EHR) (record artifact) |
are good.

I get the difficulty in having a single SNOMED code representing distinct entities. I can't find a alternative SNOMED concept which fits the bill. 
In an ideal world where you could create both concepts what would their wording be?

Thank you.

Kind regards, Malcolm
Dr Malcolm H Duncan
Tel: (+44)7710 483088

**Comment by MikeStacey** [comment]
Fixed
