### ISSUE TITLE
Uplift the guidance on how systems should handle requests for a superseded patient record linked to a new active patient record.

### ISSUE THREAD

**Issue by MikeHowley** [nhsconnect/gpconnect#69]

**Comment by michaelmeasures** [comment]
For Stage 1 it is expected that provider systems will return a 404 patient not found when a superseded record is requested by a consumer.

**Comment by michaelmeasures** [comment]
#62 will detail returning a 404 patient not found for FoT entry (and further work for Stage 2 or 3 will be handled under this ticket - hence moving to the rc6 release).

**Comment by jackiebarnes** [comment]
Now dealt with in #391
