### ISSUE TITLE
Clarify relationship between problems, ProblemHeader and Condition

### ISSUE THREAD

**Issue by mstephens-xsl** [nhsconnect/gpconnect#691]
We need to clarify the relationship between the below concepts and ensure that it's clear in the spec:

- problem
- ProblemHeader
- Condition

For example, ProblemHeader is used in the diagrams on the linkages page, where the resource name is actually Condition. Condition (ProblemHeader)  could be used instead and would be more consistent with other resource/profiles in the diagrams.

**Comment by MikeStacey** [comment]
Updated the wording in the specification to refer to ProblemHeader (Condition). The relationship between Clinical Areas and Profiles/Resources are covered in the introduction.
