### ISSUE TITLE
Review design decisions page

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#692]
The scope in the design decisions page is not consistent with what is in the specification.

Is the design decisions page really adding value? Do we need it?

**Comment by MikeStacey** [comment]
Take the page out the menu.
Move STU3 to introduction, check fabricated consultation in consultation guidance.

**Comment by PeteSalis** [comment]
I have removed the link from the sidebar to the design decisions page, changed the header so it will not be published, moved the FHIR version to the introduction page and checked the fabricated consultation paragraph is on the consultation page.
