### ISSUE TITLE
Uplift the Clinical Terminologies guidances around the need for DescriptionID in addition to ConceptID for SNOMED CT codes.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#70]
@InteropAdmin needs to update the specification.

**Comment by briandiggle** [comment]
Consider splitting this into some common generic guidance on core area of spec, and specific guidance for capability - e.g. Access Record Structured.

**Comment by james-answer** [comment]
I have added wording on the clinical terminology page to day that DescriptionID should be included in addition to ConceptID where available as it can have a different meaning. We don't need to go into any detail on population of the DescriptionID using the prefered term as this can be found from the ConceptID so just including the ConceptID has the same meaning.

Specific detail is included in the specification uplift for the bundled structured operation. It is better to give specific instructions on when and how to populate the codeable concepts and elemnet extension for the SNOMED CT DescriptionID in the specific guidance for each resource. From the meetings around structured resources and guidance from the clinitions for the different resource, guidance will probably very depending on the concept that is being represented in the resource element.

This additional guidance within structured is being done seperatly from this github issue so I will close this off.
