### ISSUE TITLE
The new values for the “consultation lists of lists” differs - Structured to HTML

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#703]
For the lists gp connect list profile – the new values for the “consultaion lists of lists”  differs between Structured and HTML

**Comment by MikeStacey** [comment]
Refers to difference between guidances and profile definitions not html.

**Comment by PeteSalis** [comment]
Changed the list consultation population page to contain the preferred terms in line with the valueset in the profile.
