### ISSUE TITLE
vaccinationProtocol.doseSequence-is 1..1 in element guidance but is 0..1 in FHIR spec 

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#708]
vaccinationProtocol.doseSequence is marked as 1..1 in the element guidance but is 0..1 in the FHIR spec

**Comment by martinhillyard** [comment]
This is 0..1 in the base FHIR version but it is 1..1 in the Care Connect version, hence the same in the GP Connect profile and guidance.

No change made.
