### ISSUE TITLE
Consultation - meds is not issued but added to record then it adds a textual representation 

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#727]
If meds is not issued in a consultation but added to record then it simply adds a textual representation

**Comment by MikeStacey** [comment]
Depends what the clinician does (and what the system allows). If a medication was added as a medication without an issue (for example prescribed elsewhere or a repeat plan that will be issued in the future) then it must appear as a medication/medical device.
I suppose a medication could be entered directly to the record without using the medication screens (is that allowed), in which case it would appear as uncategorised.
