### ISSUE TITLE
Clarify how local registrations which are not PDS traced should be handled.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#73]
Currently patient data will only be returned for active and traced PDS patients. Note, this places limits on the use cases that can be supported.

**Comment by michaelmeasures** [comment]
The CareConnect profile for Patient has support for the NhsNumberVerificationStatus extension which could be introduced to allow other trace statuses to be managed i.e. "Number present but not traced", "Trace required" etc.

http://www.interopen.org/candidate-profiles/care-connect/CareConnect-NhsNumberVerificationStatus-1.valueset.html

http://www.datadictionary.nhs.uk/data_dictionary/data_field_notes/n/nhs/nhs_number_status_indicator_code_de.asp?shownav=0

**Comment by james-answer** [comment]
Currently there is no use case for allowing non-traced patient details to be returned by the API. This is going to be moved into the next release as no change is required currently. The extension within the patient identifier is not restricted by the profile or the specification so a change to this in future should be non-breaking.

**Comment by james-answer** [comment]
There is currently no use case for this capability, if a use case is identified for non traced patients the spec will be update to meet the requirement at the time. There is no point in trying to guess what use cases we might support in the future and making changes to the spec based on that as we will probably still have to update the spec when a use case is identified if it does not match what we guess we might use the capability for. Therefore I am going to close this ticket and if the need for retrieving non-traced patients arises then the work will be done to meet the used case at the time.
