### ISSUE TITLE
Register a patient - Uplift the Register Patient Operation in the DMS and GitHub to have the NHS Number as a mandatory field.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#74]
http://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.RegisterPatientRequest/gpconnect-registerpatient-operation-1.html

http://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.RegisterPatientResponse/gpconnect-register-patient-1.html

We should consider slicing the identifier field inline with the other resources.

**Comment by jackiebarnes** [comment]
Including mandatory NHS Number and slicing in DMS change 'package'

**Comment by briandiggle** [comment]
Internal decision (HDL-110) which relates to this issue:

1. identifier to 1..* cardinality
2. gender to 0..1 with Must-Support property set to true
3. name to 0..1 with Must-Support set to true (given name and family name remain mandatory as sub-elements of name.
