### ISSUE TITLE
Linkages - Data Proportionality

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#740]
'While the consumer system should aim to avoid the retrieval of large quantities of unnecessary data, it is acceptable for the consumer system to request and retrieve a large proportion of the patient’s record from the provider system and filter out the unnecessary data before presenting it to their clinicians / users where the consumer organisation has determined it is necessary to support patient care.' - Is this legally correct?

**Comment by MikeStacey** [comment]
Yes, this is based on feedback from our IG, team and Caldicott Guardian.
