### ISSUE TITLE
Misc - ValueSet/CareConnect-ListCode-1 - has no codes for imms or uncategorised data 

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#741]
https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-ListCode-1 - has no codes for imms or uncategorised data

**Comment by MikeStacey** [comment]
Codes are agreed and in the guidance just need to update codeset.

**Comment by PeteSalis** [comment]
Emailed John George to ask him to make the changes.

**Comment by PeteSalis** [comment]
John has updated the profiles
