### ISSUE TITLE
Bundle diagram

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#749]
Where the condition resource is used does it need to be made clear that this is in the context of the problem header.

Should there be something to indicate which resources are referenced directly by the returned list. And maybe say that the other resources are referenced by items in the list rather than directly by it.

**Comment by mstephens-xsl** [comment]
I've added some text to the. Condition resources indicating that they're problem headers.

The second issue needs a bit of thought to make sure that the diagram is easily understood.

**Comment by MikeStacey** [comment]
I've updated the diagrams in
https://gpc-structured-futures.netlify.com/accessrecord_structured_development_linkages.html#fhir-profiles-returned-on-query
so that they now show how the list profile is used and what references it contains.
