### ISSUE TITLE
Update the problems and consultations example

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#750]
The JSON example needs to be updated so all the problem header details are correct and all the consultations are contained in a list.

**Comment by PeteSalis** [comment]
Also would need to be amended to model what would be returned by a problem query.

**Comment by mstephens-xsl** [comment]
I've updated the uncategorised data observations so that they are structurally valid and also corrected the 'encounter' field to 'context'

**Comment by mstephens-xsl** [comment]
Corrected problem header so that encounters are recorded in 'context' instead of 'relatedClinicalInformation' and added List for Encounter resources.

**Comment by PeteSalis** [comment]
Updated the example in line with Mike's example. Also uploaded the spreadsheet description.
