### ISSUE TITLE
Do we need examples of how unsupported clinical items will look in json

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#758]
Check that it is included in the consultation example.

Also add a snippet to the page under the title.

**Comment by mstephens-xsl** [comment]
There is an example of this in the consultation example at line 1094 although it doesn't make reference to a particular clinical area:
`
"item": {
            "reference": null,
            "display": "Clinical item not supported by the provider system"
          }
`

**Comment by mstephens-xsl** [comment]
An example has been added
