### ISSUE TITLE
Uplift the Consumer Demonstrator page to include details of where to download the source code

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#76]
We need to add a download link to the demonstrator page so people can easily find the GitHub repo.

https://github.com/nhs-digital/gpconnect

Needs adding to the consumer demonstrator page.

https://nhsconnect.github.io/gpconnect/system_demonstrator.html

**Comment by michaelmeasures** [comment]
@adamjlees can you give it a try putting the issue/ticket number in the commit/pull request so that it closes out / links to this issue. Thanks.

**Comment by adamjlees** [comment]
Merging the pull request didn't close out the issue.
