### ISSUE TITLE
Observation narrative page

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#761]
Needs general review of content and consistency with other pages. Some items to note.

Observation Narrative - Should we have guidance text in the profile page?
Observation Narrative - context. Should this be required?
Observation Narrative - effectiveDateTime - should be required
Observation Narrative - related - this describes the approach to linking bits of text, codes together. Is this consistent with the consultations page

**Comment by MikeStacey** [comment]
Removed the page and merged into Observation - Uncategorised.
