### ISSUE TITLE
Uplift the guidance to state the workshop agreement that local record locking wont impact reading the care record

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#77]
We should add a clarification to the pack along the lines of:

Record locking inside a provider system SHALL NOT impact the ability of the system to fulfill read/query requests to the patient's record.

However, it is understood that there are differing approaches to record locking within the GP principal systems which effect when any local/pending changes are actually committed back to the patient's record.

When a consumer system accesses a patient's record the provider systems SHALL only return data that has been successfully committed back to the patient's record and thus has become available to all users (including users of the provider APIs).

**Comment by adamjlees** [comment]
Is this in design decisions page (accessrecord_design)?

**Comment by adamjlees** [comment]
also accessrecord_development_html_implementation_guide
