### ISSUE TITLE
Interaction Diagram - API page

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#770]
Comment from Katie in IOPS,

https://gpc-structured-futures.netlify.com/accessrecord_structured_development_retrieve_patient_record.html#interaction-diagram

This diagram doesn’t show that the response from the providing system is either a successful return of a bundle or an error response. It looks as if the requester would receive both which is incorrect
It also does not show the http responses.

See https://nhsconnect.github.io/FHIR-ReasonableAdjustments-API/design_interactions_create.html#create-resource for my preferred type of diagram (although for a different interaction).

Also the response would look better as a dotted line to differentiate it from the request.

**Comment by mstephens-xsl** [comment]
The diagram has been updated to use dotted lines for the responses.
