### ISSUE TITLE
Linkages diagram

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#771]
https://gpc-structured-futures.netlify.com/accessrecord_structured_development_linkages.html#gp-connect-fhir-model

Diagram would benefit from a key.
It is very small and cannot be clicked and opened on another page.

The same applies to other diagrams on this page.

**Comment by PeteSalis** [comment]
Again this is a very long page with several diagrams so may benefit from being divided into a number of pages.

**Comment by MikeStacey** [comment]
Added key. All diagrams can now be opened.
