### ISSUE TITLE
Linkages profiles returned on query

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#772]
https://gpc-structured-futures.netlify.com/accessrecord_structured_development_linkages.html#fhir-profiles-returned-on-query

Would this be better condensed down and showing an example response in json format (or linking to one on another page)?

**Comment by MikeStacey** [comment]
I think adding a JSON example would be a good idea. Not sure how we can condense the text and still explain the concept in full.

**Comment by PeteSalis** [comment]
Discussed with Mike. Having updated the consultations example which contains examples of all of these items we agreed that there would be little value in adding bits of it here as snippets.
