### ISSUE TITLE
Linkages - should search be a separate page

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#775]
https://gpc-structured-futures.netlify.com/accessrecord_structured_development_linkages.html#search

Shouldn’t this section have its own page?
It doesn’t seem particularly relevant to this page.

**Comment by PeteSalis** [comment]
I have created a new page which is a copy of the linkages and search page. It was the easiest way to create the new page and you should now just be able to delete the content you don't want out of each one.

**Comment by MikeStacey** [comment]
Pages updated.
