### ISSUE TITLE
Linkages - following a linkage 

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#777]
The textual description here may be better explained using a json example and relevant RESTful queries.

Adding examples may be beneficial

**Comment by MikeStacey** [comment]
Adding a JSON example is a good idea. However I would avoid references to RESTful as we are not a RESTful API and it could cause confusion.

**Comment by PeteSalis** [comment]
Discussed with Mike. Having updated the consultations example which contains examples of all of these items we agreed that there would be little value in adding bits of it here as snippets.
