### ISSUE TITLE
Capitalisation of project name

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#779]
“Defining all the clinical data areas within a patient record has enabled GP Connect access structured record to more clearly define the scope of the project.”

Suggest title casing:
“Defining all the clinical data areas within a patient record has enabled GP Connect Access Structured Record to more clearly define the scope of the project.”

**Comment by Mhitchins** [comment]
Added capitals and transposed 'Structured' and 'Record'.
