### ISSUE TITLE
Retrieve Patient - Structured - Grammar

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#780]
-  Warning yellow box – grammar;  “The parameters can be used together in a   single call or in multiple calls so that information can be retrieved if is   required.” Should be ‘if required’ or ‘if it is required’.   ·         
- The example dates given in the payload   request body are in a different format to the example. 01-02-2017 vs 2017-06-04. Should they be   consistent?   ·         
- Error handling – grammar; “The table   below showns common errors that   may be encountered during this API call, and the returned Spine error code.”   ·         
- Response headers – is this in FHIR STU3?   If so the mime type in the example Content-Type: application/json+fhir;   charset=utf-8 should be application/fhir+json.
- •	Payload Response Body – Allergies, medications, immunisations, and uncategorised data – should the format of the ‘Condition’ be the same as the other resources mentioned?
--

**Comment by mstephens-xsl** [comment]
All issues have been fixed apart from the last one, I need some clarification on what the issue is.

**Comment by Fitz1006** [comment]
Hi Matt,

What’s the number and I’ll dig out the defect.

Thanks

Simon

Simon Fitzgerald
Project Manager
GP Connect
Simon.fitzgerald4@nhs.net<mailto:Simon.fitzgerald4@nhs.net>

07833 588627

**Comment by mstephens-xsl** [comment]
> •	Payload Response Body – Allergies, medications, immunisations, and uncategorised data – should the format of the ‘Condition’ be the same as the other resources mentioned?

It's whether there's anymore information about this issue. If not, we'll have to go back to IOPS to get some clarification.

**Comment by mstephens-xsl** [comment]
I've found the issue and have fixed it.
