### ISSUE TITLE
Linkages - Grammar points

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#782]
•	Search Criteria – Medication and Medical Devices - grammar - For each of the returned plans, the provider system includes data for all of its issues
•	Following a linkage – example – gramar - a retrieved medication is linked to a problem that the clinician wants to review
•	Scale of Search – grammar - The details on how this is implemented in an API can be found in the API definition

**Comment by MikeStacey** [comment]
Fixed
