### ISSUE TITLE
Immunisations - Various - Grammar and formatting

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#783]
•	What is immunisation – grammar - Immunisation, is the process by which an individual’s immune system becomes fortified against an agent (known as the immunogen).
•	What is immunisation – should this definition refer to animals?
•	What is a vaccination – there looks to be references to footnotes that don’t exist.
•	Vaccinations that were not given – grammar - This version of the specification only supports immunisations which have been given to the patient.
•	General inconsistency in how resources are referenced and formatted.

**Comment by Mhitchins** [comment]
Done the first four. Regarding the comment about general inconsistency, in this page the resource name has been formatted in code. Need to check against other pages and ensure consistency.

**Comment by Mhitchins** [comment]
Done
