### ISSUE TITLE
Uncategorised - Grammar - (2)

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#786]
•	Identifier – The term CodeSystem is incorrect in this context, this is a system identifier.
•	effectiveDateTime – grammar -  the effective datetime is the when the consultation took place, not the date it was recorded.
•	Value[x] – grammar - This may be in the form, of but is not limited to one of the following datatypes; a quantity, string or an attachment.

**Comment by Mhitchins** [comment]
Unsure what's required here. Can you clarify?

**Comment by Mhitchins** [comment]
The two grammar point have been completed (effectiveDateTime and Value[x]). Leaving the CodeSystem point to Mike S or Pete.

**Comment by Mhitchins** [comment]
Completed the two grammar points
