### ISSUE TITLE
Consultations - Grammar

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#787]
•	Introduction – typo - bny consumers
•	What is a consultation ? – heading requires space removing
•	Logical structure – grammar - This is mostly generated automatically by the provider system but it may have been manually updated.
•	Logical structure – grammar - In these cases, the clinical items are recorded directly under the topic the same way they are recordinged under a heading.
•	Approach – may be good to get the diagrams to open in a new tab as the text is difficult to read.
•	Consultation notes – grammar - When reflecting these in FHIR it is important they that these two methods are represented in a way

**Comment by Mhitchins** [comment]
Already fixed
