### ISSUE TITLE
Encounter - Grammar points and formatting

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#790]
•	Status – grammar - Hence, use the most appropriate value from limited set available.
•	Type – grammar - Carries the consultation type  as displayed by the system via the…
•	Type – outstanding To Do item
•	Elements not used section is in a different format to similar pages

**Comment by Mhitchins** [comment]
These have been fixed by Mike Stacey with the exception of:
 Type – outstanding To Do item

**Comment by MikeStacey** [comment]
#730 already covers outstanding To Do item.
