### ISSUE TITLE
Various grammer and fotmat related observations

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#800]
- Development Intro page - Change "access record structured" to "Access Record Structured"
- Development Linkages - typo - last para - mediations needs to change to medications 
- Linkages Medications and medical devices - type - add an "S" onto "request" (The consumer system request(s) all items after the start date)
- Linkages Probs - needs consistent representation of Significance/Status of significance/status
- Linkages - scale of search - fill stop missing after the final para

-

**Comment by Mhitchins** [comment]
Development Intro page - Change "access record structured" to "Access Record Structured" DONE

Development Linkages - typo - last para - mediations needs to change to medications DONE

Linkages Medications and medical devices - type - add an "S" onto "request" (The consumer system request(s) all items after the start date) DONE

Linkages Probs - needs consistent representation of Significance/Status of significance/status DONE

Linkages - scale of search - fill stop missing after the final para DONE
