### ISSUE TITLE
Imms guidance - 

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#802]
- GP Systems that support a note entry against the immunisation MUST populate the text to the note element. Additionally, any other information relevant to the immunisation which does not have a suitable element within the immunization profile MUSTbe populated to the note as a key value pair. 

- Should refer to Immunization resource (profile?!)
This comment also applies to the text ‘ For example, the vaccine manufacturer is recorded in a free text field so is not suited as a reference to an organization resource…’ in the same section.

**Comment by martinhillyard** [comment]
Changed as part of commit 5ba3e9c
