### ISSUE TITLE
Immunisations identifier

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#804]
This is sliced to include a cross-care setting identifier which MUST be populated. The codeSystem for this identifier ishttps://fhir.nhs.uk/Id/cross-care-setting-identifier.

Isn’t this a NamingSystem URL and not a codeSystem?

**Comment by martinhillyard** [comment]
The identifier description is the same for all profiles so they should all be treated the same i.e. immunizations should not be changed in isolation

**Comment by PeteSalis** [comment]
Updated Imms page to refer to system identifier
