### ISSUE TITLE
uncategoriseddata - guidance format

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#807]
https://gpc-structured-futures.netlify.com/accessrecord_structured_development_uncategoriseddata_guidance#qualifiers       and        
https://gpc-structured-futures.netlify.com/accessrecord_structured_development_uncategoriseddata_guidance#values
--
These sections make reference to FHIR Observation elements, which would benefit from the grey formatting used elsewhere, i.e. Observation

**Comment by Mhitchins** [comment]
Completed
