### ISSUE TITLE
Problems - Grammar

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#813]
https://gpc-structured-futures.netlify.com/accessrecord_structured_problems.html#extensionactualproblem
--

References may be created to MedicationRequest,   AllergyIntolerance, Immunization, Observation - Uncategorised.       Suggest:       References may be created to MedicationRequest,   AllergyIntolerance, Immunization, Observation – Uncategorised resources.
--

**Comment by Mhitchins** [comment]
Updated as per suggestion
