### ISSUE TITLE
Problems search criteria

### ISSUE THREAD

**Issue by MikeStacey** [nhsconnect/gpconnect#816]
https://gpc-structured-futures.netlify.com/accessrecord_structured_development_retrieve_patient_record.html

The problem search fields do not reflect the requirements defined in:
https://gpc-structured-futures.netlify.com/accessrecord_structured_development_linkages.html#problems-1

In particular, significance and status are searched for in pairs with support for multiple pairs searches.
Example: Search for all Major Active, Minor Active, Major Inactive

**Comment by mstephens-xsl** [comment]
The spec has been updated, this also requires the IOPS team to update the OperationDefinition

**Comment by MikeStacey** [comment]
Had a look in https://gpc-structured-futures.netlify.com/accessrecord_structured_development_retrieve_patient_record.html and it still looks wrong.

**Comment by mstephens-xsl** [comment]
@MikeStacey the includeProblems parameter can be included multiple times with each instance containing a pair of problem significance and status codes. Could you provide more details on why it looks wrong?

**Comment by mstephens-xsl** [comment]
The guidance has been clarified to say how parameters should be used to request multiple pairs of problems.
