### ISSUE TITLE
immunisations & uncategorised data from the operation request are missing their counterpart in the list response 

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#818]
includeAllergies -> Allergies and adverse reactions / "Ended allergies
includeMedication -> Medications and medical devices
includeConsultations -> Consultation
includeProblems -> Problems
includeImmunisations -> ????
includeUncategorisedData -> ???

Note: this looks a lot like #702 - may be a duplicate

**Comment by martinhillyard** [comment]
Looks like this is the same as #702. List guidance now includes codes for immunisations and uncategorised. Couldn't spot any omission of imms or uncat in the retrieve record or the list page
