### ISSUE TITLE
Enable visits to be returned in retrieve and read appointment calls

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect#826]

**Comment by dilrajbhatia2** [comment]
03/10/2019
Agreed with Cath that we will not return the location of a Patient in the retrieval of booked home visits as it could be misleading. We would instead provide guidance in the API spec that location of home visit depends on the local policy of the GP Practice.
We discussed that Location for home visit is usually retrieved from the Patient record – residential address. In scenarios where Patient is in a temporary location such as 
Respite care or their relative’s place then the Practice’s home visit local process/policy might be followed where the address may be captured in the appointment or maybe in a paper/pen etc.
