### ISSUE TITLE
Should we consider using Observation for the placeholders

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect#828]
Currently we are using an empty reference.

Would we be better off using a Observation as it would be easier to process?

**Comment by mstephens-xsl** [comment]
I think we decided against this due to backwards compatibility rules. For example, with Referrals we'd be changing a Reference from an Observation to a ReferralRequest.

**Comment by MikeStacey** [comment]
Discussed internally and agreed the existing approach works best for consumers.
