### ISSUE TITLE
Microtest - Change GPConnect-Appointment-1 id field from 1..1 to 0..1

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect#830]
The id field in the https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1 profile is incorrectly defined as mandatory (1..1).

However when creating an Appointment ID must not be supplied.

The GP Connect provider testing pack correctly doesn't supply an ID but this means it's not conformant to the profile. (i.e. If you validate the resource by FHIR validators it says the testing software is incorrect)

Mandatory requirement for ID should be removed.

**Comment by jonnyry** [comment]
Change was made in:  https://github.com/nhsconnect/STU3-FHIR-Assets/commit/ef509a7a35c13a734e66676ec1d3115709e21b79#diff-1ab02bf7df16276d2ff36ae7ed0c13b4
Currently investigating the change.

**Comment by jonnyry** [comment]
Request sent to Interoperability team to revert .id field 1..1 change in Appointments and Foundations profiles back to 0..1.

**Comment by jonnyry** [comment]
Kev - this is now complete and has been been published to the FHIR server.
