### ISSUE TITLE
Consumer systems SHOULD  - (this should be MUST)

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#843]
https://gpconnect-documents.netlify.com/accessrecord_documents_development_search_patient_documents.html#_include-parameters

For “Consumer systems SHOULD send the following parameters in the request: …type”.  In DocumentReference.type this is 1..1 (Mandatory).  So shouldn’t type be removed from that bullet point list and be included in the above “MUST” bulleted list?  i.e:

•	type MUST be included  

John George

**Comment by mstephens-xsl** [comment]
DocumentReference.type is mandatory in the profile, however there is nowhere in FHIR that states that the equivalent search parameter must always be present. Our use cases require that this is a SHOULD.
