### ISSUE TITLE
Why has “DELETE” been missed out

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#845]
https://gpconnect-documents.netlify.com/designprinciples_open_api_principles.html#fhir

Regarding “synchronous endpoints using GET, POST and PUT HTTP verbs”.
Why has “DELETE” been missed out? This is mentioned in https://www.hl7.org/fhir/STU3/http.html.
john george

**Comment by mstephens-xsl** [comment]
The GP Connect APIs doesn't have any DELETE endpoints so it hasn't been included in the design principles.
