### ISSUE TITLE
Top menu items are a repeat and a bit misleading

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#846]
Dilraj
I believe you are collating feedback on Document spec version 1.0.0 beta. I think the top menu items are a repeat and a bit misleading as it provides overview of GPConnect whereas the user might be expecting an overview of GPConnect documents.
We can move the items in the red box in the following image to a core spec:

**Comment by mstephens-xsl** [comment]
@Fitz1006 @dilrajbhatia2 Was there an image with this comment?

**Comment by dilrajbhatia2** [comment]
Hi @Fitz1006 .. I am not collating feedback on Document spec version 1.0.0 beta but your feedback is helpful. @mstephens-xsl  I do not have an image for this.
