### ISSUE TITLE
Documents - Multiple calls to ID patient and document

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#851]
TPP - Annelie  -	https://developer.nhs.uk/apis/gpconnect-documents-1-0- /accessrecord_documents_development_api_session.html
Documents 
Why do TPP need to do the first call to find the patient and then a second call to query the documents? Why not do both in one as Structured Meds and Allergies does at the moment?

**Comment by Fitz1006** [comment]
Updated to V1.4.1 from V1.4.0

**Comment by dilrajbhatia2** [comment]
@mstephens-xsl  Hi Matt, please could you look into this query.

**Comment by mstephens-xsl** [comment]
The find patient API has been added to locate the logical id for a patient from a provider. This is then used in the search Document API. This follows the RESTful API that has been implemented for appointment management, the single call approach for structured wasn't used as structured uses a FHIR operation and not a RESTful API.
