### ISSUE TITLE
content.attachment.data which is Required/Optional

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#852]
TPP - Annelie
-	https://developer.nhs.uk/apis/gpconnect-documents-1-0-0/accessrecord_documents_development_search_patient_documents.html indicates that in response to a query about a patient’s documents, the provider should return a document reference.
https://developer.nhs.uk/apis/gpconnect-documents-1-0-0/accessrecord_documents_development_documents.html shows that the document reference resource has a field for content.attachment.data which is Required/Optional. What does this mean? If a consumer has just queried the patient’s documents, then the provider shouldn’t be returning the actual data for all the documents – there can be tens/hundreds of documents on one patient’s record and so a message containing the data for all the documents of a patient could be huge. Surely in response to a query, we should not send the actual data for the documents. The actual data should only be sent once the consumer has requested to retrieve a specific document.

**Comment by dilrajbhatia2** [comment]
Agree with you Annelie. Attachment.data field should not be populated when it is a response to search documents query. 
Attachment.data field should be populated when it is a response to retrieve a binary of the given document. We will update the specs to reflect this data population requirement.

**Comment by dilrajbhatia2** [comment]
1. We have removed the content.data.attachment field from the DocumentReference profile as it will not be populated in Search Documents API request
2. @mstephens-xsl  - Please could you update the Search Document API spec to provide guidance on point 1

**Comment by mstephens-xsl** [comment]
There was no change required in the API, this just needs the profile guidance to be updated.

**Comment by dilrajbhatia2** [comment]
I have updated the profile guidance. I have informed John Geroge(technical modeller of the profile) to make it an optional field.
