### ISSUE TITLE
Documents Format and File extensions

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#853]
-	The Document Format section under Document Guidance (https://developer.nhs.uk/apis/gpconnect-documents-1-0-0/accessrecord_documents_development_documents_guidance.html) gives a list of formats or file extensions that the document can have. This is far from a complete list. A couple of concerns here: What should the provider do if the document is in a format not listed here? E.g. some format specific to an ECG result. The provider certainly doesn’t want to be converting the document into one of these formats. The list of document references should just include all documents the provider holds regardless of file format. It should be up to the consumer, which is the only thing that knows what file formats it can handle, to either let the user request the document itself, or say it cannot be handled.  It would be more helpful if the consumer only retrieves documents that they can see are in a format they can handle. They could give some indication if there are documents available that are in formats that they can’t handle.
Further to this, Content.document.format seems to be populated from this valueSet: http://hl7.org/fhir/ValueSet/formatcodes. We’re not sure what benefit this gives. Really, the file extension is the interesting thing about the document format. Other information could be gained from the description and content.attachment.title fields. Can this format field just be removed?

**Comment by dilrajbhatia2** [comment]
Hi @PeteSalis , please could you advise on this issue

**Comment by dilrajbhatia2** [comment]
Following was discussed with @PeteSalis and @Fitz1006 today:
1. @PeteSalis  agrees with TPP that we may not need a white list of document types. We can provide guidance that no local file types are allowed. For example, docman may have created local file types of .xx or .xxx 
2. There is a white list of Document Formats allowed in spine which is used in Mesh.
3. @mstephens-xsl  Please could you look into git ticket about formats allowed.

**Comment by dilrajbhatia2** [comment]
As discussed and agreed in the clinical review meeting on the 16th of October 2019, we would remove the white list of documents and provide guidance that 'Documents of industry-standard format are allowed. Any local document formats are not allowed.'
