### ISSUE TITLE
Use case for Document reference

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#854]
-	TPP - Annelie
What’s the intended difference between the created and indexed fields on the DocumentReference resource? Can you give us a use case where these two fields are populated differently?

**Comment by dilrajbhatia2** [comment]
A created field depicts the date on which the given document was created or the event date.  
Indexed field depicts when this document was added by the GP Practice to their clinical system.
Example, a GP Practice received a document dated 10/10/2019 from a Hospital on the 15/10/2019, so the creation DateTime is 10/10/2019 and indexed would be 15/10/2019.
