### ISSUE TITLE
Access to 1.0.0 spec - clone

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#856]
TPP - Annelie

-	The specification for Documents which lives here: https://developer.nhs.uk/apis/gpconnect-documents-1-0-0, seems to be a clone of the existing specification for retrieving the structured record. Why is it being treated separately? It’s making navigating the specification quite difficult. In a similar vein, it’s difficult to work out from the release notes, exactly what on the referenced pages has changed.

**Comment by mstephens-xsl** [comment]
The specification has been published separately as this is the direction of travel for GP Connect specs. Each capability will be implemented as a separate logical FHIR server and will be published in a separate specification. It will also allow the capabilities to be versioned independently.

The release notes apply to each specification.
