### ISSUE TITLE
Payload size - Documents retrieval

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#857]
TPP - Annelie,

The spec aside, we have some technical concerns too. Some of these messages could be huge. One patient can have hundreds of letters in their record and so querying all of these could require the provider to return hundreds of DocumentReferences. Similarly, some documents themselves are big and so messages containing even just one document could be big. Given this, what are the SLAs around this? How quickly is the provider expected to respond? Making content.attachment.data be 0..0 (mandatory to not include the document binary data in the DocumentReference), and only include it in the GetBinary message, would go a long way to alleviate these concerns.

**Comment by dilrajbhatia2** [comment]
@PeteSalis @mstephens-xsl Please could you advise on this.
As per my understanding, I would add the following text to content.attachment.data field:
"Provider SHALL populate content.attachment.data field in API response for Retrieve a patient’s document API request. 
Provider SHALL NOT populate content.attachment.data field in API response for Search a patient’s documents API request."
This would tie in what Annelie has suggested.
@PeteSalis  Do we also need to change the cardinality to 0..0?

**Comment by dilrajbhatia2** [comment]
As per discussion with @PeteSalis and @Fitz1006 , the following has been agreed:
1. Response to first point of 'return hundreds of DocumentReferences' in search documents API call - It would not be an issue as a binary of the file would not be returned in the document reference.
2. Response to 'making content.attachment.data be 0..0' point - we have moved the content.attachment.data field to 'Do not populate' section of DocumentReference as binary of document is never returned in the search documents API call.  It would be returned in Retrieve Document API call and be populated in binary resource. @mstephens-xsl  Please, could you update the search document API spec to reflect this point.
3. @mstephens-xsl  Please could you look into the payload SLA/expectation of API when retrieving binary of the document issue.
4. @Fitz1006 has also suggested that we need to do VnP testing for AR-Documents capability and plan for it.
