### ISSUE TITLE
Release notes - [PROVIDER_ROUTING_SEGMENT] mandatory

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#858]
TPP Annelie

Release Notes https://developer.nhs.uk/apis/gpconnect-documents-1-0-0/overview_release_notes_1_0_0.html
 
-	Can you provide some further information around the change to make the [PROVIDER_ROUTING_SEGMENT] mandatory? Is this an attempt to handle cases where a provider may use a third party document repository? E.g. the case where EMIS would integrate with DocMan. If this isn’t the intended purpose of the change, can you also please explain how such a case will be handled?

**Comment by mstephens-xsl** [comment]
This has been added to support multi provider scenarios. Each capability would be exposed as a separate FHIR server and the [PROVIDER_ROUTING_SEGMENT] would be set accordingly, for example, 'gpc-structured' or 'gpc-documents'.
