### ISSUE TITLE
ReferralRequest resource

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#859]
EMIS - Matt

Referral Guidance
	-----
	ReferralRequest resource
	-----
		***Priority - Confirm that if no priority is held this element must not be populated
		***AuthoredOn - perhaps provide more guidance here, there is a reasonable definition for this that explains the date here https://developer.nhs.uk/apis/gpconnect-1-4-0

**Comment by martinhillyard** [comment]
The priority does not have to be populated if the source record does not hold a priority.

**Comment by martinhillyard** [comment]
Change applied for the date of referral to reference to section in the guidance page
