### ISSUE TITLE
Investigations scope in GP Connect

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#860]
EMIS - Matt H

Investigations
-----
	Investigations Guidance
	-----
		Investigations scope in GP Connect
		-----
			***investigations results that have been entered in a GP system using a code as an individual item (these may have a value and other qualifiers associated with them) - confirm these should subseqently displayed in the uncategorised data call

**Comment by PeteSalis** [comment]
Responded to Matt via email. This is correct.
