### ISSUE TITLE
Diagnosticreport- EMIS

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#861]
EMIS - Matt H

DiagnosticReport
	-----
		basedOn - Note: EMIS cannot produce a link back to the original test request so cannot provide a link back to a ProcedureRequest
		INTERNAL instant - should be the IssueTime recorded against the report in the DB (CareRecord.Report.IssueTime)
		***Performer - Cannot populate, could idenitfy a link back to the interchange and the trading partner it was received from but this is not stored as an organisation and cannot be referenced
		Specimen - can provide some details (see specimen notes)
		codedDiagnosis - don't code an outcome of the report with a link
		conclusion - output associated text from the report to here?

**Comment by PeteSalis** [comment]
Responded to Matt H via email. Confirmed his understanding.
