### ISSUE TITLE
EMIS - Specimen - AccessionIdentifier

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#862]
EMIS - Matt H
Specimen
	-----
		accessionIdentifier - map this to CareRecord.ReportSpecimen.SpecimenReference?
		status - not held by web, cannot provide
		***type - we don't currently code a type but do have a textual representation of the type, believe we should populate this as part of the text element in the codeableconcept? Could expand guidance?
		receivedTime - pull from CareRecord.ReportSpecimen.DateTimeReceivedbyLab
		collection.extension(fastingStatus) - Web does record this in some form but need to understand more about this. Appears to simply be a code of F held to indicate fasting and no other detail
		collection.collector - no details held
		collection.collected - pull from CareRecord.ReportSpecimen.SampleDateTime?
		collection.Qunatity - doesn't appear to be recorded in EMIS Web when we receive results
		collection.bodysite - doesn't appear to be recorded in EMIS Web when we receive results
		note - pull from CareRecord.ReportSpecimen.SpecimenComment

**Comment by PeteSalis** [comment]
Made amendments to specimen.type to clarify meaning.
