### ISSUE TITLE
EMIS - Observations - Test Group

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#863]
EMIS - Matt H

Observation - Test Group
	-----
		code -  pull from CareRecord.Report.CodeId
		***Performer - Cannot populate, could idenitfy a link back to the interchange and the trading partner it was received from but this is not stored as an organisation and cannot be referenced

**Comment by Fitz1006** [comment]
Updated owner to PS

**Comment by PeteSalis** [comment]
Updated Matt H via email. No spec change necessary.
