### ISSUE TITLE
EMIS - Parameters added to OperationDefinition GPConnect-GetStructuredRecord-Operation-1 to support retrieval of new resources

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#867]
EMIS Matt H

Parameters added to OperationDefinition GPConnect-GetStructuredRecord-Operation-1 to support retrieval of new resources
	-----
		***Should the date period guidance between investigations and referrals not be the same? and if not why the difference?

**Comment by mstephens-xsl** [comment]
investigationSearchPeriod has been updated to include guidance about date periods.
