### ISSUE TITLE
EMIS - Code and term for pathology missing

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#868]
EMIS - Matt H

Updated the list profile to include codes for investigations and referrals
	-----
		***Code and term for pathology are missing

**Comment by mstephens-xsl** [comment]
@PeteSalis do you know if this was looked at during curation?

**Comment by PeteSalis** [comment]
Added in the term for Investigations and results. John G has added this to the profile for List in 1-4-1 too.
