### ISSUE TITLE
EMIS - DocumentReference

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#870]
EMIS - Matt H

***masterIdentifier - guidance doesn't seem clear that this is supposed to be the version of the document in particular
		***content.attachment.data - no guidance around this? Should this be a reference to a binary resource?

**Comment by dilrajbhatia2** [comment]
I have added text:
URL to retrieve the document, this **MUST** be populated when the document is available. It is a reference to the document data i.e. the binary resource.
URL SHALL point to the same content as found in content.attachment.data when populated.
added text:
The actual data of the attachment - a sequence of bytes. In XML, represented using base64. 
The base64-encoded data SHALL be expressed in the same character set as the base resource XML or JSON.

**Comment by dilrajbhatia2** [comment]
@mstephens-xsl's comment:
I’m not sure we need to use content.attachment.data as the data would always be returned in a Binary resource in the retrieve document API 
It probably needs to go into the do not populate section.

**Comment by dilrajbhatia2** [comment]
Closing as I have updated the Document Reference profile with the following changes:
1. Updated description of MasterIdentifier
2. Moved content.attachment.data to 'Do not populate' section in the DocumentReference page as the data of the document would be populated in FHIR Binary resource.
