### ISSUE TITLE
EMIS - Search for a patient's documents

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#871]
EMIS - Matt H

Search parameters
		-----
			***Still unclear as to the user case of all the search parameters i.e. custodian, author, facility. The amount of parameters seems very over the top and not necessary. Will a person looking for documents actually try and search by custodian???

**Comment by dilrajbhatia2** [comment]
@mstephens-xsl  I think Custodian field is not required as a search parameter. There is also a requirement to be able to search for documents in a given date range, is it reflected in the spec?

**Comment by mstephens-xsl** [comment]
Custodian has been removed, created is used to search for docs in a given date range.
