### ISSUE TITLE
EMIS - Include Parameters

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#872]
EMIS - Matt H
_include Parameters
		-----
			***difference between the two organiszation parameters isn't clear
			***saying consumers should send the additional parameters feels wrong, they should all be mays. Should send 'facility' doesn't feel useful

**Comment by dilrajbhatia2** [comment]
Agree with EMIS comment:
point 1: we can update the description of the two organisations custodian organisation and author orgnanisation.
point 2: We can update the text to say - 
Consumer systems MAY send the following parameters in the request:
- created
- facility
- author
- type

**Comment by mstephens-xsl** [comment]
the descriptions for the orgs in point 1 have been updated

the search params section has been updated to reflect point 2

**Comment by dilrajbhatia2** [comment]
Hi @mstephens-xsl - I went to this link https://gpconnect-documents.netlify.com/accessrecord_documents_development_search_patient_documents.html - it does not show the changes you have done.
