### ISSUE TITLE
Sensitive Documents

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#880]
Some documents may be sensitive. 
Do we need to retrieve sensitive documents from the clinical system?

**Comment by dilrajbhatia2** [comment]
23/10/2019 Discussed this issue with Peter Short and Michelle Durham and following decision was taken:
GPC AR-Documents API spec is currently restricted to search and retrieval of documents that have NO internal confidentiality policy applied, but may in future expand to include all documentation subject to data controller determination. (Future proofing/sign-posting)
Recommendation for Strategic solution: Create a capability that enables the data controller(GP Practice) to control who can access documents/information from the clinical record that has confidentiality/protection policy applied. 
Clinical record systems and linked document management products need to support confidentiality/protection policy marking and implementation on an item by item basis.

**Comment by dilrajbhatia2** [comment]
done.
