### ISSUE TITLE
Unfiled Documents

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#881]
Documents that are not yet filed in the clinical system are still available to view in the clinical system.
The clinicians believe that it would be worth retrieving unfiled documents too.

**Comment by dilrajbhatia2** [comment]
23/10/2018 Discussed this issue with Peter Short and Michelle Durham. The following decision was taken:
GPC AR-Documents API spec would allow search and retrieval of documents that have not been reviewed and filed. It would enable the health and care workers to have access to the required documents at the right time and take informed decisions with the patient for their health care.
Recommendation for Strategic solution: Create a capability that enables the data controller(GP Practice) to control who can access documents that have not yet been reviewed. 

It has been considered that there is the possibility that some of these documents might be deemed and subsequently marked confidential at clinical review, but at this stage the advising Clinicians decision is that clinical safety and continuity concerns outweigh the small risk of disclosure of data that may merit consideration of confidentiality policy application. (balanced decision of benefit v risk)
