### ISSUE TITLE
Filesize SLAs

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#882]
We need an SLA around the size of the document. GP to GP project are creating an SLA for the same.

**Comment by Fitz1006** [comment]
Hi Dilraj,  I had a conversation with Pete who believes that the GP2GP SLA may not work for Structured as the service operates on a batch basis and the SLA is 24 hours

**Comment by dilrajbhatia2** [comment]
Hi @Fitz1006 , Thanks for letting me know. I think this issue is duplicate of #857. Matt is looking into #857

**Comment by st3v3nhunt** [comment]
Closing as associated issue has been resolved/closed also.
