### ISSUE TITLE
Specification inconsistency - GPC Practitioner

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect#893]
Specification https://developer.nhs.uk/apis/gpconnect-1-2-3/foundations_use_case_read_a_practitioner.html
and https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Practitioner-1

Have different interpretations of the telecom field
github page says SHALL NOT populate telecom field and GPC Profile says MAY/MAY NOT.

Suspect the rule is SHALL NOT. Would prefer the profile to be correct(ed) as it is easier to follow and find restrictions like these.

**Comment by jonnyry** [comment]
The profiles are intentionally looser/more flexible than the requirements on each API definition.  The API definition requirements override those set by the profile.
