### ISSUE TITLE
Missing link mystery

### ISSUE THREAD

**Issue by Mhitchins** [nhsconnect/gpconnect#894]
On this page in the 1.4.0 spec,  https://developer.nhs.uk/apis/gpconnect-1-4-0/overview_engage.html, the link to the Access Record Structured design decision doesn't work.

It's the same for 1.4.1 and 1.3.1. When you go back to 1.2.4, though, it's fine but I can't work out what changed between 1.2.4 and 1.3.1.

As I understand it the Access Record Structured capability doesn't have a link to the design page either, so I'm wondering if the link on the getting started page is still needed (?)

**Comment by martinhillyard** [comment]
Link has been removed. No longer a general decision decisions page in structured. Decision decisions are covered in the development area across various pages of guidance.
