### ISSUE TITLE
Profile Issue - CareConnect-GPC-MedicationRequest-1 repeatInformation should not be mandatory

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect#898]
Error in profile which prevents resources from validating correctly (using HL7 Validation + CareConnect)
Profile 
 https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-MedicationRequest-1
has Extension https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-MedicationRepeatInformation-1

as mandatory, it is not mandatory for acutes and differs from acceptance test pack rules.

**Comment by PeteSalis** [comment]
Need to check with IOPS if we have any resource from them currently. Should be a 2 min job for John George or another of the modellers but they don't have any GP Connect NWR tickets open.
