### ISSUE TITLE
ValueSet/Specification Inconsistency - AllergyIntolerance

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect#903]
Guidance here:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_allergies_guidance.html#reaction-cardinality

Says: AllergyIntolerance.reaction.manifestation MUST be coded as the nullFlavor NI.
(we want to record the severity of the reaction)

However this code is not part of the ValueSet https://fhir.nhs.uk/STU3/ValueSet/CareConnect-AllergyManifestation-1 
and so invalid. **Warning** is:

_None of the codes provided are in the value set https://fhir.nhs.uk/STU3/ValueSet/CareConnect-AllergyManifestation-1 (https://fhir.nhs.uk/STU3/ValueSet/CareConnect-AllergyManifestation-1, and a code should come from this value set unless it has no suitable code) (codes = http://hl7.org/fhir/v3/NullFlavor#NI)_

**Comment by PeteSalis** [comment]
This should reference the CareConnect valueset,
https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-AllergyManifestation-1

**Comment by PeteSalis** [comment]
This was updated by John George before christmas and is now using the correct valueset
