### ISSUE TITLE
Uplift Access Record pack with example conformance profile

### ISSUE THREAD

**Issue by adamjlees** [nhsconnect/gpconnect#91]
uplift integration_spine_security_proxy_implementation_guide and conformance page

**Comment by adamjlees** [comment]
Decided to uplift the pack with an example conformance profile in each capability pack, to illustrate a server only supporting the minimum items for that capability.  The conformance page will show the full example with all capabilities.

**Comment by michaelmeasures** [comment]
@adamjlees can you please add the FHIR StructureDefintion profile details to the conformance statement example you've worked up for the Access Record HTML pack. thanks.

**Comment by michaelmeasures** [comment]
@adamjlees can you look at this today please.
