### ISSUE TITLE
Meds list needs adding to consultation diagram in linkages page

### ISSUE THREAD

**Issue by mstephens-xsl** [nhsconnect/gpconnect#920]
A medications list needs adding to the diagram that appears in the linkages page:

[https://gpconnect-1-3-2.netlify.com/accessrecord_structured_development_linkages.html#consultations](https://gpconnect-1-3-2.netlify.com/accessrecord_structured_development_linkages.html#consultations)

**Comment by PeteSalis** [comment]
This has now been updated to include the Meds List.
