### ISSUE TITLE
Uplift guidance on auditing to reference GPSoC audit requirements

### ISSUE THREAD

**Issue by adamjlees** [nhsconnect/gpconnect#93]
integration_cross_organisation_audit_and_provenance

**Comment by michaelmeasures** [comment]
@jackiebarnes I've added some of the requirements from the GPSoC IG Requirements for GP Systems document taken from your IG requirements spreadsheet. If you get time would you mind having a look and checking the content against what you're expecting.

**Comment by michaelmeasures** [comment]
1c32d3e121bb6f0ea9e5804455f61a4b1918f37e is the commit.

**Comment by michaelmeasures** [comment]
Going forward with this as the first cut but will need refining in 1.0.0-rc.6 based on feedback and if we decide to upload excel spreadsheets of the full set of GPSoC requirements (including IM1 requirements).
