### ISSUE TITLE
Documents - Full Url in bundle questions

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#940]
**From Nigel Boney - EMIS**	
Taking the foundation spec,  a consumer isn't supposed to send to an endpoint directly, it’s supposed to go via the ssp, eg :-

GET https://[proxy_server]/https://[provider_server]/[fhir_base]/Patient?identifier=[system]|[value]

Where the "https://[provider_server]/[fhir_base]" is supposed to have been retrieved from SDS via an LDAP query on a particular interactionid. The spec then says what params to append.

(And I believe our FHIR endpoints will reject requests which don't originate from the ssp).

Taking example from 

https://developer.nhs.uk/apis/gpconnect-documents-1-0-1/accessrecord_documents_development_fhir_examples_documents.html

                fullUrl is being populated with endpoints which don’t exist, eg :-
		
"fullUrl": http://exampleGPSystem.co.uk/GP0001/STU3/1/gpconnect-documents/Patient/04603d77-1a4e-4d63-b246-d7504f8bd833
					
Documents doesn’t support a patient read – no interactionid

		
		"fullUrl": http://exampleGPSystem.co.uk/GP0001/STU3/1/gpconnect-documents/PractitionerRole/e0244de8-07ef-4274-9f7a-d7067bcc8d21
	
Documents doesn’t support a practioner role read – no interactionid
	
		
		"fullUrl": http://exampleGPSystem.co.uk/GP0001/STU3/1/gpconnect-documents/Organization/db67f447-b30d-442a-8e31-6918d1367eeb
	
Documents doesn’t support a organisation  read – no interactionid
				
		"fullUrl": http://exampleGPSystem.co.uk/GP0001/STU3/1/gpconnect-documents/Practitioner/6c41ebfd-57c3-4162-9d7b-208c171a2fd7
		
	
Documents doesn’t support a practioner read – no interactionid
		
		
Even if these “foundation” resources were populated with there Foundation (+Appoiment) equivalent, a client shouldn’t be using these urls as it need to prefix the ssp (and as foundation/appoitments is a separate capability, it doesn’t mean that that agreement exists on the ssp).

**Comment by dilrajbhatia2** [comment]
@mstephens-xsl  please could you help with this technical query on endpoints?

**Comment by Fitz1006** [comment]
@mstephens-xsl, @dilrajbhatia2   - Hi Matt, Dilraj - can this one be closed?

**Comment by mstephens-xsl** [comment]
Answered in #967
