### ISSUE TITLE
In the new Guidance on the use of CodeableConcept:

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#946]
o	examples have been updated with “userSelected” but the JSON examples are consistently wrong in representing the value as a string instead of a boolean.
o	It may be useful to have a more detailed change/version history in the document. Appendix A goes some way to address this but the embedded document/link cannot be opened.

**Comment by mstephens-xsl** [comment]
I've taken a look at the spec and I can't find any uses of userSelected in the examples, these would only be in the guidance doc.

**Comment by PeteSalis** [comment]
Updated the 1-2-6 branch with the new version of the document so it will pull through the changes to 1-5-0.
