### ISSUE TITLE
A lot of broken links due to case mismatch

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#948]
e.g. “uncategoriseddata “ instead of “uncategorisedData“ in https://developer.nhs.uk/apis/gpconnect-1-3-2/accessrecord_structured_development_uncategoriseddata_guidance.html

**Comment by martinhillyard** [comment]
Checked through the structured capability pages and have made 4 changes as per the check ins above

**Comment by PeteSalis** [comment]
Closing as this refers to specific links that have been fixed. This will be part of the publication process.
