### ISSUE TITLE
paragraph Dealing With Confidential Items is in the wrong place or at the wrong hierarchy

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#950]
It seems the paragraph Dealing With Confidential Items is in the wrong place or at the wrong hierarchy level as it splits the list of profiles from the section entitled “FHIR profiles returned on query”

**Comment by martinhillyard** [comment]
Change made in the feature branch to make this a subsection rather than main section. Needs merging to 1.3.2 and 1.5.0 releases

**Comment by PeteSalis** [comment]
I have corrected the 1-5-0 feature branch.
