### ISSUE TITLE
release notes for Updates to Profiles state that “participant valueset now has an option for AUTH to specify who recorded the Encounter

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#951]
The release notes for Updates to Profiles state that “participant valueset now has an option for AUTH to specify who recorded the Encounter” but I can’t find the value in http://hl7.org/fhir/stu3/valueset-encounter-participant-type.html

**Comment by PeteSalis** [comment]
Awaiting for this to be fixed by IOPS before correcting.

**Comment by PeteSalis** [comment]
Updated the encounter page with the new code for recorder, REC, as published by IOPS.
