### ISSUE TITLE
Access Record Structured interactions

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#954]
Interacterationid doesn’t fit published pattern? 

Operation | Interaction I
-- | --
Get Structured Record | urn:nhs:names:services:gpconnect:structured:fhir:operation:gpc.getstructuredrecord-1
Read metadata (Access Record Structured) | urn:nhs:names:services:gpconnect:structured:fhir:rest:read:metadata-1

**Comment by jonnyry** [comment]
The interaction ID naming policy has been updated:

https://developer.nhs.uk/apis/gpconnect-1-2-6/integration_interaction_ids.html#gp-connect-interaction-id-naming-policy

We now support two patterns - the existing, and the new, hence the differences in the pattern of the two interaction IDs.
