### ISSUE TITLE
V1.2.3 FoT Entry V1.2.6 FoT Exit Risk

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#958]
Potential issue with “separate FHIR sever” with 1.2.3 pilot and deploying 1.2.6 (or even updating the 1.2.3 endpoints)., If pilot 1.2.3 with structured – then SDS Endpoint registration will use the same naming as per appointments and structured :- https://dns/ODS/STU3/1/GPConnect 

1.2.6 spec would like distinct “fhir server endpoints” per capability :-
                Appts/Foundation, Structured, Documents

This means SDS endpoints would be reqistered along lines of: https://dns/ODS/STU3/1/GPConnect. https://dns/ODS/STU3/1/Structured.  https://dns/ODS/STU3/1/Docs 

Our controllers would be altered so that each endpoint processed those interactions. What happens if the 1.2.3 pilot/endpoint is on the existing “GPConnect” name and 1.2.6 is rolled out?

**Comment by jonnyry** [comment]
Yes appreciate this is slightly more complicated for those capabilities that are live or about to go live.

In this instance, we'd recommend continuing to support the capability on the old and new paths concurrently, until the SDS endpoints have been changed over to point to the new path, when the old path can be withdrawn.

However it is worth checking the dates of the structured first of types with the GP Connect programme first (and comparing with release dates for this change) to determine whether this will be an issue for changing the path of the structured capability.
