### ISSUE TITLE
Observations on the document search parameters

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#965]
Can NhsDigital please comment on these observations on the document search parameters:

 Facility is a {&facility=[care_setting_type]} instead of {&facility=[OrgTypeCodeSystem]|[OrgTypeCode]}
https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_search_patient_documents.html#request

Custodian is missing from the search parameters
https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_search_patient_documents.html#request
https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_search_patient_documents.html#search-parameters

**Comment by mstephens-xsl** [comment]
facility has been updated to reflect the data type
