### ISSUE TITLE
Access Document – examples of parameters

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#968]
For clarity, please provide examples on the population of each parameter for the Search for a patient's document request.

Exclusions can be applied to the created parameter as examples of these have been provided at the following link:
https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_fhir_examples_documents.html

**Comment by dilrajbhatia2** [comment]
Hi @mstephens-xs Please  could you help us with the code examples of search parameters

**Comment by mstephens-xsl** [comment]
Closed as duplicate of [962](https://github.com/nhsconnect/gpconnect/issues/962)
