### ISSUE TITLE
Access Document – codeable concept values

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#969]
Please clarify whether a Codeable Concept’s code value for a document   reference's type is a snomed concept id, description id or otherwise       e.g. "type": { "coding": [ { "system":   "http://snomed.info/sct", "code": "824331000000106",   "display": "Inpatient final discharge letter" }
--

**Comment by dilrajbhatia2** [comment]
@PeteSalis Please could you help with this query?
