### ISSUE TITLE
Access Document - refsets

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#970]
One of the Refsets contains “record artefacts”. The SNOMED CT   implementation guidance states these are not suitable for adding to clinical   records   The other Refset contains “qualifier values”. These are not suitable   for use as standalone codes as qualifiers by definition add context to   another code.       We would suggest a review, checking with NHS Terminology Standards   and perhaps other Refsets with more relevant codes are produced.       These are the refsets in question:   99000381000000107 Correspondence care setting type   999000391000000109 Correspondence document type
--

**Comment by dilrajbhatia2** [comment]
@PeteSalis  Please could you help us with this query on refsets.

**Comment by Fitz1006** [comment]
Duplicate of #964
