### ISSUE TITLE
Access Document – search parameters

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#971]
Please comment on these observations on the document search   parameters:       Facility is a {&facility=[care_setting_type]}   instead of {&facility=[OrgTypeCodeSystem]\|[OrgTypeCode]}   https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_search_patient_documents.html#request           Custodian is missing from the   search parameters   https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_search_patient_documents.html#request      https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_search_patient_documents.html#search-parameters
--

**Comment by dilrajbhatia2** [comment]
Custodian is missing from search parameters as when we are searching a GP Practice for documents, we already know that the GP Practice is the custodian.
Agree that 'facility' is care setting type.
 @mstephens-xsl, Please could you provide your viewpoint on this.
