### ISSUE TITLE
Access Document – date searches

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#972]
Please confirm if the date in the document search request example 
as 'created=ge2019-0624' should instead be 'created=ge2019-06-24' to be a valid fhir yyyy MM dd date.

https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_fhir_examples_documents.html

**Comment by dilrajbhatia2** [comment]
@PeteSalis  Please could you help with the dateformat
