### ISSUE TITLE
Immunisations – not given in uncat data

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#976]
The “not given”/”dissent” entries (codeids) will appear as “uncategorised data” by default from EMIS Web. Is the expectation that the “Uncat” call will filter these “imms dissents” out (because they’re classed as imms)?

**Comment by martinhillyard** [comment]
That is the intention for the consent / dissent records. Those should be returned as observations against an immunisation request and excluded from an uncategorised response. If there are coded "not given" entries which would be returned in an immunisation resource where not given are requested, we have not specified that those must be removed from the uncategorised response. The code hierarchies to exclude from uncategorised are listed here: https://developer.nhs.uk/apis/gpconnect-1-5-0/accessrecord_structured_development_immunization_guidance.html#consent-or-dissent-for-vaccination
