### ISSUE TITLE
Consultations containing documents

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#988]
Consultations   - What is the behaviour if a consultation contains a document/attachment?
--

**Comment by dilrajbhatia2** [comment]
AR-Documents - [DocumentReference ](https://developer.nhs.uk/apis/gpconnect-1-5-0/access_documents_development_documentreference.html#contextencounter)profile provides a link to the associated consultation in context.encounter field.  @PeteSalis  please could you help to find out if there is an equivalent field with ref to associated documents in consultations in AR-Structured capability? I tried to find it but could not locate a link to documents in consultations.

**Comment by dilrajbhatia2** [comment]
[Linkages](https://developer.nhs.uk/apis/gpconnect-1-5-0/accessrecord_structured_development_linkages.html) would show the linked document references for a given consultation.  The api spec says the consultation would return:
_The DocumentReference profile of any linked Documents
Only include the document metadata in any returned DocumentReference profile, do not include the binary file
Include the ProblemHeader (Condition) profile of any Problems linked to the returned Documents_

It would return metadata of the document and url to retrieve the document from.
