### ISSUE TITLE
Uplift specification to include guidance on Controlled Drugs

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#99]
Controlled drugs need to be flagged as such at the line item level as this is clinically relevant supporting information.

**Comment by adamjlees** [comment]
Brought into scope of rc.6 following meeting Monday 11th

**Comment by jackiebarnes** [comment]
Part of Medications revision work for ARHTML - Future

**Comment by martinhillyard** [comment]
Review of issue under JIRA item GPC-628

**Comment by tim1ford** [comment]
Fixed in https://github.com/nhsconnect/gpconnect/commit/f9e00876eeef8f5e8b40d181ded4b2518bf72fdf
