### ISSUE TITLE
Accept/Content-Type needs updating across all specifications

### ISSUE THREAD

**Issue by tim1ford** [nhsconnect/gpconnect#991]
The GP Connect specifications have an incorrect value of **application/json+fhir;charset=utf-8** listed in the request header examples.

This needs to be updated to **application/json+fhir**

**Comment by tim1ford** [comment]
https://github.com/nhsconnect/gpconnect/commit/51b350cda502610f925f3e04fb5c1461cef97922

https://github.com/nhsconnect/gpconnect/commit/5e72d44352b261749d96f8e4a7851ffbec3c0eee

**Comment by tim1ford** [comment]
0.5.3 and 0.7.3 updated

**Comment by st3v3nhunt** [comment]
Closing as done.
