### ISSUE TITLE
Remove acute handwritten prescription type

### ISSUE THREAD

**Issue by martinhillyard** [nhsconnect/gpconnect#993]
The acute handwritten prescription type is included in the GP Connect valueset, but is not in the current valueset associated to the care connect profile and we do not believe it is being used by providers.

Propose to remove it from the GP Connect valuest and use 'acute' in the event any systems have prescriptions flagged as handwritten.

Needs spec and profile change to medication request.

**Comment by Fitz1006** [comment]
SF - Request sent to IOPS to complete the profile change - 18/9/20

**Comment by martinhillyard** [comment]
Change applied, release note required

**Comment by martinhillyard** [comment]
Change applied for 1.5.0
